<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi500P2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode' => '500.6.9.2', 'keterangan' => 'Produksi Benih Serealia'],
            ['kode' => '500.6.9.3', 'keterangan' => 'Produksi Benih Aneka Kacang dan Umbi'],
            ['kode' => '500.6.9.4', 'keterangan' => 'Kelembagaan Benih'],
            ['kode' => '500.6.10', 'keterangan' => 'Budidaya Serealia'],
            ['kode' => '500.6.10.1', 'keterangan' => 'Padi Irigasi dan Rawa'],
            ['kode' => '500.6.10.2', 'keterangan' => 'Padi Tadah Hujan dan Lahan Kering'],
            ['kode' => '500.6.10.3', 'keterangan' => 'Jagung'],
            ['kode' => '500.6.10.4', 'keterangan' => 'Serealia Lain'],
            ['kode' => '500.6.11', 'keterangan' => 'Budidaya Aneka Kacang dan Umbi'],
            ['kode' => '500.6.11.1', 'keterangan' => 'Kedelai'],
            ['kode' => '500.6.11.2', 'keterangan' => 'Ubi Kayu'],
            ['kode' => '500.6.11.3', 'keterangan' => 'Aneka Kacang'],
            ['kode' => '500.6.11.4', 'keterangan' => 'Aneka Umbi'],
            ['kode' => '500.6.12', 'keterangan' => 'Tanaman Pangan'],
            ['kode' => '500.6.12.1', 'keterangan' => 'Pengeloalan Data Organisasi Pengganggu Tumbuhan'],
            ['kode' => '500.6.12.2', 'keterangan' => 'Dampak Perubahan Iklim'],
            ['kode' => '500.6.12.3', 'keterangan' => 'Teknoogi Pengendalian Organisme Pengganggu Tumbuhan'],
            ['kode' => '500.6.12.4', 'keterangan' => 'Pengelolaan Pengendalian Hama Tepadu'],
            ['kode' => '500.6.13', 'keterangan' => 'Pascapanen Tanaman Pangan'],
            ['kode' => '500.6.13.1', 'keterangan' => 'Padi'],
            ['kode' => '500.6.13.2', 'keterangan' => 'Jagung dan Serealia alin'],
            ['kode' => '500.6.13.3', 'keterangan' => 'Kedelai dan Aneka Kacang'],
            ['kode' => '500.6.13.4', 'keterangan' => 'Aneka Umbi'],
            ['kode' => '500.6.14', 'keterangan' => 'Pengolahan Hasil Pertanian'],
            ['kode' => '500.6.14.1', 'keterangan' => 'Tanaman Pangan'],
            ['kode' => '500.6.14.2', 'keterangan' => 'Holtikurtura'],
            ['kode' => '500.6.14.3', 'keterangan' => 'Perkebunan'],
            ['kode' => '500.6.14.4', 'keterangan' => 'Peternakan'],
            ['kode' => '500.6.15', 'keterangan' => 'Mutu dan Standariasi'],
            ['kode' => '500.6.15.1', 'keterangan' => 'Standardisasi'],
            ['kode' => '500.6.15.2', 'keterangan' => 'Penerapan dan Pengawasan Jaminan Mutu'],
            ['kode' => '500.6.15.3', 'keterangan' => 'Akreditasi dan Kelembagaan'],
            ['kode' => '500.6.15.4', 'keterangan' => 'Kerjasama dan Harmonisasi'],
            ['kode' => '500.6.16', 'keterangan' => 'Pengembangan Usaha dan Investasi'],
            ['kode' => '500.6.16.1', 'keterangan' => 'Kemitraan dan Kewirausahaan'],
            ['kode' => '500.6.16.2', 'keterangan' => 'Investasi'],
            ['kode' => '500.6.16.3', 'keterangan' => 'Promosi Dalam Negeri'],
            ['kode' => '500.6.16.4', 'keterangan' => 'Promosi Luar Negeri'],
            ['kode' => '500.6.17', 'keterangan' => 'Pemasaran Domestik'],
            ['kode' => '500.6.17.1', 'keterangan' => 'Informasi Pasar'],
            ['kode' => '500.6.17.2', 'keterangan' => 'Pemantauan Pasar dan Stabilisasi Harga'],
            ['kode' => '500.6.17.3', 'keterangan' => 'Sarana dan Kelembagaan Pasar'],
            ['kode' => '500.6.17.4', 'keterangan' => 'Jaringan Pemasaran'],
            ['kode' => '500.6.18', 'keterangan' => 'Administrasi Penelitian, Pengkajian, dan Pengembangan, antara lain: Rencana Kerja, TOR/Proposal, Pembentukan Tim Kerja dan Surat menyurat'],
            ['kode' => '500.6.19', 'keterangan' => 'Hasil Penelitian, Pengkajian, dan Pengembangan'],
            ['kode' => '500.6.19.1', 'keterangan' => 'Hasil Penelitian dan Pengembangan'],
            ['kode' => '500.6.19.2', 'keterangan' => 'Hasil Pengkajian dan Kebijakan dan Strategi'],
            ['kode' => '500.6.20', 'keterangan' => 'Diseminasi'],
            ['kode' => '500.6.21', 'keterangan' => 'Publikasi Hasil Penelitian/ Pengkajian'],
            ['kode' => '500.6.21.1', 'keterangan' => 'Pameran, Temu Lapang, Temu Bisnis, Demlot, Seminar Lokakarya, Temu Karya, Workshop'],
            ['kode' => '500.6.21.2', 'keterangan' => 'Jurnal, Buletin, Monograf, Prosiding, dan Publikasi lainnya'],
            ['kode' => '500.6.22', 'keterangan' => 'Bimbingan Teknis Penelitian, Pengkajian, dan Pengembangan'],
            ['kode' => '500.6.23', 'keterangan' => 'Forum Komunikasi Penelitian dan Pengembangan'],
            ['kode' => '500.6.24', 'keterangan' => 'Data Penelitian dan Pengembangan'],
            ['kode' => '500.6.25', 'keterangan' => 'Evaluasi Penelitian/ Pengkajian dan Pengembangan'],
            ['kode' => '500.6.26', 'keterangan' => 'Hak Atas Kekayaan Intelektual (HAKI)'],
            ['kode' => '500.6.26.1', 'keterangan' => 'Hak Cipta'],
            ['kode' => '500.6.26.2', 'keterangan' => 'Hak Paten Sederhana'],
            ['kode' => '500.6.26.3', 'keterangan' => 'Hak Paten Biasa'],
            ['kode' => '500.6.26.4', 'keterangan' => 'Hak Merek'],
            ['kode' => '500.6.26.5', 'keterangan' => 'Pendaftaran Varietas Tanaman'],
            ['kode' => '500.6.26.6', 'keterangan' => 'Permohonan Hak PVTT Tanaman Semusim dan Tahunan'],
            ['kode' => '500.6.26.7', 'keterangan' => 'Permohonan HKI yang ditolak'],
            ['kode' => '500.6.27', 'keterangan' => 'Pelayanan Perijinan Pertanian'],
            ['kode' => '500.6.27.1', 'keterangan' => 'Sarana I (bidang pupuk, pestisida, alat dan mesin pertanian)'],
            ['kode' => '500.6.27.2', 'keterangan' => 'Sarana II (bidang benih tanaman, bahan penelitian, teknis pangan segar asal tumbuhan, teknis pengalihan saham perkebunan)'],
            ['kode' => '500.6.27.3', 'keterangan' => 'Sarana III (bidang bibit, karkas, daging, dan jeroan, pakan ternak, obat hewan, dan teknis sumber daya genetik ternak)'],
            ['kode' => '500.6.28', 'keterangan' => 'Pelayanan Hukum'],
            ['kode' => '500.6.28.1', 'keterangan' => 'Sertifikasi'],
            ['kode' => '500.6.28.2', 'keterangan' => 'Pertimbangan Hukum'],
            ['kode' => '500.6.29', 'keterangan' => 'Karantina Pertanian'],
            ['kode' => '500.6.29.1', 'keterangan' => 'Karantina Tumbuhan'],
            ['kode' => '500.6.29.2', 'keterangan' => 'Karantina Hewan'],
            ['kode' => '500.6.30', 'keterangan' => 'Bimbingan Teknis'],
            ['kode' => '500.6.31', 'keterangan' => 'Evaluasi'],
            ['kode' => '500.7', 'keterangan' => 'PETERNAKAN'],
            ['kode' => '500.7.1', 'keterangan' => 'Kebijakan di bidang Peternakan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.7.2', 'keterangan' => 'Peternakan dan Kesehatan Hewan'],
            ['kode' => '500.7.2.1', 'keterangan' => 'Perbibitan Ternak, Antara lain: Produksi Bibit Ternak Ruminansia, Produksi Bibit Ternak Non Ruminansia, Penilaian dan Pelepasan Bibit ternak, Pengembangan Bibit Ternak, Surat Rekomendasi & Persetujuan Pemasukan/ Pengeluaran'],
            ['kode' => '500.7.2.2', 'keterangan' => 'Pakan Ternak'],
            ['kode' => '500.7.2.3', 'keterangan' => 'Budidaya Ternak'],
            ['kode' => '500.7.2.4', 'keterangan' => 'Kesehatan Hewan, Antara lain: Pengamatan Penyakit Hewan, Pencegahan dan Pemberantasan Penyakit Hewan, Perlindungan Hewan, Kelembagaan dan Sumber Daya Kesehatan Hewan, Pengawasan Obat Hewan'],
            ['kode' => '500.7.2.5', 'keterangan' => 'Kesehatan Masyarakat Veteriner dan Pascapanen, Antara lain: Pascapanen, Higien Sanitasi, Pengawasan Sanitary dan Keamanan Produk Hewan, Zoonosis dan Kesejahteraan Hewan, Pengujian dan Sertifikasi Produk Hewan, Surat Rekomendasi & Persetujuan Pemasukan/ Pengeluaran'],
            ['kode' => '500.7.3', 'keterangan' => 'Bimbingan Teknis'],
            ['kode' => '500.7.4', 'keterangan' => 'Evaluasi'],
            ['kode' => '500.8', 'keterangan' => 'PERKEBUNAN'],
            ['kode' => '500.8.1', 'keterangan' => 'Kebijakan di bidang Perkebunan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.8.2', 'keterangan' => 'Tanaman Semusim'],
            ['kode' => '500.8.2.1', 'keterangan' => 'Identifikasi dan Pendayagunaan Sumber Daya Tanaman Semusim'],
            ['kode' => '500.8.2.2', 'keterangan' => 'Perbenihan Tanaman Semusim'],
            ['kode' => '500.8.2.3', 'keterangan' => 'Budidaya Teknologi Budidaya Tanaman Semusim'],
            ['kode' => '500.8.2.4', 'keterangan' => 'Pemberdayaan Tanaman Semusim'],
            ['kode' => '500.8.3', 'keterangan' => 'Tanaman Rempah & Penyegar'],
            ['kode' => '500.8.3.1', 'keterangan' => 'Identifikasi dan Pendayagunaan Sumber Daya Tanaman Rempah & Penyegar'],
            ['kode' => '500.8.3.2', 'keterangan' => 'Perbenihan Tanaman Rempah & Penyegar'],
            ['kode' => '500.8.3.3', 'keterangan' => 'Budidaya Tanaman Rempah & Penyegar'],
            ['kode' => '500.8.3.4', 'keterangan' => 'Pemberdayaan dan Kelembagaan Tanaman Rempah & Penyegar'],
            ['kode' => '500.8.4', 'keterangan' => 'Tanaman Tahunan'],
            ['kode' => '500.8.4.1', 'keterangan' => 'Identifikasi dan Pendayagunaan Sumber Daya Tanaman Tahunan'],
            ['kode' => '500.8.4.2', 'keterangan' => 'Perbenihan Tanaman Tahunan'],
            ['kode' => '500.8.4.3', 'keterangan' => 'Budidaya Tanaman Tahunan'],
            ['kode' => '500.8.4.4', 'keterangan' => 'Pemberdayaan dan Kelembagaan Tanaman Tahunan'],
            ['kode' => '500.8.5', 'keterangan' => 'Perlindungan Perkebunan'],
            ['kode' => '500.8.5.1', 'keterangan' => 'Identifikasi dan Pengendalian Organisme Pengganggu Tumbuhan Tanaman Semusim, Perlindungan Perkebunan'],
            ['kode' => '500.8.5.2', 'keterangan' => 'Identifikasi dan Pengendalian Organisme Pengganggu Tumbuhan Tanaman Rempah dan Penyegar'],
            ['kode' => '500.8.5.3', 'keterangan' => 'Identifikasi dan Pengendalian Organisme Pengganggu Tumbuhan Tanaman Tahunan'],
            ['kode' => '500.8.5.4', 'keterangan' => 'Dampak Perubahan Iklim dan Pencegahan Kebakaran'],
            ['kode' => '500.8.6', 'keterangan' => 'Pascapanen dan Pembinaan Usaha'],
            ['kode' => '500.8.6.1', 'keterangan' => 'Pascapanen Tanaman Semusim, Rempah dan Penyegar'],
            ['kode' => '500.8.6.2', 'keterangan' => 'Pascapanen Tanaman Tahunan'],
            ['kode' => '500.8.6.3', 'keterangan' => 'Bimbingan Usaha dan Perkebunan Berkelanjutan'],
            ['kode' => '500.8.6.4', 'keterangan' => 'Gangguan Usaha dan Penanganan Konflik'],
            ['kode' => '500.8.7', 'keterangan' => 'Bimbingan Teknis Perkebunan'],
            ['kode' => '500.8.8', 'keterangan' => 'Evaluasi Perkebunan'],
            ['kode' => '500.9', 'keterangan' => 'PERINDUSTRIAN'],
            ['kode' => '500.9.1', 'keterangan' => 'Kebijakan di bidang Perindustrian yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.9.2', 'keterangan' => 'Iklim Usaha dan Kerja Sama'],
            ['kode' => '500.9.2.1', 'keterangan' => 'Industri Manufaktur'],
            ['kode' => '500.9.2.2', 'keterangan' => 'Industri Agro'],
            ['kode' => '500.9.2.3', 'keterangan' => 'Industri Unggulan Berbasis Teknologi Tinggi'],
            ['kode' => '500.9.2.4', 'keterangan' => 'Industri Kecil dan Menengah'],
            ['kode' => '500.9.3', 'keterangan' => 'Promosi Industri'],
            ['kode' => '500.9.3.1', 'keterangan' => 'Industri Manufaktur'],
            ['kode' => '500.9.3.2', 'keterangan' => 'Promosi Industri Agro'],
            ['kode' => '500.9.3.3', 'keterangan' => 'Industri Unggulan Berbasis Teknologi Tinggi'],
            ['kode' => '500.9.3.4', 'keterangan' => 'Industri Kecil dan Menengah'],
            ['kode' => '500.9.4', 'keterangan' => 'Standarisasi dan Teknologi'],
            ['kode' => '500.9.4.1', 'keterangan' => 'Industri Manufaktur'],
            ['kode' => '500.9.4.2', 'keterangan' => 'Industri Agro'],
            ['kode' => '500.9.4.3', 'keterangan' => 'Industri Unggulan Berbasis Teknologi Tinggi'],
            ['kode' => '500.9.4.4', 'keterangan' => 'Industri Kecil dan Menengah'],
            ['kode' => '500.9.5', 'keterangan' => 'Hak dan Kekayaan Intelektual'],
            ['kode' => '500.9.5.1', 'keterangan' => 'Industri Manufaktur'],
            ['kode' => '500.9.5.2', 'keterangan' => 'Industri Agro'],
            ['kode' => '500.9.5.3', 'keterangan' => 'Industri Unggulan Berbasis Teknologi Tinggi'],
            ['kode' => '500.9.5.4', 'keterangan' => 'Industri Kecil dan Menengah'],
            ['kode' => '500.9.6', 'keterangan' => 'Industri Hijau'],
            ['kode' => '500.9.6.1', 'keterangan' => 'Industri Manufaktur'],
            ['kode' => '500.9.6.2', 'keterangan' => 'Industri Agro'],
            ['kode' => '500.9.6.3', 'keterangan' => 'Industri Unggulan Berbasis Teknologi Tinggi'],
            ['kode' => '500.9.6.4', 'keterangan' => 'Industri Kecil dan Menengah'],
            ['kode' => '500.9.7', 'keterangan' => 'Analisis Kerja Sama Industri Unggulan Kabupaten/Kota'],
            ['kode' => '500.9.8', 'keterangan' => 'Monitoring dan Evaluasi Kompetensi Inti Industri (Provinsi dan Kabupaten/Kota)'],
            ['kode' => '500.9.9', 'keterangan' => 'Pengembangan Infrastruktur Pendukung Pengembangan Kawasan Industri'],
            ['kode' => '500.9.10', 'keterangan' => 'Fasilitasi Pengembangan Kawasan Industri'],
            ['kode' => '500.9.11', 'keterangan' => 'Kerja Sama Ketahanan Industri Internasional'],
            ['kode' => '500.9.12', 'keterangan' => 'Standarisasi'],
            ['kode' => '500.9.12.1', 'keterangan' => 'Standar'],
            ['kode' => '500.9.12.2', 'keterangan' => 'Penyiapan Penerapan'],
            ['kode' => '500.9.12.3', 'keterangan' => 'Infrastruktur Standar'],
            ['kode' => '500.9.13', 'keterangan' => 'Pengkajian Kebijakan dan Iklim Usaha Industri'],
            ['kode' => '500.9.13.1', 'keterangan' => 'Kebijakan Industri'],
            ['kode' => '500.9.13.2', 'keterangan' => 'Perpajakan dan Tarif'],
            ['kode' => '500.9.13.3', 'keterangan' => 'Pengembangan Model Industrial'],
            ['kode' => '500.9.14', 'keterangan' => 'Pengkajian Industri Hijau dan Lingkungan Hidup'],
            ['kode' => '500.9.14.1', 'keterangan' => 'Industri Hijau'],
            ['kode' => '500.9.14.2', 'keterangan' => 'Lingkungan Hidup'],
            ['kode' => '500.9.14.3', 'keterangan' => 'Energi'],
            ['kode' => '500.9.15', 'keterangan' => 'Teknologi dan Hak Kekayaan Intelektual'],
            ['kode' => '500.9.15.1', 'keterangan' => 'Pengkajian dan Penerapan Kebijakan Teknologi Industri'],
            ['kode' => '500.9.15.2', 'keterangan' => 'Pengkajian dan Penerapan Inovasi Teknologi Industri'],
            ['kode' => '500.9.15.3', 'keterangan' => 'Pengembangan Hak Kekayaan Intelektual'],
            ['kode' => '500.9.16', 'keterangan' => 'Monitoring dan Evaluasi Kompetensi Industri'],
            ['kode' => '500.10', 'keterangan' => 'ENERGI DAN SUMBER DAYA MINERAL'],
            ['kode' => '500.10.1', 'keterangan' => 'Kebijakan di bidang Energi dan Sumber Daya Mineral yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.10.2', 'keterangan' => 'Rekomendasi Kegeologian'],
            ['kode' => '500.10.2.1', 'keterangan' => 'Mitigasi Gunung Api, Gempa Bumi, Tsunami, dan Gerakan Tanah'],
            ['kode' => '500.10.2.2', 'keterangan' => 'Air Tanah dan Geologi Tata Lingkungan'],
            ['kode' => '500.10.2.3', 'keterangan' => 'Pertambangan'],
            ['kode' => '500.10.2.4', 'keterangan' => 'Panas Bumi'],
            ['kode' => '500.10.2.5', 'keterangan' => 'Geosains'],
            ['kode' => '500.10.2.6', 'keterangan' => 'Pengukuran Time Domain Electromagnetic (TDEM)'],
            ['kode' => '500.10.2.7', 'keterangan' => 'Kelayakan Lingkungan'],
            ['kode' => '500.10.3', 'keterangan' => 'Penelitian Kegeologian'],
            ['kode' => '500.10.3.1', 'keterangan' => 'Administrasi pelaksanaan penelitian'],
            ['kode' => '500.10.3.2', 'keterangan' => 'Administrasi tenaga penelitian'],
            ['kode' => '500.10.3.3', 'keterangan' => 'Administrasi penggunaan peralatan penelitian'],
            ['kode' => '500.10.3.4', 'keterangan' => 'Log-book peralatan survei/peralatan uji/kalibrasi'],
            ['kode' => '500.10.3.5', 'keterangan' => 'Hasil penelitian dan penyelidikan kegeologian'],
            ['kode' => '500.10.3.6', 'keterangan' => 'Sumber Daya Geologi'],
            ['kode' => '500.10.3.7', 'keterangan' => 'Air Tanah dan Geologi Tata Lingkungan'],
            ['kode' => '500.10.3.8', 'keterangan' => 'Vulkanologi dan Mitigasi Bencana Geologi'],
            ['kode' => '500.10.3.9', 'keterangan' => 'Survei Geologi'],
            ['kode' => '500.10.4', 'keterangan' => 'Inventarisasi dan evaluasi kegeologian'],
            ['kode' => '500.10.4.1', 'keterangan' => 'Sumber Daya Geologi'],
            ['kode' => '500.10.4.2', 'keterangan' => 'Vulkanologi dan Mitigasi Bencana Geologi'],
            ['kode' => '500.10.4.3', 'keterangan' => 'Air Tanah dan Geologi Tata Lingkungan'],
            ['kode' => '500.10.4.4', 'keterangan' => 'Survei Geologi'],
            ['kode' => '500.10.4.5', 'keterangan' => 'Konservasi'],
            ['kode' => '500.10.5', 'keterangan' => 'Administrasi Pelayanan Kegeologian dan Penyajian Data dan Informasi'],
            ['kode' => '500.10.5.1', 'keterangan' => 'Peta potensi dan sebaran'],
            ['kode' => '500.10.5.2', 'keterangan' => 'Air Tanah dan Geologi Tata Lingkungan'],
            ['kode' => '500.10.5.3', 'keterangan' => 'Mitigasi Bencana Gunungapi, Gerakan Tanah, Gempa Bumi dan Tsunami, Semburan Lumpur/Gas serta kebakaran Batubara'],
            ['kode' => '500.10.5.4', 'keterangan' => 'Survei Geologi'],
            ['kode' => '500.10.6', 'keterangan' => 'Pembinaan Program Minyak dan Gas Bumi'],
            ['kode' => '500.10.6.1', 'keterangan' => 'Rencana Induk Jaringan Gas Bumi'],
            ['kode' => '500.10.6.2', 'keterangan' => 'Rencana dan Realisasi Investasi'],
            ['kode' => '500.10.6.3', 'keterangan' => 'Penetapan Harga Minyak Mentah'],
            ['kode' => '500.10.6.4', 'keterangan' => 'Penetapan Bagii Hasil Penerimaan Negara Bukan Pajak (PNBP) Minyak dan Gas Bumi'],
            ['kode' => '500.10.6.5', 'keterangan' => 'Pelaksanaan Pemeriksaan dan Pengujian PNBP'],
            ['kode' => '500.10.6.6', 'keterangan' => 'Verifikasi Tingkat Komponen Dalam Negeri (TKDN)'],
            ['kode' => '500.10.6.7', 'keterangan' => 'Rekomendasi Kemampuan Produksi Barang dan Jasa Dalam Negeri'],
            ['kode' => '500.10.6.8', 'keterangan' => 'Rencana Kebutuhan Impor Barang (RKIB) dan Rencana Impor Barang (RIB)'],
            ['kode' => '500.10.7', 'keterangan' => 'Pembinaan Usaha Hulu Minyak dan Gas Bumi'],
            ['kode' => '500.10.7.1', 'keterangan' => 'Penyiapan dan Penawaran Wilayah Kerja (WK) Minyak dan Gas Bumi (Konvensional dan Non Konvensional)'],
            ['kode' => '500.10.7.2', 'keterangan' => 'Eksplorasi Minyak dan Gas Bumi (antara lain: Pemanfaatan Data Migas untuk presentasi makalah, publikasi makalah, pembukaan data, Izin Pengiriman Data ke Luar Negeri, Unitisasi Lapangan Minyak dan Gas Bumi, Rekomendasi Pengalihan Interest, Rekomendasi Penyisihan Wilayah Kerja Minyak dan Gas Bumi, Penyiapan Dokumen Pengakhiran Kontrak, Laporan Data Survei Seismik, Laporan Data Pemboran Sumur Eksplorasi per semester, Laporan Data Pemboran Sumur Eksplorasi Tahunan)'],
            ['kode' => '500.10.7.3', 'keterangan' => 'Eksploitasi Minyak dan Gas Bumi (antara lain: Rekomendasi Penggunaan Data Eksploitasi (publikasi makalah, analisa laboratorium, Reprocessing), Penetapan Pengusahaan Minyak Bumi dari Sumur Tua, Penetapan Pengusahaan Lapangan Produksi yang Dikembalikan Kepada Pemerintah, Buku Cadangan Minyak dan Gas Bumi, Data Cadangan Strategis/Penyangga Minyak dan Gas Bumi, Laporan Hasil Pemantauan Data Produksi Minyak dan Gas Bumi, Laporan Hasil Inventarisasi Mutu Minyak dan Gas Bumi)'],
            ['kode' => '500.10.7.4', 'keterangan' => 'Pengembangan lapangan Minyak dan Gas Bumi (POD)'],
            ['kode' => '500.10.7.5', 'keterangan' => 'Perpanjangan Kontrak KKS'],
            ['kode' => '500.10.7.6', 'keterangan' => 'Penetapan Alokasi dan Harga Gas'],
            ['kode' => '500.10.7.7', 'keterangan' => 'Partisipasi Interest'],
            ['kode' => '500.10.7.8', 'keterangan' => 'Tumpang Tindih Lahan'],
            ['kode' => '500.10.8', 'keterangan' => 'Pembinaan Usaha Hilir Minyak dan Gas Bumi'],
            ['kode' => '500.10.8.1', 'keterangan' => 'Perumusan pedoman, prosedur, layanan serta pengawasan Usaha Pengolahan, Pengangkutan, Penyimpanan, dan Niaga Minyak Bumi dan Gas Bumi, Hasil Olahan dan Bahan Bakar Lain, Antara lain: Pedoman dan Prosedur, Layanan Usaha (Izin/rekomendasi/penandasahan), Pengawasan'],
            ['kode' => '500.10.8.2', 'keterangan' => 'Fasilitasi dan pertimbangan pelanggaran'],
            ['kode' => '500.10.8.3', 'keterangan' => 'Penetapan Harga dan Subsidi Bahan Bakar yang ditetapkan dengan Keputusan Menteri'],
            ['kode' => '500.10.9', 'keterangan' => 'Teknik dan Lingkungan'],
            ['kode' => '500.10.9.1', 'keterangan' => 'Perumusan pelaksanaan dan pengawasan Standar Nasional Indonesia (SNI) / Standar Kompetensi Kerja Nasional Indonesia (SKKNI)'],
            ['kode' => '500.10.9.2', 'keterangan' => 'Registrasi Nomor Pelumas Terdaftar (NPT), Antara lain: Berkas permohonan, Berita Acara Hasil Evaluasi, Salinan Sertifikat NPT, Register NPT'],
            ['kode' => '500.10.9.3', 'keterangan' => 'Buku Register Welding Procedure Specification (WPS)/ Procedure Qualification Record (PQR)'],
            ['kode' => '500.10.9.4', 'keterangan' => 'Register dan Sertifikat Kualifikasi Juru Las'],
            ['kode' => '500.10.9.5', 'keterangan' => 'Keselamatan Hulu Minyak dan Gas Bumi, Antara lain: Pemeriksaan Teknis dan Pengujian Instalasi dan Peralatan, Pemeriksaan Kalibrasi Teknis, Pengawasan Keselamatan Operasi'],
            ['kode' => '500.10.9.6', 'keterangan' => 'Keselamatan Hilir Minyak dan Gas Bumi, Antara lain: Pemeriksaan Teknis dan Pengujian Instalasi dan Peralatan, Pemeriksaan Kalibrasi Teknis, Pengawasan Keselamatan Operasi'],
            ['kode' => '500.10.9.7', 'keterangan' => 'Keselamatan Kerja dan Lindungan Lingkungan'],
            ['kode' => '500.10.9.8', 'keterangan' => 'Dokumen Persetujuan Penunjukkan Kepala/Wakil Kepala Teknik Tambang Hulu dan Hilir, Antara lain: Dokumen Permohonan Pengajuan persetujuan penunjukkan Calon kepala/wakil kepala teknik tambang minyak dan gas bumi, Surat Undangan Presentasi, Makalah Presentasi, Surat Persetujuan/ Pengesahan penunjukan kepala/wakil Kepala Teknik Tambang Minyak dan Gas Bumi'],
            ['kode' => '500.10.9.9', 'keterangan' => 'Penghargaan Keselamatan Kerja, Antara lain: urat Permohonan Mendapatkan Penghargaan, Surat Penugasan Dalam Rangka Verifikasi, Berkas Hasil Evaluasi Verifikasi, Salinan Tanda Penghargaan, Dokumen Pengajuan dan penilaian Tanda Penghargaan Keselamatan Minyak dan Gas Bumi'],
            ['kode' => '500.10.9.10', 'keterangan' => 'Usaha penunjang'],
            ['kode' => '500.10.10', 'keterangan' => 'Infrastruktur Minyak dan Gas Bumi'],
            ['kode' => '500.10.10.1', 'keterangan' => 'Perencanaan Program Kerja Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['kode' => '500.10.10.2', 'keterangan' => 'Pengadaan Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['kode' => '500.10.10.3', 'keterangan' => 'Pelaksanaan Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['kode' => '500.10.10.4', 'keterangan' => 'Pengawasan dan Evaluasi Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['kode' => '500.10.11', 'keterangan' => 'Penyiapan Program Energi Terbarukan dan Konservasi Energi'],
            ['kode' => '500.10.11.1', 'keterangan' => 'Usulan Wilayah Kerja Panas Bumi'],
            ['kode' => '500.10.11.2', 'keterangan' => 'Usul Program Aneka Energi Pemerintah Daerah dan Lembaga'],
            ['kode' => '500.10.11.3', 'keterangan' => 'Penyiapan Program Pemanfaatan Energi'],
            ['kode' => '500.10.11.4', 'keterangan' => 'Proyeksi Kebutuhan Energi dari EBT'],
            ['kode' => '500.10.11.5', 'keterangan' => 'Perencanaan Pemanfaatan Energi dari EBT'],
            ['kode' => '500.10.11.6', 'keterangan' => 'Penyusunan Neraca Energi'],
            ['kode' => '500.10.11.7', 'keterangan' => 'Road Map di Bidang EBT'],
            ['kode' => '500.10.12', 'keterangan' => 'Panas Bumi'],
            ['kode' => '500.10.12.1', 'keterangan' => 'Penerbitan Surat Keterangan Terdaftar (SKT)'],
            ['kode' => '500.10.12.2', 'keterangan' => 'Sertifikasi Kelayakan Penggunaan Instalasi (SKPI)'],
            ['kode' => '500.10.12.3', 'keterangan' => 'Sertifikasi Kelayakan Penggunaan Peralatan'],
            ['kode' => '500.10.12.4', 'keterangan' => 'Rekomendasi Bahan Peledak'],
            ['kode' => '500.10.12.5', 'keterangan' => 'Perizinan penggunaan gudang bahan peledak'],
            ['kode' => '500.10.12.6', 'keterangan' => 'Izin Tangki Bahan Bakar Cair'],
            ['kode' => '500.10.12.7', 'keterangan' => 'Persetujuan sertifikasi Welding Prosedure Specifikation (WPS) dan Prosedure Qualification Record (PQR) dan kualifikasi Juru LasQualification Record (PQR) dan kualifikasi Juru Las'],
            ['kode' => '500.10.12.8', 'keterangan' => 'Penerbitasn Izin Usaha Panas Bumi (IUP)'],
            ['kode' => '500.10.12.9', 'keterangan' => 'Penerbitan Izin Panas Bumi (IPB)'],
            ['kode' => '500.10.12.10', 'keterangan' => 'Penerbitan Izin Pemanfaatan Langsung (IPL)'],
            ['kode' => '500.10.12.11', 'keterangan' => 'Penetapan kapasitas usaha panas bumi'],
            ['kode' => '500.10.12.12', 'keterangan' => 'Penetapan kapasitas Pembangkit Listrik Tenaga Panas Bumi (PLTP)'],
            ['kode' => '500.10.12.13', 'keterangan' => 'Pengawasan Eksplorasi dan Eksploitasi Panas Bumi'],
            ['kode' => '500.10.12.14', 'keterangan' => 'Pelaksanaaan Kerja Sama Panas Bumi'],
            ['kode' => '500.10.12.15', 'keterangan' => 'Inventarisasi, Verifikasi dan Evaluasi Obvitnas Bidang Panas Bumi'],
            ['kode' => '500.10.12.16', 'keterangan' => 'Monitoring Pelaksanaan Program Pengembangan dan Pemberdayaan Masyarakat (PPM) pada Kegiatan Pengusahaan Panas Bumi'],
            ['kode' => '500.10.12.17', 'keterangan' => 'Pembinaan dan Pengawasan Investasi Panas Bumi'],
            ['kode' => '500.10.13', 'keterangan' => 'Bioenergi'],
            ['kode' => '500.10.13.1', 'keterangan' => 'Penerbitan Izin Usaha Niaga Bahan Bakar Nabati (BNN)'],
            ['kode' => '500.10.13.2', 'keterangan' => 'Pengadaan Bahan Bakar Nabati (BBN)'],
            ['kode' => '500.10.13.3', 'keterangan' => 'Penerbitan Rekomendasi Ekspor - Impor'],
            ['kode' => '500.10.13.4', 'keterangan' => 'Penetapan Indeks Harga Pasar BBN (HIP BBN)'],
            ['kode' => '500.10.13.5', 'keterangan' => 'Evaluasi/Revisi HIP BBN'],
            ['kode' => '500.10.13.6', 'keterangan' => 'Database Pengusahaan Bioenergi'],
            ['kode' => '500.10.13.7', 'keterangan' => 'Penetapan Badan Usaha sebagai Pengelola Energi Biomassa atau Biogas untuk Pembangkit Listrik'],
            ['kode' => '500.10.13.8', 'keterangan' => 'Penetapan Spesifikasi Bahan Bakar Nabati'],
            ['kode' => '500.10.13.9', 'keterangan' => 'Usul Program Bioenergi Pemerintah Daerah dan Lembaga'],
            ['kode' => '500.10.14', 'keterangan' => 'Aneka Energi'],
            ['kode' => '500.10.14.1', 'keterangan' => 'Penerbitan Izin Usaha Aneka Energi'],
            ['kode' => '500.10.14.2', 'keterangan' => 'Penetapan Kapasitas Usaha'],
            ['kode' => '500.10.14.3', 'keterangan' => 'Rekomendasi Kompetensi dan Rencana Penggunaan Tenaga Kerja Asing'],
            ['kode' => '500.10.14.4', 'keterangan' => 'Rekomendasi Persetujuan Perubahan Pemegang Saham'],
            ['kode' => '500.10.14.5', 'keterangan' => 'Persetujuan Rencana Impor Barang (RIB)'],
            ['kode' => '500.10.15', 'keterangan' => 'Konservasi Energi'],
            ['kode' => '500.10.15.1', 'keterangan' => 'Audit Energi melalui program kemitraan Konservasi Energi'],
            ['kode' => '500.10.15.2', 'keterangan' => 'Monitoring Implementasi hasil audit energi melalui program kemitraan konservasi energi'],
            ['kode' => '500.10.15.3', 'keterangan' => 'Pembinaan dan pengawasan pelaksanaan manajemen energi di pengguna energi di atas 6.000 TOE'],
            ['kode' => '500.10.15.4', 'keterangan' => 'Pengawasan sertifikasi label dan tanda hemat energi pada lampu swabalast'],
            ['kode' => '500.10.15.5', 'keterangan' => 'Penyusunan daftar peralatan/teknologi efisiensi'],
            ['kode' => '500.10.15.6', 'keterangan' => 'Penyusunan emisi energi gas rumah kaca'],
            ['kode' => '500.10.15.7', 'keterangan' => 'Pemberian insentif dan disinsentif konservasi energi'],
            ['kode' => '500.10.15.8', 'keterangan' => 'Profil investasi efisiensi energi'],
            ['kode' => '500.10.15.9', 'keterangan' => 'Invesment Grade Audit (IGA)'],
            ['kode' => '500.10.15.10', 'keterangan' => 'Bimbingan Teknis Bidang EBTKE'],
            ['kode' => '500.10.16', 'keterangan' => 'Perencanaan dan Pembangunan Infrastruktur EBTKE'],
            ['kode' => '500.10.16.1', 'keterangan' => 'Usul Pembangunan Infrastruktur Pemerintah Daerah dan Lembaga'],
            ['kode' => '500.10.16.2', 'keterangan' => 'Perencanaan Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['kode' => '500.10.16.3', 'keterangan' => 'Pelaksanaan Pembangunan Infrastruktur Bidang EBTKE'],
            ['kode' => '500.10.16.4', 'keterangan' => 'Evaluasi Program Kerja'],
            ['kode' => '500.10.17', 'keterangan' => 'Bina Program Tenaga Listrik'],
            ['kode' => '500.10.17.1', 'keterangan' => 'Investasi dan pendanaan tenaga listrik, Antara lain: Dokumen grant/hibah/loan agreement luar negeri, Monitoring loan pembangunan infrastruktur penyediaan tenaga listrik, Laporan penanganan permasalahan infrastruktur penyediaan tenaga listrik, Laporan kegiatan investasi dan pendanaan tenaga listrik'],
            ['kode' => '500.10.17.2', 'keterangan' => 'Pengembangan listrik pedesaan, Antara lain: Data program listrik pedesaan, Data rasio elektrifikasi (RE) dan Rasio Desa Berlistrik (RD), Monitoring dan evaluasi listrik pedesaan, Listrik untuk masyarakat tidak mampu'],
            ['kode' => '500.10.17.3', 'keterangan' => 'Data dan Informasi Ketenagalistrikan'],
            ['kode' => '500.10.18', 'keterangan' => 'Bina Usaha Ketenagalistrikan'],
            ['kode' => '500.10.18.1', 'keterangan' => 'Penyiapan Usaha Ketenagalistrikan, Antara lain: Pelayanan izin usaha penyediaan tenaga listrik (IO, IUPL-S, dan IUPL), Bimbingan Usaha Ketenagalistrikan, Data laporan berkala pemegang Izin'],
            ['kode' => '500.10.18.2', 'keterangan' => 'Harga dan Subsidi Listrik'],
            ['kode' => '500.10.18.3', 'keterangan' => 'Hubungan komersial tenaga listrik'],
            ['kode' => '500.10.18.4', 'keterangan' => 'Perlindungan konsumen listrik, Antara lain: Penanganan pengaduan konsumen listrik, Dokumen Pengawasan tingkat mutu pelayanan tenaga listrik, Dokumen Evaluasi realisasi tingkat mutu pelayanan tenaga listrik, Dokumen evaluasi pemberian kompensasi pinalti tingkat mutu pelayanan PT PLN (Persero)'],
            ['kode' => '500.10.19', 'keterangan' => 'Teknik dan Lingkungan Ketenagalistrikan'],
            ['kode' => '500.10.19.1', 'keterangan' => 'Kelaikan teknik dan keselamatan ketenagalistrikan'],
            ['kode' => '500.10.19.2', 'keterangan' => 'Penyiapan kompetensi dan pengawasan tenaga teknik ketenagalistrikan'],
            ['kode' => '500.10.19.3', 'keterangan' => 'Usaha penunjang ketenagalistrikan, Antara lain: Dokumen Izin Usaha Jasa Penunjang Tenaga Listrik (IUJPTL), Dokumen Izin Pemanfaatan Jaringan Tenaga Listrik untuk Kepentingan Telematika (IPJ Telematika), Dokumen Penandasahan Rencana Impor Barang (RIB)'],
            ['kode' => '500.10.19.4', 'keterangan' => 'Perlindungan lingkungan ketenagalistrikan, Antara lain: Dokumen forum keselamatan instalasi pemanfaatan tenaga listrik, Dokumen pelaksanaan pengelolaan lingkungan hidup sektor ketenagalistrikan Laporan pembinaan dan pengawasan lingkungan, Dokumen perhitungan faktor emisi Clean Development Mechansim (CDM)'],
            ['kode' => '500.10.20', 'keterangan' => 'Sertifikasi'],
            ['kode' => '500.10.20.1', 'keterangan' => 'Dokumen Sertifikasi Produk peralatan dan pemanfaatan tenaga listrik'],
            ['kode' => '500.10.20.2', 'keterangan' => 'Dokumen Penunjukan Lembaga Sertifikasi Kompetensi (LSK)'],
            ['kode' => '500.10.20.3', 'keterangan' => 'Dokumen Penerbitan Sertifikasi Laik Operasi (SLO) Instalasi Tenaga Listrik'],
            ['kode' => '500.10.20.4', 'keterangan' => 'Dokumen Pembinaan dan pengawasan sertifikat laik operasi (SLO) instalasi tenaga listrik'],
            ['kode' => '500.10.20.5', 'keterangan' => 'Registrasi Sertifikasi'],
            ['kode' => '500.10.21', 'keterangan' => 'Akreditasi Ketenagalistrikan'],
            ['kode' => '500.10.22', 'keterangan' => 'Standarisasi Kompetensi'],
            ['kode' => '500.10.23', 'keterangan' => 'Standardisasi Nasional Indonesia (SNI) Bidang Ketenagalistrikan'],
            ['kode' => '500.10.23.1', 'keterangan' => 'Perumusan rancangan SNI bidang ketenagalistrikan'],
            ['kode' => '500.10.23.2', 'keterangan' => 'Forum konsensus rancangan SNI bidang ketenagalistrikan'],
            ['kode' => '500.10.23.3', 'keterangan' => 'Program pemberlakuan SNI wajib bidang ketenagalistrikan'],
            ['kode' => '500.10.23.4', 'keterangan' => 'Dokumen pengawasan penerapan SNI wajib bidang ketenagalistrikan'],
            ['kode' => '500.10.24', 'keterangan' => 'Standardisasi Usaha Penunjang Ketenagalistrikan'],
            ['kode' => '500.10.24.1', 'keterangan' => 'Klasifikasi usaha penunjang ketenagalistrikan'],
            ['kode' => '500.10.24.2', 'keterangan' => 'Kualifikasi usaha penunjang ketenagalistrikan'],
            ['kode' => '500.10.24.3', 'keterangan' => 'Dokumen penunjukan LIT (Lembaga Inspeksi Teknis)'],
            ['kode' => '500.10.24.4', 'keterangan' => 'Laporan berkala pemegang penunjukan LIT'],
            ['kode' => '500.10.24.5', 'keterangan' => 'Laporan hasil pengawasan penunjukan'],
            ['kode' => '500.10.25', 'keterangan' => 'Bina Program Mineral dan Batubara'],
            ['kode' => '500.10.25.1', 'keterangan' => 'Penyiapan dan Perencanaan Program Mineral dan Batubara'],
            ['kode' => '500.10.25.2', 'keterangan' => 'Rencana Induk Mineral dan Batubara'],
            ['kode' => '500.10.25.3', 'keterangan' => 'Pengembangan Investasi dan Kerja Sama Bidang Mineral dan Batubara'],
            ['kode' => '500.10.25.4', 'keterangan' => 'Data dan Informasi Mineral dan Batubara'],
            ['kode' => '500.10.25.5', 'keterangan' => 'Pelaporan Program Mineral dan Batubara'],
            ['kode' => '500.10.25.6', 'keterangan' => 'Perencanaan, Penyiapan dan Penawaran Wilayah Kerja (WK) Mineral dan Batubara melalui lelang reguler'],
            ['kode' => '500.10.25.7', 'keterangan' => 'Data dan Informasi Wilayah Mineral dan Batubara'],
            ['kode' => '500.10.25.8', 'keterangan' => 'Perencanaan Produksi Mineral dan Batubara'],
            ['kode' => '500.10.25.9', 'keterangan' => 'Pengembangan dan Pemanfaatan Mineral dan Batubara'],
            ['kode' => '500.10.26', 'keterangan' => 'Pembinaan Pengusahaan Mineral'],
            ['kode' => '500.10.26.1', 'keterangan' => 'Ketenagakerjaan'],
            ['kode' => '500.10.26.2', 'keterangan' => 'Pemberdayaan masyarakat sekitar tambang'],
            ['kode' => '500.10.26.3', 'keterangan' => 'Penyelesaian perselisihan usaha pertambangan mineral'],
            ['kode' => '500.10.26.4', 'keterangan' => 'Rekomendasi kegiatan usaha pertambangan mineral'],
            ['kode' => '500.10.26.5', 'keterangan' => 'Laporan/data kegiatan eksplorasi mineral'],
            ['kode' => '500.10.26.6', 'keterangan' => 'Pengawasan produksi dan pemasaran mineral (logam, bukan logam batuan, radioaktif, dan mineral jarang)'],
            ['kode' => '500.10.26.7', 'keterangan' => 'Perizinan usaha pertambangan mineral'],
            ['kode' => '500.10.26.8', 'keterangan' => 'Kontrak Karya (KK)'],
            ['kode' => '500.10.26.9', 'keterangan' => 'Pengelolaan barang Kontrak Karya (KK)'],
            ['kode' => '500.10.26.10', 'keterangan' => 'Persetujuan Obyek Vital Nasional (OBVITNAS)'],
            ['kode' => '500.10.26.11', 'keterangan' => 'Persetujuan perubahan saham direksi, komisaris, pada perusahaan mineral'],
            ['kode' => '500.10.26.12', 'keterangan' => 'Teguran kepada pengusahan Kontrak Karya (KK)'],
            ['kode' => '500.10.26.13', 'keterangan' => 'Tanggapan kepada pemerintah daerah terkait usaha pertambangan mineral'],
            ['kode' => '500.10.26.14', 'keterangan' => 'Pedoman/petunjuk teknis pertambangan mineral termasuk rancangan awal sampai dengan rancangan akhir'],
            ['kode' => '500.10.26.15', 'keterangan' => 'Pelaporan usaha pertambangan mineral'],
            ['kode' => '500.10.26.16', 'keterangan' => 'Penghargaan usaha pertambangan mineral'],
            ['kode' => '500.10.26.17', 'keterangan' => 'Penerbitan sertifikat clear and clean (CnC) Izin Usaha Pertambangan (IUP) Mineral'],
            ['kode' => '500.10.27', 'keterangan' => 'Pembinaan Pengusahaan Batubara'],
            ['kode' => '500.10.27.1', 'keterangan' => 'Ketenagakerjaan'],
            ['kode' => '500.10.27.2', 'keterangan' => 'Pemberdayaan masyarakat sekitar tambang'],
            ['kode' => '500.10.27.3', 'keterangan' => 'Penyelesaian perselisihan usaha pertambangan batubara'],
            ['kode' => '500.10.27.4', 'keterangan' => 'Rekomendasi kegiatan usaha pertambangan batubara'],
            ['kode' => '500.10.27.5', 'keterangan' => 'Laporan/data kegiatan eksplorasi batubara'],
            ['kode' => '500.10.27.6', 'keterangan' => 'Pengawasan produksi dan pemasaran batubara (bitumen padat, batuan aspal, batubara dan gambut), Antara lain: Laporan Produksi dan Penjualan Batubara PKP2B, IUP hingga Laporan Kontrak Penjualan Pertambangan Batubara'],
            ['kode' => '500.10.27.7', 'keterangan' => 'Perizinan Usaha Pertambangan Batubara'],
            ['kode' => '500.10.27.8', 'keterangan' => 'Perjanjian Karya Pengusahaan Batubara (PKP2B)'],
            ['kode' => '500.10.27.9', 'keterangan' => 'Pengelolaan Barang Perjanjian Karya Pengusahaan Batubara (PKP2B), Antara lain: Persetujuan Pengadaan Barang Modal (Masterlist)'],
            ['kode' => '500.10.27.10', 'keterangan' => 'Persetujuan Obyek Vital Nasional (OBVITNAS)'],
            ['kode' => '500.10.27.11', 'keterangan' => 'Persetujuan perubahan saham direksi, komisaris, pada perusahaan Perjanjian Karya Pengusahaan Batubara (PKP2B)'],
            ['kode' => '500.10.27.12', 'keterangan' => 'Teguran kepada pengusahan Perjanjian Karya Pengusahaan Batubara (PKP2B)'],
            ['kode' => '500.10.27.13', 'keterangan' => 'Tanggapan kepada pemerintah daerah terkait usaha pertambangan batubara'],
            ['kode' => '500.10.27.14', 'keterangan' => 'Pedoman/petunjuk teknis pertambangan mineral termasuk rancangan awal sampul dengan rancangan akhir'],
            ['kode' => '500.10.27.15', 'keterangan' => 'Pelaporan usaha pertambangan batubara'],
            ['kode' => '500.10.27.16', 'keterangan' => 'Penghargaan usaha pertambangan batubara'],
            ['kode' => '500.10.27.17', 'keterangan' => 'Penerbitan sertifikat clear and clean (CnC) Izin Usaha Pertambangan (IUP) Batubara'],
            ['kode' => '500.10.28', 'keterangan' => 'Penerimaan Negara'],
            ['kode' => '500.10.28.1', 'keterangan' => 'Penerimaan Negara Bukan Pajak'],
            ['kode' => '500.10.28.2', 'keterangan' => 'Penetapan Bagi Hasil Penerimaan Negara Bukan Pajak (PNBP)'],
            ['kode' => '500.10.28.3', 'keterangan' => 'Pelaksanaan Pemeriksaan dan Pengujian PNBP'],
            ['kode' => '500.10.29', 'keterangan' => 'Teknik dan Lingkungan Mineral dan Batubara'],
            ['kode' => '500.10.29.1', 'keterangan' => 'Perumusan RSNI (Rancangan Standar Nasional Indonesia)/ RSKKNI (Rancangan Standar Kompetensi Kerja Nasional Indonesia), Antara lain: Draft Rancangan, Rancangan Standar Nasional'],
            ['kode' => '500.10.29.2', 'keterangan' => 'Pengawasan Standardisasi'],
            ['kode' => '500.10.29.3', 'keterangan' => 'Persetujuan Penunjukkan Kepala/Wakil Kepala Teknik Tambang'],
            ['kode' => '500.10.29.4', 'keterangan' => 'Pengawasan Keselamatan Kegiatan dan Keselamatan Pekerja, Antara lain: Laporan Kecelakaan Tambang/Statistik hingga Laporan Hasil Pemeriksaan Keselamatan dan Kesehatan Kerja (K3)'],
            ['kode' => '500.10.29.5', 'keterangan' => 'Pemeriksaan teknis dan pengujian instalasi dan peralatan tambang, Antara lain: Pemeriksaan dan Pengujian Instalasi dan Peralatan'],
            ['kode' => '500.10.29.6', 'keterangan' => 'Analisis Mengenai Dampak Lingkungan (AMDAL)'],
            ['kode' => '500.10.29.7', 'keterangan' => 'Upaya Pengelolaan Lingkungan (UKL) dan Upaya Pemantauan Lingkungan (UPL)'],
            ['kode' => '500.10.29.8', 'keterangan' => 'Rekomendasi bahan kimia'],
            ['kode' => '500.10.29.9', 'keterangan' => 'Pengawasan Pelaksanaan Pengelolaan dan Pemantauan Lingkungan, Antara lain: Laporan Pelaksanaan Rencana Pengelolaan Lingkungan (RKL)/Rencana Pemantauan Lingkungan (RPL) hingga Surat Penetapan Jaminan Pasca Tambang'],
            ['kode' => '500.10.29.10', 'keterangan' => 'Laporan berkala teknik dan lingkungan pertambangan/ laporan tahunan, Antara lain: Laporan Bulanan Terjadinya Pencemaran (LPL-5) pelaksanaan reklamasi'],
            ['kode' => '500.10.29.11', 'keterangan' => 'Pemberian Penghargaan, Antara lain: Pemberian Penghargaan Lingkungan Pertambangan, Pemberian Penghargaan Keselamatan Kerja, Dokumen Pengajuan dan Penilaian Tanda Penghargaan lingkungan Pertambangan, Dokumen Pengajuan dan Penilaian Tanda Penghargaan Keselamatan'],
            ['kode' => '500.10.29.12', 'keterangan' => 'Pengawasan lingkungan pertambangan'],
            ['kode' => '500.10.29.13', 'keterangan' => 'Usaha Jasa Mineral dan Batubara'],
            ['kode' => '500.10.29.14', 'keterangan' => 'Pembinaan dan pengawasan usaha jasa mineral dan batubara'],
            ['kode' => '500.10.29.15', 'keterangan' => 'Rekomendasi Teknis, Antara lain: Pengajuan Rekomendasi Tekis, Hasil Evaluasi'],
            ['kode' => '500.10.29.16', 'keterangan' => 'Persetujuan Teknis, Antara lain: Pengajuan Persetujuan Teknis, Hasil Evaluasi'],
            ['kode' => '500.10.29.17', 'keterangan' => 'Pengawasan Teknis'],
            ['kode' => '500.10.29.18', 'keterangan' => 'Pengawasan Konservasi Mineral dan Batubara'],
            ['kode' => '500.10.29.19', 'keterangan' => 'Pembinaan Teknik dan Lingkungan Mineral dan Batubara, Antara lain: Sosialisasi Standardisasi, Bimbingan Teknis'],
            ['kode' => '500.10.30', 'keterangan' => 'Program Penelitian dan Pengembangan'],
            ['kode' => '500.10.30.1', 'keterangan' => 'Rencana Penelitian dan Pengembangan'],
            ['kode' => '500.10.30.2', 'keterangan' => 'Pengembangan dan inovasi'],
            ['kode' => '500.10.30.3', 'keterangan' => 'Dokumen penerapan/pemanfaatan/pendayagunaan/replikasi/prototipe hasil penelitian/pengkajian/pengembangan/inovasi'],
            ['kode' => '500.10.30.4', 'keterangan' => 'Advokasi dan fasilitasi penelitian, pengembangan dan inovasi'],
        ];

        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
