<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi500P3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode' => '500.10.30.5', 'keterangan' => 'Diseminasi hasil penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '500.10.30.6', 'keterangan' => 'Pembinaan penelitian/Pengembangan, pengkajian, dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '500.10.30.7', 'keterangan' => 'Jaringan Sistem Nasional Penelitian, Pengembangan dan Penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '500.10.30.8', 'keterangan' => 'Data dan informasi hasil penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '500.10.30.9', 'keterangan' => 'Master proceeding/ jurnal penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '500.10.30.10', 'keterangan' => 'Hak atas kekayaan intelektual (HaKI)'],
            ['kode' => '500.10.30.11', 'keterangan' => 'Forum komunikasi penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '500.10.30.12', 'keterangan' => 'Layanan jasa penelitian, pengembangan, penerapan IPTEK'],
            ['kode' => '500.10.30.13', 'keterangan' => 'Sertifikasi personil peneliti bidang Sumber Daya Mineral'],
            ['kode' => '500.10.31', 'keterangan' => 'Sarana Litbang'],
            ['kode' => '500.10.31.1', 'keterangan' => 'Administrasi penggunaan peralatan'],
            ['kode' => '500.10.31.2', 'keterangan' => 'Log-book Peralatan Survei/Peralatan Uji Kalibrasi'],
            ['kode' => '500.10.32', 'keterangan' => 'Afiliasi'],
            ['kode' => '500.10.32.1', 'keterangan' => 'Proyek Percontohan'],
            ['kode' => '500.10.32.2', 'keterangan' => 'Promosi dan Layanan Jasa Teknologi'],
            ['kode' => '500.10.32.3', 'keterangan' => 'Pembinaan Penelitian dan Pengembangan'],
            ['kode' => '500.10.32.4', 'keterangan' => 'Penyajian Informasi'],
            ['kode' => '500.10.33', 'keterangan' => 'Penelitian dan Pengembangan Kegeologian'],
            ['kode' => '500.10.33.1', 'keterangan' => 'Pemetaaan dan penelitian geologi, geokimia, dan geofisika kelautan'],
            ['kode' => '500.10.33.2', 'keterangan' => 'Energi Kelautan dan Kewilayahan Penelitian Energi dan kewilayahan pantai'],
            ['kode' => '500.10.33.3', 'keterangan' => 'Penelitian sumber daya energi dan mineral kelautan'],
            ['kode' => '500.10.33.4', 'keterangan' => 'Penelitian Sumber Daya Mineral Kelautan'],
            ['kode' => '500.10.34', 'keterangan' => 'Penelitian dan Pengembangan Teknologi Minyak dan Gas Bumi'],
            ['kode' => '500.10.34.1', 'keterangan' => 'Teknologi Eksplorasi'],
            ['kode' => '500.10.34.2', 'keterangan' => 'Teknologi Eksploitasi'],
            ['kode' => '500.10.34.3', 'keterangan' => 'Laboratorium'],
            ['kode' => '500.10.34.4', 'keterangan' => 'Study'],
            ['kode' => '500.10.34.5', 'keterangan' => 'Teknologi Proses'],
            ['kode' => '500.10.34.6', 'keterangan' => 'Teknologi Aplikasi Produk'],
            ['kode' => '500.10.34.7', 'keterangan' => 'Teknologi Gas'],
            ['kode' => '500.10.35', 'keterangan' => 'Penelitian dan Pengembangan Teknologi Mineral Batubara'],
            ['kode' => '500.10.35.1', 'keterangan' => 'Teknologi Eksploitasi Tambang dan Pengolahan Sumber Daya'],
            ['kode' => '500.10.35.2', 'keterangan' => 'Teknologi Pengolahan dan Pemanfaatan mineral'],
            ['kode' => '500.10.35.3', 'keterangan' => 'Teknologi Pemanfaatan Batubara'],
            ['kode' => '500.10.36', 'keterangan' => 'Penelitian dan Pengembangan Ketenagalistrikan dan Energi Baru Terbarukan'],
            ['kode' => '500.10.36.1', 'keterangan' => 'Energi baru terbarukan'],
            ['kode' => '500.10.36.2', 'keterangan' => 'Teknologi Ketenagalistrikan'],
            ['kode' => '500.10.36.3', 'keterangan' => 'Lingkungan dan Konservasi Energi'],
            ['kode' => '500.10.36.4', 'keterangan' => 'Penelitian dan Pengembangan Teknologi PLTSa (Pembangkit Listrik Tenaga Sampah) dan Konservasi Energi'],
            ['kode' => '500.11', 'keterangan' => 'PERHUBUNGAN'],
            ['kode' => '500.11.1', 'keterangan' => 'Kebijakan di bidang Perhubungan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.11.2', 'keterangan' => 'Jaringan Prasarana dan Pelayanan'],
            ['kode' => '500.11.2.1', 'keterangan' => 'Penentuan lokasi terminal barang tipe pengumpul dan tipe penunjang'],
            ['kode' => '500.11.2.2', 'keterangan' => 'Penentuan lokasi terminal penumpang tipe A, tipe B, dan tipe C'],
            ['kode' => '500.11.2.3', 'keterangan' => 'Penetapan lokasi terminal barang utama'],
            ['kode' => '500.11.2.4', 'keterangan' => 'Standar pelayanan minimal pengoperasian terminal'],
            ['kode' => '500.11.2.5', 'keterangan' => 'Jaringan trayek angkutan antar kota/provinsi'],
            ['kode' => '500.11.2.6', 'keterangan' => 'Jaringan lintas pada jaringan jalan primer'],
            ['kode' => '500.11.2.7', 'keterangan' => 'Penetapan kelas jalan primer'],
            ['kode' => '500.11.2.8', 'keterangan' => 'Kualifikasi teknis petugas terminal'],
            ['kode' => '500.11.2.9', 'keterangan' => 'Jaringan transportasi jalan sekunder'],
            ['kode' => '500.11.3', 'keterangan' => 'Pengembangan Transportasi Jalan'],
            ['kode' => '500.11.3.1', 'keterangan' => 'Sistem informasi dan komunikasi lalu lintas dan angkutan jalan'],
            ['kode' => '500.11.3.2', 'keterangan' => 'Pengembangan transportasi jalan'],
            ['kode' => '500.11.4', 'keterangan' => 'Pengujian Kendaraan Bermotor'],
            ['kode' => '500.11.4.1', 'keterangan' => 'Pengesahan hasil uji tipe kendaraan bermotor'],
            ['kode' => '500.11.4.2', 'keterangan' => 'Sertifikasi uji tipe kendaraan bermotor'],
            ['kode' => '500.11.4.3', 'keterangan' => 'Sertifikasi tenaga penguji kendaraan bermotor'],
            ['kode' => '500.11.4.4', 'keterangan' => 'Akreditasi unit pengujian kendaraan bermotor'],
            ['kode' => '500.11.5', 'keterangan' => 'Teknologi Kendaraan Bermotor'],
            ['kode' => '500.11.5.1', 'keterangan' => 'Sertifikasi rancang bangun dan rekayasa kendaraan bermotor'],
            ['kode' => '500.11.5.2', 'keterangan' => 'Pelaksanaan kalibrasi peralatan uji kendaraan bermotor'],
            ['kode' => '500.11.5.3', 'keterangan' => 'Persyaratan teknis dan laik jalan kendaraan bermotor'],
            ['kode' => '500.11.5.4', 'keterangan' => 'Harmonisasi dan standardisasi regulasi kendaraan bermotor'],
            ['kode' => '500.11.6', 'keterangan' => 'Manajemen dan Rekayasa Lalu Lintas'],
            ['kode' => '500.11.6.1', 'keterangan' => 'Analisa dampak lalu lintas jalan nasional di luar kawasan perkotaan'],
            ['kode' => '500.11.6.2', 'keterangan' => 'Manajemen dan rekayasa lalu lintas di jalan nasional'],
            ['kode' => '500.11.7', 'keterangan' => 'Perlengkapan Jalan'],
            ['kode' => '500.11.7.1', 'keterangan' => 'Pedoman teknis perlengkapan jalan'],
            ['kode' => '500.11.7.2', 'keterangan' => 'Penimbangan kendaraan bermotor di jalan'],
            ['kode' => '500.11.7.3', 'keterangan' => 'Akreditasi unit penimbangan kendaraan bermotor'],
            ['kode' => '500.11.7.4', 'keterangan' => 'Kualifikasi teknis petugas penimbangan kendaraan bermotor'],
            ['kode' => '500.11.7.5', 'keterangan' => 'Pengadaan, pemasangan, perbaikan, dan pemeliharaan perlengkapan jalan di jalan nasional'],
            ['kode' => '500.11.8', 'keterangan' => 'Angkutan Penumpang'],
            ['kode' => '500.11.8.1', 'keterangan' => 'Tarif angkutan penumpang kelas ekonomi'],
            ['kode' => '500.11.8.2', 'keterangan' => 'Izin trayek angkutan penumpang untuk trayek lintas batas negara'],
            ['kode' => '500.11.8.3', 'keterangan' => 'Izin trayek antar kota antar provinsi'],
            ['kode' => '500.11.8.4', 'keterangan' => 'Izin operasi angkutan pariwisata dan angkutan penumpang tidak dalam trayek yang wilayah pelayanannya bersifat lintas batas negara & antar kota/provinsi'],
            ['kode' => '500.11.8.5', 'keterangan' => 'Penilaian kinerja perusahaan angkutan umum'],
            ['kode' => '500.11.8.6', 'keterangan' => 'Pemberian subsidi angkutan umum'],
            ['kode' => '500.11.8.7', 'keterangan' => 'Angkutan perintis'],
            ['kode' => '500.11.8.8', 'keterangan' => 'Penghargaan perusahaan angkutan umum'],
            ['kode' => '500.11.9', 'keterangan' => 'Angkutan Barang'],
            ['kode' => '500.11.9.1', 'keterangan' => 'Sistem informasi dan komunikasi lalu lintas dan angkutan jalan'],
            ['kode' => '500.11.9.2', 'keterangan' => 'Tarif angkutan barang'],
            ['kode' => '500.11.9.3', 'keterangan' => 'Izin operasi angkutan barang tertentu'],
            ['kode' => '500.11.9.4', 'keterangan' => 'Pembinaan angkutan barang'],
            ['kode' => '500.11.9.5', 'keterangan' => 'Izin dispensasi angkutan jalan'],
            ['kode' => '500.11.10', 'keterangan' => 'Monitoring Operasional'],
            ['kode' => '500.11.10.1', 'keterangan' => 'Pengendalian operasional Lalu Lintas dan Angkutan Jalan'],
            ['kode' => '500.11.10.2', 'keterangan' => 'Pengawasan, penertiban dan pemberian sanksi administratif terhadap pelanggaran operasional kendaraan angkutan umum yang menjadi kewenangan'],
            ['kode' => '500.11.10.3', 'keterangan' => 'Berkas Pelanggaran Perda'],
            ['kode' => '500.11.11', 'keterangan' => 'Bimbingan Teknis Penyidik Pegawai Negeri Sipil'],
            ['kode' => '500.11.11.1', 'keterangan' => 'Pedoman Teknis'],
            ['kode' => '500.11.11.2', 'keterangan' => 'Penyidikan pelanggaran Lalu Lintas dan Angkutan Jalan oleh Penyidik Pegawai Negeri Sipil (PPNS)'],
            ['kode' => '500.11.11.3', 'keterangan' => 'Bimtek PPNS'],
            ['kode' => '500.11.11.4', 'keterangan' => 'Pengusulan pengangkatan dan pemberhentian Penyidik Pegawai Negeri Sipil (PPNS)'],
            ['kode' => '500.11.12', 'keterangan' => 'Analisa dan Evaluasi Jaringan Jaringan Transportasi Sungai, Danau dan Penyeberangan'],
            ['kode' => '500.11.12.1', 'keterangan' => 'Pendataan jaringan transportasi sungai, danau, dan penyeberangan'],
            ['kode' => '500.11.12.2', 'keterangan' => 'Analisis serta informasi jaringan transportasi sungai, danau, & penyeberangan'],
            ['kode' => '500.11.13', 'keterangan' => 'Pengembangan Jaringan Jaringan Transportasi Sungai, Danau dan Penyeberangan'],
            ['kode' => '500.11.13.1', 'keterangan' => 'Pengembangan dan penetapan jaringan transportasi sungai, danau dan penyeberangan (peta jaringan, blueprint jaringan)'],
            ['kode' => '500.11.13.2', 'keterangan' => 'Pengembangan Sistem Informasi Manajemen (SIM) lalu lintas dan angkutan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.14', 'keterangan' => 'Rancang Bangun Sarana Angkutan Sungai, Danau, dan Penyeberangan'],
            ['kode' => '500.11.15', 'keterangan' => 'Bimbingan Perawatan Sarana Angkutan Sungai, Danau, dan Penyeberangan'],
            ['kode' => '500.11.15.1', 'keterangan' => 'Perawatan dan pemeliharaan sarana sungai, danau dan penyeberangan'],
            ['kode' => '500.11.15.2', 'keterangan' => 'Pengawakan dan registrasi sarana angkutan sungai dan danau dan penyeberangan'],
            ['kode' => '500.11.16', 'keterangan' => 'Rancang Bangun Pelabuhan Sungai, Danau dan Penyeberangan'],
            ['kode' => '500.11.16.1', 'keterangan' => 'Perencanaan dan pembangunan pelabuhan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.16.2', 'keterangan' => 'Pemberian sertifikasi pelabuhan penyeberangan'],
            ['kode' => '500.11.16.3', 'keterangan' => 'Rekomendasi penetapan lokasi pelabuhan penyeberangan di lintas nasional dan internasional'],
            ['kode' => '500.11.16.4', 'keterangan' => 'Penyelenggaraan, pemeliharaan, perawatan dan perbaikan pelabuhan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.17', 'keterangan' => 'Kualifikasi teknis petugas pelabuhan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.18', 'keterangan' => 'Manajemen Lalu Lintas Sungai, Danau dan Penyeberangan'],
            ['kode' => '500.11.18.1', 'keterangan' => 'Manajemen lalu lintas'],
            ['kode' => '500.11.18.2', 'keterangan' => 'Tata cara berlalu lintas di sungai, danau dan penyeberangan'],
            ['kode' => '500.11.18.3', 'keterangan' => 'Penyidik Pegawai Negeri Sipil bidang lalu lintas dan angkutan sungai & danau'],
            ['kode' => '500.11.18.4', 'keterangan' => 'Sertifikasi inspektur sungai dan danau dan pejabat pemberangkatan angkutan sungai dan danau'],
            ['kode' => '500.11.19', 'keterangan' => 'Alur dan Perambuan Lalu Lintas Sungai, Danau dan Penyeberangan'],
            ['kode' => '500.11.19.1', 'keterangan' => 'Pengerukan alur pelayaran sungai, danau dan kolam pelabuhan penyeberangan'],
            ['kode' => '500.11.19.2', 'keterangan' => 'Penetapan kelas alur dan peta alur pelayaran sungai dan danau'],
            ['kode' => '500.11.19.3', 'keterangan' => 'Perambuan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.20', 'keterangan' => 'Bimbingan Usaha Angkutan Sungai, Danau dan Penyeberangan'],
            ['kode' => '500.11.20.1', 'keterangan' => 'Penyelenggaraan angkutan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.20.2', 'keterangan' => 'Persetujuan operasi kapal penyeberangan di lintas nasional dan internasional'],
            ['kode' => '500.11.21', 'keterangan' => 'Tarif dan Keperintisan'],
            ['kode' => '500.11.21.1', 'keterangan' => 'Perhitungan tarif, pemantauan tarif angkutan dan jasa pelabuhan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.21.2', 'keterangan' => 'Kriteria dan pelaksanaan pelayanan keperintisan'],
            ['kode' => '500.11.22', 'keterangan' => 'Bina Sistem Transportasi Perkotaan'],
            ['kode' => '500.11.22.1', 'keterangan' => 'Jaringan Transportasi Perkotaan'],
            ['kode' => '500.11.22.2', 'keterangan' => 'Transportasi perkotaan yang berbasis jalan, jalan rel dan perairan daratan'],
            ['kode' => '500.11.22.3', 'keterangan' => 'Transportasi perkotaan untuk kawasan perkotaan yang melebihi satu wilayah administrasi provinsi'],
            ['kode' => '500.11.23', 'keterangan' => 'Lalu Lintas Perkotaan'],
            ['kode' => '500.11.23.1', 'keterangan' => 'Manajemen dan rekayasa lalu lintas perkotaan'],
            ['kode' => '500.11.23.2', 'keterangan' => 'Manajemen dan rekayasa lalu lintas perkotaan di jalan nasional dalam kawasan perkotaan'],
            ['kode' => '500.11.23.3', 'keterangan' => 'Penanganan lalu lintas perkotaan berbasis teknologi di wilayah'],
            ['kode' => '500.11.24', 'keterangan' => 'Angkutan Perkotaan'],
            ['kode' => '500.11.24.1', 'keterangan' => 'Penyelenggaraan angkutan perkotaan dalam trayek'],
            ['kode' => '500.11.24.2', 'keterangan' => 'Jaringan trayek perkotaan'],
            ['kode' => '500.11.24.3', 'keterangan' => 'Penentuan dan pemenuhan alokasi kebutuhan angkutan perkotaan dalam trayek yang wilayah pelayanannya melebihi satu wilayah administrasi provinsi'],
            ['kode' => '500.11.25', 'keterangan' => 'Pengaduan Moda Transportasi Perkotaan'],
            ['kode' => '500.11.25.1', 'keterangan' => 'Penyelenggaraan angkutan perkotaan tidak dalam trayek untuk angkutan penumpang dan/atau barang'],
            ['kode' => '500.11.25.2', 'keterangan' => 'Pengaduan moda transportasi perkotaan yang menghubungkan antar simpul (bandara, pelabuhan, stasiun, dan terminal) di kawasan perkotaan yang melebihi satu wilayah administrasi provinsi'],
            ['kode' => '500.11.25.3', 'keterangan' => 'Penentuan dan pemenuhan alokasi kebutuhan angkutan perkotaan tidak dalam trayek yang wilayah pelayanannya melebihi satu wilayah administrasi provinsi'],
            ['kode' => '500.11.26', 'keterangan' => 'Dampak Transportasi Perkotaan'],
            ['kode' => '500.11.26.1', 'keterangan' => 'Penyelenggaraan transportasi perkotaan berwawasan lingkungan'],
            ['kode' => '500.11.26.2', 'keterangan' => 'Penanganan dampak transportasi di kawasan perkotaan'],
            ['kode' => '500.11.26.3', 'keterangan' => 'Masterplan pengembangan teknologi transportasi ramah lingkungan'],
            ['kode' => '500.11.26.4', 'keterangan' => 'Pelaksanaan analisis dampak lalu lintas di jalan nasional dalam kawasan kota'],
            ['kode' => '500.11.26.5', 'keterangan' => 'Rekomendasi hasil analisis dampak lalu lintas di jalan nasional dalam kawasan perkotaan'],
            ['kode' => '500.11.26.6', 'keterangan' => 'Masterplan transportasi perkotaan'],
            ['kode' => '500.11.27', 'keterangan' => 'Monitoring dan Evaluasi Manajemen Keselamatan'],
            ['kode' => '500.11.27.1', 'keterangan' => 'Monitoring dan evaluasi data kecelakaan'],
            ['kode' => '500.11.27.2', 'keterangan' => 'Kualifikasi unit pengkajian'],
            ['kode' => '500.11.27.3', 'keterangan' => 'Pengembangan sistem informasi manajemen keselamatan lalu lintas dan angkutan jalan, sungai, danau dan penyeberangan'],
            ['kode' => '500.11.28', 'keterangan' => 'Pengembangan Keselamatan'],
            ['kode' => '500.11.28.1', 'keterangan' => 'Program keselamatan lalu lintas dan angkutan jalan, sungai, danau, dan penyeberangan'],
            ['kode' => '500.11.28.2', 'keterangan' => 'Harmonisasi kebijakan'],
            ['kode' => '500.11.29', 'keterangan' => 'Promosi dan Kemitraan Keselamatan'],
            ['kode' => '500.11.29.1', 'keterangan' => 'Promosi Keselamatan: penyuluhan, publikasi dan destinasi keselamatan lalu lintas dan angkutan jalan, sungai, danau dan penyeberangan'],
            ['kode' => '500.11.29.2', 'keterangan' => 'Kemitraan keselamatan antar lembaga dan masyarakat di bidang keselamatan lalu lintas dan angkutan jalan, sungai, danau dan penyeberangan'],
            ['kode' => '500.11.30', 'keterangan' => 'Bina Keselamatan Angkutan Umum'],
            ['kode' => '500.11.30.1', 'keterangan' => 'Keselamatan Pengusahaan Angkutan Umum'],
            ['kode' => '500.11.30.2', 'keterangan' => 'Keselamatan Awak Angkutan Umum dan awak kapal sungai dan danau'],
            ['kode' => '500.11.31', 'keterangan' => 'Audit Keselamatan'],
            ['kode' => '500.11.31.1', 'keterangan' => 'Pedoman audit keselamatan sarana, prasarana, sumber daya manusia'],
            ['kode' => '500.11.31.2', 'keterangan' => 'Identifikasi daerah rawan kecelakaan jalan dan pelaku transportasi jalan dan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.31.3', 'keterangan' => 'Audit faktor keselamatan lalu lintas dan angkutan jalan, sungai, danau dan penyeberangan serta laik fungsi jalan'],
            ['kode' => '500.11.32', 'keterangan' => 'Inspeksi Keselamatan'],
            ['kode' => '500.11.32.1', 'keterangan' => 'Pedoman keselamatan'],
            ['kode' => '500.11.32.2', 'keterangan' => 'Inspeksi keselamatan sarana, prasarana, sumber daya manusia, dan pelaku transportasi jalan dan sungai, danau dan penyeberangan'],
            ['kode' => '500.11.32.3', 'keterangan' => 'Investigasi kecelakaan sungai, danau dan penyeberangan serta laik fungsi jalan'],
            ['kode' => '500.11.33', 'keterangan' => 'Parkir'],
            ['kode' => '500.11.33.1', 'keterangan' => 'Surat Tugas Juru Parkir'],
            ['kode' => '500.11.33.2', 'keterangan' => 'Izin tempat khusus parkir swasta'],
            ['kode' => '500.11.33.3', 'keterangan' => 'Surat Tugas TKP Pemerintah'],
            ['kode' => '500.12', 'keterangan' => 'KOMUNIKASI DAN INFORMATIKA'],
            ['kode' => '500.12.1', 'keterangan' => 'Kebijakan di bidang Komunikasi dan Informatika yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.12.2', 'keterangan' => 'Telekomunikasi'],
            ['kode' => '500.12.2.1', 'keterangan' => 'Layanan Jaringan Telekomunikasi'],
            ['kode' => '500.12.2.2', 'keterangan' => 'Layanan Jasa Telekomunikasi'],
            ['kode' => '500.12.2.3', 'keterangan' => 'Penomoran Telekomunikasi dan Informatika'],
            ['kode' => '500.12.2.4', 'keterangan' => 'Kelayakan Sistem Telekomunikasi'],
            ['kode' => '500.12.3', 'keterangan' => 'Penyiaran'],
            ['kode' => '500.12.3.1', 'keterangan' => 'Pemetaaan Penyelenggaraan Radio dan Televisi'],
            ['kode' => '500.12.3.2', 'keterangan' => 'Database Penyelenggaraan Radio dan Televisi'],
            ['kode' => '500.12.4', 'keterangan' => 'Telekomunikasi Khusus, Penyiaran Publik dan Kewajiban Universal'],
            ['kode' => '500.12.4.1', 'keterangan' => 'Telekomunikasi Khusus Pemerintah Daerah'],
            ['kode' => '500.12.4.2', 'keterangan' => 'Telekomunikasi Khusus Non Pemerintah Daerah'],
            ['kode' => '500.12.4.3', 'keterangan' => 'Layanan Khusus Penyiaran'],
            ['kode' => '500.12.4.4', 'keterangan' => 'Pelayanan Kewajiban Universal'],
            ['kode' => '500.12.4.5', 'keterangan' => 'Pengembangan Infrastruktur'],
            ['kode' => '500.12.5', 'keterangan' => 'Pengendalian Informatika'],
            ['kode' => '500.12.5.1', 'keterangan' => 'Monitoring dan Evaluasi Jaringan Telekomunikasi'],
            ['kode' => '500.12.5.2', 'keterangan' => 'Monitoring dan Evaluasi Jasa Telekomunikasi'],
            ['kode' => '500.12.5.3', 'keterangan' => 'Monitoring dan Evaluasi Penyiaran'],
            ['kode' => '500.12.5.4', 'keterangan' => 'Pencegahan dan Penertiban'],
            ['kode' => '500.12.6', 'keterangan' => 'e-Government'],
            ['kode' => '500.12.6.1', 'keterangan' => 'Tata Kelola e-Government'],
            ['kode' => '500.12.6.2', 'keterangan' => 'Teknologi dan Infrastruktur e-Government'],
            ['kode' => '500.12.6.3', 'keterangan' => 'Interoperabilitas dan Interkonektivitas e-Government'],
            ['kode' => '500.12.6.4', 'keterangan' => 'Aplikasi Layanan Kepemerintahan'],
            ['kode' => '500.12.6.5', 'keterangan' => 'Aplikasi Layanan Publik'],
            ['kode' => '500.12.7', 'keterangan' => 'e-Business'],
            ['kode' => '500.12.7.1', 'keterangan' => 'Tata Kelola e-Business'],
            ['kode' => '500.12.7.2', 'keterangan' => 'Teknologi dan Infrastruktur e-Business'],
            ['kode' => '500.12.7.3', 'keterangan' => 'Interoperabilitas dan Interkonektivitas e-Business'],
            ['kode' => '500.12.7.4', 'keterangan' => 'Aplikasi Layanan e-Business'],
            ['kode' => '500.12.8', 'keterangan' => 'Pemberdayaan Informatika Masyarakat'],
            ['kode' => '500.12.8.1', 'keterangan' => 'Pemberdayaan Informatika Masyarakat Perkotaan'],
            ['kode' => '500.12.8.2', 'keterangan' => 'Pemberdayaan Informatika Masyarakat Pedesaan'],
            ['kode' => '500.12.9', 'keterangan' => 'Pemberdayaan Industri Informatika'],
            ['kode' => '500.12.9.1', 'keterangan' => 'Industri Infrastruktur dan Layanan Aplikasi Informatika'],
            ['kode' => '500.12.9.2', 'keterangan' => 'Industri Perangkat Informatika Pengguna'],
            ['kode' => '500.12.9.3', 'keterangan' => 'Industri Perangkat Lunak'],
            ['kode' => '500.12.9.4', 'keterangan' => 'Industri Konten Multimedia'],
            ['kode' => '500.12.10', 'keterangan' => 'Keamanan Informasi'],
            ['kode' => '500.12.10.1', 'keterangan' => 'Tata Kelola Keamanan Informasi'],
            ['kode' => '500.12.10.2', 'keterangan' => 'Teknologi Keamanan Informasi'],
            ['kode' => '500.12.10.3', 'keterangan' => 'Monitoring, Evaluasi dan Tanggap Darurat Keamanan Informasi'],
            ['kode' => '500.12.10.4', 'keterangan' => 'Penyidikan dan Penindakan'],
            ['kode' => '500.12.10.5', 'keterangan' => 'Budaya Keamanan Informasi'],
            ['kode' => '500.12.11', 'keterangan' => 'Komunikasi Publik'],
            ['kode' => '500.12.11.1', 'keterangan' => 'Tata Kelola Komunikasi Publik'],
            ['kode' => '500.12.11.2', 'keterangan' => 'Pengelolaan Opini Publik'],
            ['kode' => '500.12.11.3', 'keterangan' => 'Layanan Komunikasi Publik'],
            ['kode' => '500.12.12', 'keterangan' => 'Pengolahan dan Penyediaan Informasi'],
            ['kode' => '500.12.12.1', 'keterangan' => 'Informasi Politik, Hukum, dan Keamanan'],
            ['kode' => '500.12.12.2', 'keterangan' => 'Informasi Perekonomian'],
            ['kode' => '500.12.12.3', 'keterangan' => 'Informasi Kesejahteraan Rakyat'],
            ['kode' => '500.12.13', 'keterangan' => 'Pengelolaan Media Publik'],
            ['kode' => '500.12.13.1', 'keterangan' => 'Media Cetak'],
            ['kode' => '500.12.13.2', 'keterangan' => 'Media Online'],
            ['kode' => '500.12.13.3', 'keterangan' => 'Media Luar Ruang dan Audio Visual'],
            ['kode' => '500.12.14', 'keterangan' => 'Kemitraan Komunikasi'],
            ['kode' => '500.12.14.1', 'keterangan' => 'Kemitraan Pemerintah dan Lembaga Negara'],
            ['kode' => '500.12.14.2', 'keterangan' => 'Kemitraan Media dan Dunia Usaha'],
            ['kode' => '500.12.14.3', 'keterangan' => 'Kemitraan Organisasi Kemasyarakatan dan Profesi'],
            ['kode' => '500.12.15', 'keterangan' => 'Infrastruktur Informatika'],
            ['kode' => '500.12.15.1', 'keterangan' => 'Jaringan'],
            ['kode' => '500.12.15.2', 'keterangan' => 'Piranti Teknologi Informatika'],
            ['kode' => '500.12.15.3', 'keterangan' => 'Keamanan Informatika'],
            ['kode' => '500.12.16', 'keterangan' => 'Sistem dan Data'],
            ['kode' => '500.12.16.1', 'keterangan' => 'Portal dan Konten'],
            ['kode' => '500.12.16.2', 'keterangan' => 'Pengumpulan dan Pengolahan Data'],
            ['kode' => '500.12.16.3', 'keterangan' => 'Pengembangan Aplikasi'],
            ['kode' => '500.12.17', 'keterangan' => 'Pusat Kerjasama'],
            ['kode' => '500.12.17.1', 'keterangan' => 'Kerja Sama daerah'],
            ['kode' => '500.12.17.2', 'keterangan' => 'Kerja Sama Bilateral'],
            ['kode' => '500.12.18', 'keterangan' => 'Pusat Informasi dan Hubungan Masyarakat'],
            ['kode' => '500.12.18.1', 'keterangan' => 'Pelayanan Informasi'],
            ['kode' => '500.12.18.2', 'keterangan' => 'Hubungan Masyarakat'],
            ['kode' => '500.12.18.3', 'keterangan' => 'Bimbingan Teknis'],
            ['kode' => '500.12.19', 'keterangan' => 'Evaluasi'],
            ['kode' => '500.13', 'keterangan' => 'PARIWISATA DAN EKONOMI KREATIF'],
            ['kode' => '500.13.1', 'keterangan' => 'Kebijakan di bidang Pariwisata dan Ekonomi Kreatif yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.13.2', 'keterangan' => 'Pengembangan Destinasi Wisata'],
            ['kode' => '500.13.2.1', 'keterangan' => 'Perancangan Destinasi dan Investasi Pariwisata'],
            ['kode' => '500.13.2.2', 'keterangan' => 'Pengembangan Daya Tarik Wisata'],
            ['kode' => '500.13.2.3', 'keterangan' => 'Industri Pariwisata'],
            ['kode' => '500.13.2.4', 'keterangan' => 'Pemberdayaan Masyarakat Destinasi Pariwisata'],
            ['kode' => '500.13.2.5', 'keterangan' => 'Pengembangan Wisata Minat Khusus, Konvansi, Insentif, dan Event'],
            ['kode' => '500.13.3', 'keterangan' => 'Pemasaran Pariwisata'],
            ['kode' => '500.13.3.1', 'keterangan' => 'Pengembangan Pasar dan Informasi Pariwisata'],
            ['kode' => '500.13.3.2', 'keterangan' => 'Promosi Pariwisata Luar Negeri'],
            ['kode' => '500.13.3.3', 'keterangan' => 'Promosi Pariwisata Dalam Negeri'],
            ['kode' => '500.13.3.4', 'keterangan' => 'Pencitraan Indonesia'],
            ['kode' => '500.13.4', 'keterangan' => 'Ekonomi Kreatif Berbasis Seni dan Budaya'],
            ['kode' => '500.13.4.1', 'keterangan' => 'Pengembangan industri Perfilman'],
            ['kode' => '500.13.4.2', 'keterangan' => 'Pengembangan Seni Pertunjukan dan Industri Musik'],
            ['kode' => '500.13.4.3', 'keterangan' => 'Pengembangan Seni Rupa'],
            ['kode' => '500.13.5', 'keterangan' => 'Ekonomi Kreatif Berbasi Media, Desain, dan IPTEK'],
            ['kode' => '500.13.5.1', 'keterangan' => 'Pengembangan Ekonomi Kreatif Berbasis Media'],
            ['kode' => '500.13.5.2', 'keterangan' => 'Desain dan Arsitektur'],
            ['kode' => '500.13.5.3', 'keterangan' => 'Kerjasama dan Fasilitasi'],
            ['kode' => '500.13.6', 'keterangan' => 'Pengembangan Sumber Daya Pariwisata dan Ekonomi Kreatif'],
            ['kode' => '500.13.6.1', 'keterangan' => 'Penelitian dan Pengembangan Kebijakan Kepariwisataan'],
            ['kode' => '500.13.6.2', 'keterangan' => 'Penelitian dan Pengembangan Kebijakan Ekonomi Kreatif'],
            ['kode' => '500.13.6.3', 'keterangan' => 'Pengembangan SDM Kepariwisataan dan Ekonomi Kreatif'],
            ['kode' => '500.13.6.4', 'keterangan' => 'Kompetensi Kepariwisataan dan Ekonomi Kreatif'],
            ['kode' => '500.14', 'keterangan' => 'STATISTIK'],
            ['kode' => '500.14.1', 'keterangan' => 'Kebijakan di bidang Statistik yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.14.2', 'keterangan' => 'Sensus Penduduk, Pertanian, dan Ekonomi'],
            ['kode' => '500.14.2.1', 'keterangan' => 'Perencanaan'],
            ['kode' => '500.14.2.2', 'keterangan' => 'Persiapan, Antara lain: Penyusunan rancangan organisasi kegiatan sensus, Penyusunan Kuesioner, Penyusunan konsep dan definisi, Penyusunan metodologi (cakupan, organisasi, lapangan, ukuran statistik, prosedur), Penyusunan buku pedoman (pencacahan, pengawasan, pengolahan), Penyusunan peta wilayah kerja dan muatan peta wilayah, Penyusunan pedoman sosialisasi, Sosialisasi kegiatan kepada stakeholder dan sumber data (leaflet, poster, pertemuan), Pelaksanaan pertemuan koordinasi (intern dan ekstern), Pelaksanaan pelatihan instruktur (TOT), Pelaksanaan pelatihan petugas, Penyusunan program pengolahan (rule validasi, pemeriksaan data entri, tabulasi), Pelatihan petugas pengolahan, Perancangan tabel, Pelaksanaan Ujicoba'],
            ['kode' => '500.14.2.3', 'keterangan' => 'Pelaksanaan Lapangan'],
            ['kode' => '500.14.2.4', 'keterangan' => 'Pengolahan, Antara lain: Pengelolaan dokumen (penerimaan/ pengiriman, pengelompokkan/Batching), Pemeriksaan dokumen dan pengkodean (Editing/Coding), Perekaman data (entri, scanner), Tabulasi Data, Pemeriksaan tabulasi, Laporan konsistensi tabulasi'],
            ['kode' => '500.14.2.5', 'keterangan' => 'Analisis dan Penyajian Hasil Sensus'],
            ['kode' => '500.14.2.6', 'keterangan' => 'Diseminasi hasil sensus'],
            ['kode' => '500.14.3', 'keterangan' => 'Survei'],
            ['kode' => '500.14.3.1', 'keterangan' => 'Perencanaan'],
            ['kode' => '500.14.3.2', 'keterangan' => 'Persiapan'],
            ['kode' => '500.14.3.3', 'keterangan' => 'Pelaksanaan Lapangan, Antara lain: Pelaksanaan listing, Pemilihan sampel, Pengumpulan data, Pemeriksaan, Pengawasan Lapangan, Monitoring kualitas'],
            ['kode' => '500.14.3.4', 'keterangan' => 'Pengolahan, Antara lain: Pengelolaan dokumen (penerimaan/ pengiriman, pengelompokkan/ Batching), Pemeriksaan dokumen dan pengkodean (Editing/Coding), Perekaman data (entri, scanner), Tabulasi Data, Pemeriksaan tabulasi, Laporan konsistensi tabulasi'],
            ['kode' => '500.14.3.5', 'keterangan' => 'Analisis dan Penyajian Hasil Survei, Antara lain: Pembahasan angka hasil pengolahan, Penyusunan'],
            ['kode' => '500.14.3.6', 'keterangan' => 'Diseminasi hasil Survei'],
            ['kode' => '500.14.4', 'keterangan' => 'Konsolidasi Data Statistik'],
            ['kode' => '500.14.4.1', 'keterangan' => 'Kompilasi Data'],
            ['kode' => '500.14.4.2', 'keterangan' => 'Analisis data'],
            ['kode' => '500.14.4.3', 'keterangan' => 'Penyusunan Publikasi'],
            ['kode' => '500.14.5', 'keterangan' => 'Evaluasi dan Pelaporan Sensus, Survei, dan Konsolidasi Data Statistik'],
            ['kode' => '500.15', 'keterangan' => 'KETENAGAKERJAAN'],
            ['kode' => '500.15.1', 'keterangan' => 'Kebijakan di bidang Ketenagakerjaan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.15.2', 'keterangan' => 'Perencanaan Tenaga Kerja'],
            ['kode' => '500.15.2.1', 'keterangan' => 'Perencanaan Tenaga Kerja Perusahaan Pemerintah'],
            ['kode' => '500.15.2.2', 'keterangan' => 'Perencanaan Tenaga Kerja Perusahaan Swasta'],
            ['kode' => '500.15.3', 'keterangan' => 'Pengembangan Standarisasi Kompetensi'],
            ['kode' => '500.15.3.1', 'keterangan' => 'Penerapan Standar Kompetensi'],
            ['kode' => '500.15.3.2', 'keterangan' => 'Pengembangan Standarisasi Kompetensi'],
            ['kode' => '500.15.3.3', 'keterangan' => 'Pengembangan Program Pelatihan Ketenagakerjaan'],
            ['kode' => '500.15.3.4', 'keterangan' => 'Pengembangan Program Pelatihan Produktivitas dan Kewirausahaan'],
            ['kode' => '500.15.3.5', 'keterangan' => 'Pengembangan Program Pelatihan Ketransmigrasian'],
            ['kode' => '500.15.4', 'keterangan' => 'Bina Lembaga dan Sarana Pelatihan Kerja'],
            ['kode' => '500.15.4.1', 'keterangan' => 'Akreditasi dan Sistem Informasi Kelembagaan'],
            ['kode' => '500.15.4.2', 'keterangan' => 'Pengembangan Sarana dan Fasilitas Lembaga Pelatihan'],
            ['kode' => '500.15.4.3', 'keterangan' => 'Pengembangan Standar Mutu (PSM) Lembaga Pelatihan'],
            ['kode' => '500.15.4.4', 'keterangan' => 'Sistem Pendanaan dan Kerjasama Antar Lembaga'],
            ['kode' => '500.15.5', 'keterangan' => 'Bina Instruktur dan Tenaga Pelatihan'],
            ['kode' => '500.15.5.1', 'keterangan' => 'Instruktur dan PSM Lembaga Pelatihan Pemerintah'],
            ['kode' => '500.15.5.2', 'keterangan' => 'Instruktur Lembaga Pelatihan Swasta'],
            ['kode' => '500.15.5.3', 'keterangan' => 'Tenaga Pelatihan'],
            ['kode' => '500.15.5.4', 'keterangan' => 'Sistem Informasi Instruktur, PSM, dan Tenaga Pelatihan'],
            ['kode' => '500.15.6', 'keterangan' => 'Bina Pemagangan'],
            ['kode' => '500.15.6.1', 'keterangan' => 'Pemagangan Dalam Negeri'],
            ['kode' => '500.15.6.2', 'keterangan' => 'Pemagangan Luar Negeri'],
            ['kode' => '500.15.6.3', 'keterangan' => 'Perizinan dan Advokasi Pemagangan'],
            ['kode' => '500.15.6.4', 'keterangan' => 'Promosi dan Jenjang Pemagangan'],
            ['kode' => '500.15.7', 'keterangan' => 'Produktivitas dan Kewirausahaan'],
            ['kode' => '500.15.7.1', 'keterangan' => 'Pengembangan Promosi dan Kerjasama Produktivitas dan Kewirausahaan'],
            ['kode' => '500.15.7.2', 'keterangan' => 'Pengembangan Sistem dan Peningkatan Produktivitas'],
            ['kode' => '500.15.7.3', 'keterangan' => 'Pengembangan Pengukuran dan Kajian Produktivitas'],
            ['kode' => '500.15.7.4', 'keterangan' => 'Pengembangan Kewirausahaan'],
            ['kode' => '500.15.8', 'keterangan' => 'Pengembangan Pasar Kerja'],
            ['kode' => '500.15.8.1', 'keterangan' => 'Informasi Pasar Kerja'],
            ['kode' => '500.15.8.2', 'keterangan' => 'Analisis Pasar Kerja'],
            ['kode' => '500.15.8.3', 'keterangan' => 'Bursa Kerja'],
            ['kode' => '500.15.8.4', 'keterangan' => 'Analisis Jabatan'],
            ['kode' => '500.15.9', 'keterangan' => 'Penempatan Tenaga Kerja Dalam Negeri'],
            ['kode' => '500.15.9.1', 'keterangan' => 'Antar Kerja'],
            ['kode' => '500.15.9.2', 'keterangan' => 'Penempatan Tenaga Kerja Khusus'],
            ['kode' => '500.15.9.3', 'keterangan' => 'Penyuluhan dan Bimbingan Jabatan'],
            ['kode' => '500.15.9.4', 'keterangan' => 'Pemberdayaan Pengantar Kerja'],
            ['kode' => '500.15.10', 'keterangan' => 'Perluasan Kesempatan Kerja dan Pengembangan Tenaga Kerja Sektor Informal'],
            ['kode' => '500.15.10.1', 'keterangan' => 'Tenaga Kerja Mandiri dan Sektoral Informal'],
            ['kode' => '500.15.10.2', 'keterangan' => 'Pengembangan Padat Karya'],
            ['kode' => '500.15.10.3', 'keterangan' => 'Terapan Teknologi Tepat Guna'],
            ['kode' => '500.15.10.4', 'keterangan' => 'Pemberdayaan Pendampingan dan Kerjasama Antar Lembaga'],
            ['kode' => '500.15.11', 'keterangan' => 'Standardisasi Profesi'],
            ['kode' => '500.15.11.1', 'keterangan' => 'Sistem Informasi dan Registrasi'],
            ['kode' => '500.15.11.2', 'keterangan' => 'Pembakuan Akreditasi'],
            ['kode' => '500.15.12', 'keterangan' => 'Persyaratan Kerja, Kesejahteraan, dan Analisis Diskriminasi'],
            ['kode' => '500.15.12.1', 'keterangan' => 'Peraturan Perusahaan dan Perjanjian Kerjasama Bersama'],
            ['kode' => '500.15.12.2', 'keterangan' => 'Perjanjian Kerja'],
            ['kode' => '500.15.12.3', 'keterangan' => 'Kesejahteraan Pekerja'],
            ['kode' => '500.15.12.4', 'keterangan' => 'Analisis Diskriminasi Syarat Kerja'],
            ['kode' => '500.15.13', 'keterangan' => 'Kelembagaan dan Pemasyarakatan Hubungan Industrial'],
            ['kode' => '500.15.13.1', 'keterangan' => 'Organisasi Pekerja dan Pengusaha'],
            ['kode' => '500.15.13.2', 'keterangan' => 'Kelembagaan Hubungan Industrial'],
            ['kode' => '500.15.13.3', 'keterangan' => 'Pemasyarakatan Hubungan Industrial'],
            ['kode' => '500.15.14', 'keterangan' => 'Pengupahan dan Penyelesaian Perselisihan Hubungan Industrial'],
            ['kode' => '500.15.14.1', 'keterangan' => 'Pengupahan'],
            ['kode' => '500.15.14.2', 'keterangan' => 'Jaminan Sosial Tenaga Kerja Dalam Hubungan Kerja'],
            ['kode' => '500.15.15', 'keterangan' => 'Pencegahan dan Penyelesaian Pelestarian Hubungan Industrial'],
            ['kode' => '500.15.15.1', 'keterangan' => 'Pencegahan Perselisihan Hubungan Industrial'],
            ['kode' => '500.15.15.2', 'keterangan' => 'Penyelenggaraan Penyelesaian Perselisihan Hubungan Industrial'],
            ['kode' => '500.15.15.3', 'keterangan' => 'Pemberdayaan Kelembagaan dan Tenaga Penyelesaian Perselisihan Hubungan Industrial'],
            ['kode' => '500.15.16', 'keterangan' => 'Pengawasan Norma Kerja dan Jaminan Sosial Tenaga Kerja'],
            ['kode' => '500.15.16.1', 'keterangan' => 'Pengawasan Norma Kerja'],
            ['kode' => '500.15.16.2', 'keterangan' => 'Pengawasan Norma Hubungan Kerja dan Perlindungan Berserikat'],
            ['kode' => '500.15.16.3', 'keterangan' => 'Pengawasan Norma Penempatan dan Latihan Tenaga Kerja'],
            ['kode' => '500.15.17', 'keterangan' => 'Pengawasan Norma Kerja Perempuan dan Anak'],
            ['kode' => '500.15.17.1', 'keterangan' => 'Pengawasan Norma Kerja Perempuan'],
            ['kode' => '500.15.17.2', 'keterangan' => 'Pengawasan Norma Kerja Anak'],
            ['kode' => '500.15.17.3', 'keterangan' => 'Kerjasama Lintas Sektoral'],
            ['kode' => '500.15.17.4', 'keterangan' => 'Advokasi Tenaga Kerja Perempuan dan Anak'],
            ['kode' => '500.15.18', 'keterangan' => 'Pengawasan Norma Keselamatan dan Kesehatan Kerja'],
            ['kode' => '500.15.18.1', 'keterangan' => 'Pengawasan Norma Mekanik, Pesawat Uap dan Bejana Tekan'],
            ['kode' => '500.15.18.2', 'keterangan' => 'Pengawasan Norma Konstruksi Bangunan, Listrik dan Penanggulangan Kebakaran'],
            ['kode' => '500.15.18.3', 'keterangan' => 'Pengawasan Norma Kesehatan Kerja'],
            ['kode' => '500.15.18.4', 'keterangan' => 'Pengawasan Norma Lingkungan Kerja dan Bahan Berbahaya'],
            ['kode' => '500.15.18.5', 'keterangan' => 'Pengawasan Norma Kelembagaan, Keahlian dan Sistem Manajemen K3'],
            ['kode' => '500.15.19', 'keterangan' => 'Laporan Hasil Pengawasan Ketenagakerjaan'],
            ['kode' => '500.15.20', 'keterangan' => 'Bina Penegakan Hukum'],
            ['kode' => '500.15.20.1', 'keterangan' => 'Pemeriksaan Norma Ketenagakerjaan'],
            ['kode' => '500.15.20.2', 'keterangan' => 'Penyidikan Norma Ketenagakerjaan'],
            ['kode' => '500.15.20.3', 'keterangan' => 'Pengembangan Penyidik Pegawai Negeri Sipil'],
            ['kode' => '500.15.20.4', 'keterangan' => 'Kerjasama Penegakan Hukum'],
            ['kode' => '500.15.21', 'keterangan' => 'Pengkajian dan Bimbingan Teknis Pelayanan Keselamatan dan Kesehatan Kerja (K3)'],
            ['kode' => '500.15.21.1', 'keterangan' => 'Analisis dan Standardisasi bidang K3'],
            ['kode' => '500.15.21.2', 'keterangan' => 'Hasil kajian, perekayasaan dan penerapan teknologi dan alih teknologi K3'],
            ['kode' => '500.15.21.3', 'keterangan' => 'Bimbingan Teknis dan Evaluasi Pengkajian K3'],
            ['kode' => '500.15.21.4', 'keterangan' => 'Bimbingan Teknis dan Evaluasi Pelayanan K3'],
            ['kode' => '500.15.22', 'keterangan' => 'Pengembangan SDM dan Kompetensi K3'],
            ['kode' => '500.15.22.1', 'keterangan' => 'Program, Analisis dan Standardisasi Pengembangan SDM dan Kompetensi K3'],
            ['kode' => '500.15.22.2', 'keterangan' => 'Penyebarluasan Informasi Pengembangan SDM dan Kompetensi K3'],
            ['kode' => '500.15.22.3', 'keterangan' => 'Kerjasama Tingkat Nasional Bidang Pengembangan SDM dan Kompetensi K3'],
            ['kode' => '500.15.22.4', 'keterangan' => 'Kerjasama Tingkat Regional Bidang Pengembangan SDM dan Kompetensi K3'],
            ['kode' => '500.15.22.5', 'keterangan' => 'Kerjasama Tingkat Internasional Bidang Pengembangan SDM dan Kompetensi K3'],
            ['kode' => '500.15.22.6', 'keterangan' => 'Bimbingan Teknis dan Evaluasi Pengembangan SDM dan Kompetensi K3'],
            ['kode' => '500.16', 'keterangan' => 'PENANAMAN MODAL'],
            ['kode' => '500.16.1', 'keterangan' => 'Kebijakan di bidang Penanaman Modal yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.16.2', 'keterangan' => 'Perencanaan Penanaman Modal'],
            ['kode' => '500.16.2.1', 'keterangan' => 'Perencanaan Industri Agribisnis dan Sumber Daya Alam Lainnya'],
            ['kode' => '500.16.2.2', 'keterangan' => 'Perencanaan Industri Manufaktur'],
            ['kode' => '500.16.2.3', 'keterangan' => 'Perencanaan Jasa dan Kawasan'],
            ['kode' => '500.16.2.4', 'keterangan' => 'Perencanaan Infrastruktur'],
            ['kode' => '500.16.3', 'keterangan' => 'Pengembangan Iklim Penanaman Modal'],
            ['kode' => '500.16.3.1', 'keterangan' => 'Deregulasi Penanaman Modal'],
            ['kode' => '500.16.3.2', 'keterangan' => 'Pengembangan Potensi Daerah'],
            ['kode' => '500.16.3.3', 'keterangan' => 'Pemberdayaan Usaha'],
            ['kode' => '500.16.3.4', 'keterangan' => 'Pemberdayaan Usaha Pembinaan dan Penyuluhan'],
            ['kode' => '500.16.3.5', 'keterangan' => 'Pemberdayaan Usaha Kemitraan Usaha'],
            ['kode' => '500.16.3.6', 'keterangan' => 'Pemberdayaan Usaha Pelayanan Usaha'],
            ['kode' => '500.16.4', 'keterangan' => 'Promosi Penanaman Modal'],
            ['kode' => '500.16.4.1', 'keterangan' => 'Pengembangan Promosi'],
            ['kode' => '500.16.4.2', 'keterangan' => 'Analisis Strategi Promosi'],
            ['kode' => '500.16.4.3', 'keterangan' => 'Fasilitasi Promosi Luar Negeri'],
            ['kode' => '500.16.4.4', 'keterangan' => 'Promosi Sektoral'],
            ['kode' => '500.16.4.5', 'keterangan' => 'Fasilitasi Promosi Daerah'],
            ['kode' => '500.16.4.6', 'keterangan' => 'Pameran dan Sarana Promosi'],
            ['kode' => '500.16.5', 'keterangan' => 'Kerja Sama Penanaman Modal'],
            ['kode' => '500.16.5.1', 'keterangan' => 'Kerja Sama Bilateral dan Multilateral'],
            ['kode' => '500.16.5.2', 'keterangan' => 'Kerja Sama Regional'],
            ['kode' => '500.16.5.3', 'keterangan' => 'Kerja Sama Dunia Usaha Internasional'],
            ['kode' => '500.16.6', 'keterangan' => 'Pengendalian Pelaksanaan Penanaman Modal'],
            ['kode' => '500.16.6.1', 'keterangan' => 'Pemantauan Penanaman Modal'],
            ['kode' => '500.16.6.2', 'keterangan' => 'Data Realisasi Penanaman Modal'],
            ['kode' => '500.16.6.3', 'keterangan' => 'Bimbingan Sosialisasi Ketentuan Penanaman Modal'],
            ['kode' => '500.16.6.4', 'keterangan' => 'Fasilitasi Penyelesaian Masalah'],
            ['kode' => '500.16.6.5', 'keterangan' => 'Pengawasan Penanaman Modal'],
            ['kode' => '500.16.6.6', 'keterangan' => 'Pencabutan/Pembatalan Perizinan Penanaman Modal'],
            ['kode' => '500.16.7', 'keterangan' => 'Pelayanan Penanaman Modal'],
            ['kode' => '500.16.7.1', 'keterangan' => 'Pelayanan Aplikasi'],
            ['kode' => '500.16.7.2', 'keterangan' => 'Pelayanan Perijinan'],
            ['kode' => '500.16.7.3', 'keterangan' => 'Pelayanan Konsultasi Perijinan'],
            ['kode' => '500.16.7.4', 'keterangan' => 'Pelayanan Non Perijinan'],
            ['kode' => '500.16.7.5', 'keterangan' => 'Pelayanan Fasilitas'],
            ['kode' => '500.17', 'keterangan' => 'PERTANAHAN'],
            ['kode' => '500.17.1', 'keterangan' => 'Kebijakan di bidang Pertanahan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.17.2', 'keterangan' => 'Pengadaan dan Penataan Administrasi Pertanahan'],
            ['kode' => '500.17.2.1', 'keterangan' => 'Fasilitasi Pengadaan Tanah'],
            ['kode' => '500.17.2.2', 'keterangan' => 'Pembinaan dan Pengendalian Administrasi Pertanahan'],
            ['kode' => '500.17.2.3', 'keterangan' => 'Data dan Informasi Pertanahan'],
            ['kode' => '500.17.2.4', 'keterangan' => 'Advokasi dan Pengendalian'],
            ['kode' => '500.17.3', 'keterangan' => 'Penatagunaan dan Penguatan Hak Atas Tanah'],
            ['kode' => '500.17.3.1', 'keterangan' => 'Penatagunaan Tanah'],
            ['kode' => '500.17.3.2', 'keterangan' => 'Data dan Pemetaan Tematik'],
            ['kode' => '500.17.3.3', 'keterangan' => 'Penguatan Atas Tanah'],
            ['kode' => '500.17.4', 'keterangan' => 'Sengketa Tanah'],
            ['kode' => '500.17.4.1', 'keterangan' => 'Pengkajian dan Penanganan Sengketa'],
            ['kode' => '500.17.4.2', 'keterangan' => 'Advokasi dan Pengendalian'],
            ['kode' => '500.18', 'keterangan' => 'TRANSMIGRASI'],
            ['kode' => '500.18.1', 'keterangan' => 'Kebijakan di bidang Transmigrasi yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.18.2', 'keterangan' => 'Penyediaan Tanah Transmigrasi'],
            ['kode' => '500.18.2.1', 'keterangan' => 'Fasilitasi Pengadaan Tanah'],
            ['kode' => '500.18.2.2', 'keterangan' => 'Pengurusan Legalitas Tanah'],
            ['kode' => '500.18.2.3', 'keterangan' => 'Dokumentasi Pertanahan'],
            ['kode' => '500.18.2.4', 'keterangan' => 'Advokasi Pertanahan'],
            ['kode' => '500.18.3', 'keterangan' => 'Pembangunan Pemukiman dan Infrastruktur Kawasan Transmigrasi'],
            ['kode' => '500.18.3.1', 'keterangan' => 'Penyiapan Lahan'],
            ['kode' => '500.18.3.2', 'keterangan' => 'Penyiapan Sarana'],
            ['kode' => '500.18.3.3', 'keterangan' => 'Penyiapan Prasarana'],
            ['kode' => '500.18.3.4', 'keterangan' => 'Evaluasi Kelayakan Permukiman'],
            ['kode' => '500.18.4', 'keterangan' => 'Fasilitasi Penempatan Transmigrasi'],
            ['kode' => '500.18.4.1', 'keterangan' => 'Penyiapan Calon Transmigrasi'],
            ['kode' => '500.18.4.2', 'keterangan' => 'Penyiapan Perpindahan'],
            ['kode' => '500.18.4.3', 'keterangan' => 'Pelaksanaan Perpindahan'],
            ['kode' => '500.18.4.4', 'keterangan' => 'Penataan dan Adaptasi'],
            ['kode' => '500.18.5', 'keterangan' => 'Partisipasi Masyarakat'],
            ['kode' => '500.18.5.1', 'keterangan' => 'Promosi dan Motivasi'],
            ['kode' => '500.18.5.2', 'keterangan' => 'Kerjasama Kelembagaan'],
            ['kode' => '500.18.5.3', 'keterangan' => 'Kerjasama Antar Daerah'],
            ['kode' => '500.18.5.4', 'keterangan' => 'Pelayanan Investasi'],
            ['kode' => '500.18.6', 'keterangan' => 'Pembinaan Pengembangan Masyarakat dan Kawasan Transmigrasi'],
            ['kode' => '500.18.6.1', 'keterangan' => 'Perencanaan Teknis Pengembangan Masyarakat dan Kawasan'],
            ['kode' => '500.18.6.2', 'keterangan' => 'Bina Sistem Informasi'],
            ['kode' => '500.18.6.3', 'keterangan' => 'Perencanaan Pengembangan Kawasan'],
            ['kode' => '500.18.6.4', 'keterangan' => 'Perencanaan Pengembangan Masyarakat'],
            ['kode' => '500.18.6.5', 'keterangan' => 'Perencanaan Pengembangan Pusat Pertumbuhan'],
            ['kode' => '500.18.7', 'keterangan' => 'Peningkatan Kapasitas Sumber Daya Manusia dan Masyarakat'],
            ['kode' => '500.18.7.1', 'keterangan' => 'Bantuan Pangan dan Kesehatan'],
            ['kode' => '500.18.7.2', 'keterangan' => 'Fasilitas Sosial Budaya'],
            ['kode' => '500.18.7.3', 'keterangan' => 'Pengembangan Kelembagaan'],
            ['kode' => '500.18.7.4', 'keterangan' => 'Bina Pendampingan Masyarakat Transmigrasi'],
            ['kode' => '500.18.8', 'keterangan' => 'Pengembangan Usaha'],
            ['kode' => '500.18.8.1', 'keterangan' => 'Kewirausahaan'],
            ['kode' => '500.18.8.2', 'keterangan' => 'Produksi'],
            ['kode' => '500.18.8.3', 'keterangan' => 'Pengolahan Hasil dan Pemasaran'],
            ['kode' => '500.18.8.4', 'keterangan' => 'Lembaga Ekonomi dan permodalan'],
            ['kode' => '500.18.9', 'keterangan' => 'Pengembangan Sarana dan Prasarana Kawasan'],
            ['kode' => '500.18.9.1', 'keterangan' => 'Analisis dan Standarisasi Sarana dan Prasarana'],
            ['kode' => '500.18.9.2', 'keterangan' => 'Pengembangan Sarana'],
            ['kode' => '500.18.9.3', 'keterangan' => 'Pengembangan Prasarana'],
            ['kode' => '500.18.9.4', 'keterangan' => 'Evaluasi Pengembangan Sarana dan Prasarana'],
            ['kode' => '500.18.10', 'keterangan' => 'Penyerasian Lingkungan'],
            ['kode' => '500.18.10.1', 'keterangan' => 'Persiapan Pengelolaan dan Pemantauan Lingkungan'],
            ['kode' => '500.18.10.2', 'keterangan' => 'Adaptasi dan Mitigasi Lingkungan'],
            ['kode' => '500.18.10.3', 'keterangan' => 'Evaluasi Perkembangan Permukiman Transmigrasi'],
            ['kode' => '500.18.10.4', 'keterangan' => 'Evaluasi Perkembangan Pusat Pertumbuhan'],
        ];


        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
