<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi500Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode' => '500', 'keterangan' => 'PEREKONOMIAN'],
            ['kode' => '500.1', 'keterangan' => 'KETAHANAN PANGAN'],
            ['kode' => '500.1.1', 'keterangan' => 'Kebijakan di bidang Ketahanan Pangan yang dilakukan Pemerintah Daerah'],
            ['kode' => '500.1.2', 'keterangan' => 'Ketersediaan dan Kerawanan Pangan'],
            ['kode' => '500.1.2.1', 'keterangan' => 'Ketersediaan Pangan'],
            ['kode' => '500.1.2.2', 'keterangan' => 'Akses Pangan'],
            ['kode' => '500.1.2.3', 'keterangan' => 'Kerawanan Pangan'],
            ['kode' => '500.1.3', 'keterangan' => 'Distribusi dan Cadangan Pangan'],
            ['kode' => '500.1.3.1', 'keterangan' => 'Distribusi Pangan'],
            ['kode' => '500.1.3.2', 'keterangan' => 'Harga Pangan'],
            ['kode' => '500.1.3.3', 'keterangan' => 'Cadangan Pangan'],
            ['kode' => '500.1.4', 'keterangan' => 'Penganekaragaman Konsumsi dan Ketahanan Pangan'],
            ['kode' => '500.1.4.1', 'keterangan' => 'Konsumsi Pangan'],
            ['kode' => '500.1.4.2', 'keterangan' => 'Penganekaragaman Pangan'],
            ['kode' => '500.1.4.3', 'keterangan' => 'Keamanan Pangan Segar'],
            ['kode' => '500.1.5', 'keterangan' => 'Penguatan Kelembagaan Ketahanan Pangan'],
            ['kode' => '500.1.5.1', 'keterangan' => 'Dewan Ketahanan Pangan'],
            ['kode' => '500.1.5.2', 'keterangan' => 'Penghargaan Ketahanan Pangan'],
            ['kode' => '500.1.6', 'keterangan' => 'Swasembada Pangan (Kearifan Lokal)'],
            ['kode' => '500.1.7', 'keterangan' => 'Bimbingan Teknis'],
            ['kode' => '500.1.8', 'keterangan' => 'Evaluasi'],
            ['kode' => '500.2', 'keterangan' => 'PERDAGANGAN'],
            ['kode' => '500.2.1', 'keterangan' => 'Kebijakan di bidang Perdagangan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.2.2', 'keterangan' => 'Perdagangan Dalam Negeri'],
            ['kode' => '500.2.2.1', 'keterangan' => 'Bina Usaha Kelembagaan dan Penguatan Usaha'],
            ['kode' => '500.2.2.2', 'keterangan' => 'Bina Usaha Jasa Perdagangan'],
            ['kode' => '500.2.2.3', 'keterangan' => 'Bina Usaha Dagang Asing dan Keagenan'],
            ['kode' => '500.2.2.4', 'keterangan' => 'Informasi Perusahaan'],
            ['kode' => '500.2.2.5', 'keterangan' => 'Pelaku Pasar'],
            ['kode' => '500.2.2.6', 'keterangan' => 'Iklim Usaha dan Bimbingan Teknis Usaha Dagang Kecil Menengah'],
            ['kode' => '500.2.2.7', 'keterangan' => 'Fasilitasi Usaha dan Pemasaran Usaha Dagang Kecil Menengah'],
            ['kode' => '500.2.2.8', 'keterangan' => 'Pengembangan Produk Lokal'],
            ['kode' => '500.2.2.9', 'keterangan' => 'Pencitraan Produk Dalam Negeri'],
            ['kode' => '500.2.2.10', 'keterangan' => 'Pengembangan Sarana Distribusi'],
            ['kode' => '500.2.2.11', 'keterangan' => 'Pengelolaan Sarana Distribusi'],
            ['kode' => '500.2.2.12', 'keterangan' => 'Kerjasama Pengembangan Sistem Logistik'],
            ['kode' => '500.2.2.13', 'keterangan' => 'Informasi dan Bimbingan Teknis Penyedia Jasa Logistik'],
            ['kode' => '500.2.2.14', 'keterangan' => 'Informasi Pasar'],
            ['kode' => '500.2.2.15', 'keterangan' => 'Informasi Hasil Industri'],
            ['kode' => '500.2.2.16', 'keterangan' => 'Barang Strategis'],
            ['kode' => '500.2.2.17', 'keterangan' => 'Bahan Pokok Agro'],
            ['kode' => '500.2.3', 'keterangan' => 'Standarisasi dan Perlindungan Konsumen'],
            ['kode' => '500.2.3.1', 'keterangan' => 'Kelembagaan dan informasi standar'],
            ['kode' => '500.2.3.2', 'keterangan' => 'Kerjasama Standarisasi'],
            ['kode' => '500.2.3.3', 'keterangan' => 'Perumusan dan penerapan standar'],
            ['kode' => '500.2.3.4', 'keterangan' => 'Tata usaha'],
            ['kode' => '500.2.3.5', 'keterangan' => 'Kerjasama, informasi, dan publikasi'],
            ['kode' => '500.2.3.6', 'keterangan' => 'Analisa penyelenggaraan perlindungan konsumen'],
            ['kode' => '500.2.3.7', 'keterangan' => 'Bimbingan konsumen dan pelaku usaha'],
            ['kode' => '500.2.3.8', 'keterangan' => 'Fasilitas kelembagaan'],
            ['kode' => '500.2.3.9', 'keterangan' => 'Produk pertambangan dan aneka industri'],
            ['kode' => '500.2.3.10', 'keterangan' => 'Produk pertanian, kimia dan kehutanan'],
            ['kode' => '500.2.3.11', 'keterangan' => 'Jasa'],
            ['kode' => '500.2.3.12', 'keterangan' => 'Kerjasama'],
            ['kode' => '500.2.3.13', 'keterangan' => 'Sarana dan Kerjasama'],
            ['kode' => '500.2.3.14', 'keterangan' => 'Kelembagaan dan dan penilaian'],
            ['kode' => '500.2.3.15', 'keterangan' => 'UTTP dan Standar Ukuran'],
            ['kode' => '500.2.3.16', 'keterangan' => 'Pengawasan'],
            ['kode' => '500.2.3.17', 'keterangan' => 'Balai pengelolaan Standar Nasional Satuan Ukuran'],
            ['kode' => '500.2.3.18', 'keterangan' => 'Balai Pengujian UTTP'],
            ['kode' => '500.2.4', 'keterangan' => 'Perdagangan Berjangka Komoditi'],
            ['kode' => '500.2.4.1', 'keterangan' => 'Pengkajian pasar'],
            ['kode' => '500.2.4.2', 'keterangan' => 'Pengawasan Transaksi'],
            ['kode' => '500.2.4.3', 'keterangan' => 'Pengawasan Keuangan dan Audit'],
            ['kode' => '500.2.4.4', 'keterangan' => 'Pengkajian pasar'],
            ['kode' => '500.2.4.5', 'keterangan' => 'Pengembangan Pasar'],
            ['kode' => '500.2.4.6', 'keterangan' => 'Sistem informasi'],
            ['kode' => '500.2.4.7', 'keterangan' => 'Pembinaan pasar lelang dan sistem resi gudang'],
            ['kode' => '500.2.4.8', 'keterangan' => 'Pengawasan pasar lelang'],
            ['kode' => '500.2.4.9', 'keterangan' => 'Pengawasan sistem gudang'],
            ['kode' => '500.2.5', 'keterangan' => 'Bimbingan Teknis'],
            ['kode' => '500.2.6', 'keterangan' => 'Evaluasi'],
            ['kode' => '500.3', 'keterangan' => 'KOPERASI DAN USAHA KECIL MENENGAH'],
            ['kode' => '500.3.1', 'keterangan' => 'Kebijakan di bidang Koperasi dan Usaha Kecil Menengah yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.3.2', 'keterangan' => 'Kelembagaan Koperasi dan UKM'],
            ['kode' => '500.3.2.1', 'keterangan' => 'Organisasi dan Badan Hukum Koperasi'],
            ['kode' => '500.3.2.2', 'keterangan' => 'Tata Laksana Koperasi dan UKM'],
            ['kode' => '500.3.2.3', 'keterangan' => 'Keanggotaan Koperasi'],
            ['kode' => '500.3.2.4', 'keterangan' => 'Pengendalian dan Akuntabilitas'],
            ['kode' => '500.3.3', 'keterangan' => 'Produksi'],
            ['kode' => '500.3.3.1', 'keterangan' => 'Pertanian Tanaman Pangan dan Hortikultura'],
            ['kode' => '500.3.3.2', 'keterangan' => 'Kehutanan dan Perkebunan'],
            ['kode' => '500.3.3.3', 'keterangan' => 'Perikanan dan Peternakan'],
            ['kode' => '500.3.3.4', 'keterangan' => 'Industri Kerajinan dan Pertambangan'],
            ['kode' => '500.3.3.5', 'keterangan' => 'Ketenagalistrikan dan Aneka Usaha'],
            ['kode' => '500.3.4', 'keterangan' => 'Pembiayaan'],
            ['kode' => '500.3.4.1', 'keterangan' => 'Program Pendanaan'],
            ['kode' => '500.3.4.2', 'keterangan' => 'Pengembangan dan Pengendalian Simpan Pinjam'],
            ['kode' => '500.3.4.3', 'keterangan' => 'Urusan Permodalan'],
            ['kode' => '500.3.4.4', 'keterangan' => 'Asuransi dan Jasa Keuangan'],
            ['kode' => '500.3.4.5', 'keterangan' => 'Pembiayaan dan Penjaminan Kredit'],
            ['kode' => '500.3.4.6', 'keterangan' => 'Lembaga Pengelola Dana Bergulir KUKM (LPDB)'],
            ['kode' => '500.3.5', 'keterangan' => 'Pemasaran dan Jaringan Usaha'],
            ['kode' => '500.3.5.1', 'keterangan' => 'Perdagangan Dalam Negeri'],
            ['kode' => '500.3.5.2', 'keterangan' => 'Ekspor dan Impor'],
            ['kode' => '500.3.5.3', 'keterangan' => 'Sarana dan Prasarana Pemasaran'],
            ['kode' => '500.3.5.4', 'keterangan' => 'Kemitraan dan Jaringan Usaha'],
            ['kode' => '500.3.5.5', 'keterangan' => 'Informasi dan Publikasi Bisnis'],
            ['kode' => '500.3.5.6', 'keterangan' => 'Lembaga Layanan Pemasaran LLP Koperasi dan UKM'],
            ['kode' => '500.3.6', 'keterangan' => 'Pengembangan Sumber Daya Manusia'],
            ['kode' => '500.3.6.1', 'keterangan' => 'Pengembangan Kewirausahaan'],
            ['kode' => '500.3.6.2', 'keterangan' => 'Kebijakan Pendidikan Koperasi dan UKM'],
            ['kode' => '500.3.6.3', 'keterangan' => 'Peran Serta Masyarakat'],
            ['kode' => '500.3.6.4', 'keterangan' => 'Monitoring dan Evaluasi Diklat Koperasi dan UKM'],
            ['kode' => '500.3.6.5', 'keterangan' => 'Advokasi'],
            ['kode' => '500.3.7', 'keterangan' => 'Pengembangan dan Restrukturisasi Usaha'],
            ['kode' => '500.3.7.1', 'keterangan' => 'Produktifitas dan Mutu'],
            ['kode' => '500.3.7.2', 'keterangan' => 'Restrukturisasi Usaha'],
            ['kode' => '500.3.7.3', 'keterangan' => 'Pemberdayaan Lembaga Pengembangan Bisnis (LPB)'],
            ['kode' => '500.3.7.4', 'keterangan' => 'Fasilitasi Investasi UKMK'],
            ['kode' => '500.3.7.5', 'keterangan' => 'Pengembangan Sarana Bisnis'],
            ['kode' => '500.3.8', 'keterangan' => 'Pengkajian Sumber Daya UKMK'],
            ['kode' => '500.3.8.1', 'keterangan' => 'Penelitian Koperasi'],
            ['kode' => '500.3.8.2', 'keterangan' => 'Penelitian UKM'],
            ['kode' => '500.3.8.3', 'keterangan' => 'Penelitian Sumber Daya'],
            ['kode' => '500.3.8.4', 'keterangan' => 'Pengembangan Perkaderan UMK'],
            ['kode' => '500.3.9', 'keterangan' => 'Kerja Sama Hubungan Antar Lembaga'],
            ['kode' => '500.3.10', 'keterangan' => 'Pedagang Kaki Lima (PKL)'],
            ['kode' => '500.3.10.1', 'keterangan' => 'Peraturan Perundang-Undangan'],
            ['kode' => '500.3.10.2', 'keterangan' => 'Sarana dan Prasarana'],
            ['kode' => '500.3.11', 'keterangan' => 'Monitoring dan Evaluasi'],
            ['kode' => '500.4', 'keterangan' => 'KEHUTANAN'],
            ['kode' => '500.4.1', 'keterangan' => 'Kebijakan di bidang Kehutanan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.4.2', 'keterangan' => 'Penyuluhan'],
            ['kode' => '500.4.2.1', 'keterangan' => 'Program Kerja Penyuluhan'],
            ['kode' => '500.4.2.2', 'keterangan' => 'Materi Penyuluhan'],
            ['kode' => '500.4.2.3', 'keterangan' => 'Program Penyuluhan'],
            ['kode' => '500.4.2.4', 'keterangan' => 'Sarana Penyuluhan'],
            ['kode' => '500.4.2.5', 'keterangan' => 'Pengembangan Tenaga Penyuluhan'],
            ['kode' => '500.4.2.6', 'keterangan' => 'Pelaksanaan Penyuluhan'],
            ['kode' => '500.4.2.7', 'keterangan' => 'Pemberdayaan Masyarakat'],
            ['kode' => '500.4.2.8', 'keterangan' => 'Deseminasi'],
            ['kode' => '500.4.2.9', 'keterangan' => 'Evaluasi, dan Laporan'],
            ['kode' => '500.4.3', 'keterangan' => 'Planologi Kehutanan'],
            ['kode' => '500.4.3.1', 'keterangan' => 'Perencanaan Makro Kawasan Hutan'],
            ['kode' => '500.4.3.2', 'keterangan' => 'Penataan Ruang Kawasan Hutan'],
            ['kode' => '500.4.3.3', 'keterangan' => 'Statistik dan Jaringan Komunikasi Data Kehutanan'],
            ['kode' => '500.4.3.4', 'keterangan' => 'Pengukuhan dan Penataaan Kawasan Hutan'],
            ['kode' => '500.4.3.5', 'keterangan' => 'Perubahan Fungsi dan Peruntukan Kawasan Hutan'],
            ['kode' => '500.4.3.6', 'keterangan' => 'Informasi dan Dokumentasi Kawasan Hutan'],
            ['kode' => '500.4.3.7', 'keterangan' => 'Inventarisasi Sumber Daya Hutan'],
            ['kode' => '500.4.3.8', 'keterangan' => 'Pemantauan Sumber Daya Hutan'],
            ['kode' => '500.4.3.9', 'keterangan' => 'Pemetaan Sumber Daya Hutan'],
            ['kode' => '500.4.3.10', 'keterangan' => 'Jaringan Data Spasial'],
            ['kode' => '500.4.3.11', 'keterangan' => 'Penggunaan Kawasan Hutan'],
            ['kode' => '500.4.3.12', 'keterangan' => 'Penerimaan Negara Bukan Pajak (PNBP) Penggunaan Kawasan Hutan'],
            ['kode' => '500.4.3.13', 'keterangan' => 'Informasi Penggunaan Kawasan Hutan'],
            ['kode' => '500.4.3.14', 'keterangan' => 'Pembentukan Wilayah Pengelolaan Hutan'],
            ['kode' => '500.4.3.15', 'keterangan' => 'Penyiapan Areal Pemanfaatan Hutan'],
            ['kode' => '500.4.3.16', 'keterangan' => 'Informasi Wilayah Pengelolaan dan Pemanfaatan Kawasan Hutan'],
            ['kode' => '500.4.4', 'keterangan' => 'Bina Usaha Kehutanan'],
            ['kode' => '500.4.4.1', 'keterangan' => 'Data areal HPH / HTI / IUPHHK'],
            ['kode' => '500.4.4.2', 'keterangan' => 'SK HPH / HTI / IUPHHK'],
            ['kode' => '500.4.4.3', 'keterangan' => 'Kerjasama'],
            ['kode' => '500.4.4.4', 'keterangan' => 'Pembatalan / Penolakan'],
            ['kode' => '500.4.4.5', 'keterangan' => 'Perpanjangan'],
            ['kode' => '500.4.4.6', 'keterangan' => 'Modal dan Peralatan'],
            ['kode' => '500.4.4.7', 'keterangan' => 'Investasi Industri'],
            ['kode' => '500.4.4.8', 'keterangan' => 'Peralatan'],
            ['kode' => '500.4.4.9', 'keterangan' => 'Tenaga Kerja'],
            ['kode' => '500.4.4.10', 'keterangan' => 'Pemegang Saham'],
            ['kode' => '500.4.4.11', 'keterangan' => 'Neraca Perusahaan'],
            ['kode' => '500.4.4.12', 'keterangan' => 'Rencana Karya Kesatuan Pengelolaan Hutan Produksi (KPHP)'],
            ['kode' => '500.4.4.13', 'keterangan' => 'Rencana Karya Pengusahaan Hutan (RKPH)'],
            ['kode' => '500.4.4.14', 'keterangan' => 'Rencana Karya Tahunan Pengusahaan Hutan (RKT)'],
            ['kode' => '500.4.4.15', 'keterangan' => 'Rencana Karya Lima Tahun Pengusahaan Hutan (RKL)'],
            ['kode' => '500.4.4.16', 'keterangan' => 'Target Produksi RKT dan Beban Kerja'],
            ['kode' => '500.4.4.17', 'keterangan' => 'Produksi Kayu'],
            ['kode' => '500.4.4.18', 'keterangan' => 'Produksi non kayu'],
            ['kode' => '500.4.4.19', 'keterangan' => 'Industri Kayu HPH/HTI/IUPHHK'],
            ['kode' => '500.4.4.20', 'keterangan' => 'Industri Kayu Non HPH/HTI/IUPHHK'],
            ['kode' => '500.4.4.21', 'keterangan' => 'Industri Non Kayu'],
            ['kode' => '500.4.4.22', 'keterangan' => 'Hutan Tanaman Industri Pulp'],
            ['kode' => '500.4.4.23', 'keterangan' => 'Hutan Tanaman Industri Pertukangan'],
            ['kode' => '500.4.4.24', 'keterangan' => 'Pelanggaran dan Sanksi'],
            ['kode' => '500.4.4.25', 'keterangan' => 'Pemblokiran'],
            ['kode' => '500.4.4.26', 'keterangan' => 'Denda'],
            ['kode' => '500.4.4.27', 'keterangan' => 'Pencabutan Areal HPH/HTI/IUPHHK'],
            ['kode' => '500.4.4.28', 'keterangan' => 'Pola Pemanfaatan Hutan Produksi'],
            ['kode' => '500.4.4.29', 'keterangan' => 'Penataan Pemanfaatan Hutan Produksi'],
            ['kode' => '500.4.4.30', 'keterangan' => 'Informasi Sumber Daya Hutan Produksi'],
            ['kode' => '500.4.4.31', 'keterangan' => 'Pengembangan Investasi Usaha'],
            ['kode' => '500.4.4.32', 'keterangan' => 'Penyiapan Pemanfaatan Hutan Alam'],
            ['kode' => '500.4.4.33', 'keterangan' => 'Rencana Kerja Pemanfaatan Hutan Alam/Rencana Kerja Usaha Produksi Hasil'],
            ['kode' => '500.4.4.34', 'keterangan' => 'Produksi Hutan Alam'],
            ['kode' => '500.4.4.35', 'keterangan' => 'Penilaian Kinerja Usaha Pemanfaatan Hutan Alam'],
            ['kode' => '500.4.4.36', 'keterangan' => 'Pengembangan Hutan Tanaman Industri'],
            ['kode' => '500.4.4.37', 'keterangan' => 'Pengembangan Hutan Tanaman Rakyat'],
            ['kode' => '500.4.4.38', 'keterangan' => 'Pengembangan Rencana Kerja dan Produksi Hutan Tanaman/Rencana Kerja Usaha Produksi'],
            ['kode' => '500.4.4.39', 'keterangan' => 'Penilaian Kinerja Pengembangan Usaha Pemanfaatan Hutan Tanaman'],
            ['kode' => '500.4.4.40', 'keterangan' => 'Pembiayaan Hutan Tanaman'],
            ['kode' => '500.4.4.41', 'keterangan' => 'Penerimaan Negara Bukan Pajak Hasil Hutan'],
            ['kode' => '500.4.4.42', 'keterangan' => 'Peredaran Hasil Hutan'],
            ['kode' => '500.4.4.43', 'keterangan' => 'Pengukuran dan Pengujian Hasil Hutan'],
            ['kode' => '500.4.4.44', 'keterangan' => 'Penertiban Peredaran Hasil Hutan'],
            ['kode' => '500.4.4.45', 'keterangan' => 'Pengolahan dan Pemasaran Hasil Hutan'],
            ['kode' => '500.4.4.46', 'keterangan' => 'Pengendalian Bahan Baku dan Industri Primer Hasil Hutan'],
            ['kode' => '500.4.4.47', 'keterangan' => 'Penilaian Kinerja Industri dan Pemasaran Hasil Hutan'],
            ['kode' => '500.4.4.48', 'keterangan' => 'Pembinaan HPH/HTI/IUPHHK'],
            ['kode' => '500.4.4.49', 'keterangan' => 'Pembinaan TPTI/TPTJ/Silvikultur'],
            ['kode' => '500.4.5', 'keterangan' => 'Standardisasi dan Lingkungan'],
            ['kode' => '500.4.5.1', 'keterangan' => 'Standardisasi'],
            ['kode' => '500.4.5.2', 'keterangan' => 'Sarana Pengujian Hasil Hutan'],
            ['kode' => '500.4.5.3', 'keterangan' => 'Pengembangan'],
            ['kode' => '500.4.5.4', 'keterangan' => 'Pemasaran Hasil Hutan'],
            ['kode' => '500.4.5.5', 'keterangan' => 'Pengendalian Lingkungan'],
            ['kode' => '500.4.5.6', 'keterangan' => 'Angkutan Hasil Hutan'],
            ['kode' => '500.4.5.7', 'keterangan' => 'Tanda Pengenal Perusahaan Tata Usaha Hasil Hutan'],
            ['kode' => '500.4.5.8', 'keterangan' => 'Legalitas Tata Usaha Hasil Hutan'],
            ['kode' => '500.4.5.9', 'keterangan' => 'Palu Tok Kualitas Tata Usaha Hasil Hutan'],
            ['kode' => '500.4.5.10', 'keterangan' => 'Pass Angkutan Hasil Hutan'],
            ['kode' => '500.4.5.11', 'keterangan' => 'Sertifikat Ekspor Hasil Hutan'],
            ['kode' => '500.4.6', 'keterangan' => 'Perlindungan Hutan dan Konservasi Alam'],
            ['kode' => '500.4.6.1', 'keterangan' => 'Flora dan Fauna yang Dilindungi'],
            ['kode' => '500.4.6.2', 'keterangan' => 'Flora dan Fauna yang Tidak Dilindungi'],
            ['kode' => '500.4.6.3', 'keterangan' => 'Lembaga Konservasi/Kebun Binatang'],
            ['kode' => '500.4.6.4', 'keterangan' => 'Konvensi Keanekaragaman Hayati'],
            ['kode' => '500.4.6.5', 'keterangan' => 'Kawasan Konservasi'],
            ['kode' => '500.4.6.6', 'keterangan' => 'Pengamanan Hutan'],
            ['kode' => '500.4.6.7', 'keterangan' => 'Program dan Evaluasi Penyidikan dan Perlindungan'],
            ['kode' => '500.4.6.8', 'keterangan' => 'Penyidikan dan Perlindungan Wilayah Hutan'],
            ['kode' => '500.4.6.9', 'keterangan' => 'Polisi Kehutanan dan Penyidik Pegawai Negeri Sipil (PPNS)'],
            ['kode' => '500.4.6.10', 'keterangan' => 'Pemanfaatan Jasa Lingkungan dan Wisata Alam'],
            ['kode' => '500.4.6.11', 'keterangan' => 'Bina Cinta Alam'],
            ['kode' => '500.4.6.12', 'keterangan' => 'Kader Konservasi Sumber Daya Alam'],
            ['kode' => '500.4.6.13', 'keterangan' => 'Data organisasi pencinta alam dan kader konservasi SDA'],
            ['kode' => '500.4.7', 'keterangan' => 'Bina Pengelolaan Daerah Aliran Sungai dan Perhutanan Sosial'],
            ['kode' => '500.4.7.1', 'keterangan' => 'Pengelolaan Benih'],
            ['kode' => '500.4.7.2', 'keterangan' => 'Kebun Benih'],
            ['kode' => '500.4.7.3', 'keterangan' => 'Tegakan Benih'],
            ['kode' => '500.4.7.4', 'keterangan' => 'Pengadaan Benih'],
            ['kode' => '500.4.7.5', 'keterangan' => 'Pengujian dan Penyimpanan Benih'],
            ['kode' => '500.4.7.6', 'keterangan' => 'Lalu Lintas Angkutan Benih'],
            ['kode' => '500.4.7.7', 'keterangan' => 'Pembibitan'],
            ['kode' => '500.4.7.8', 'keterangan' => 'Lalu Lintas Angkutan Benih'], // Catatan: Kode ini muncul dua kali di dokumen asli
            ['kode' => '500.4.7.9', 'keterangan' => 'Pengembangan Usaha Perbenihan'],
            ['kode' => '500.4.7.10', 'keterangan' => 'Pengendalian Peredaran Benih'],
            ['kode' => '500.4.7.11', 'keterangan' => 'Rehabilitasi Hutan dan Lahan'],
            ['kode' => '500.4.7.12', 'keterangan' => 'Tanaman Reboisasi'],
            ['kode' => '500.4.7.13', 'keterangan' => 'Pengelolaan Daerah Aliran Sungai (DAS)'],
            ['kode' => '500.4.7.14', 'keterangan' => 'Perhutanan Sosial'],
            ['kode' => '500.4.7.15', 'keterangan' => 'Pengendalian Perladangan'],
            ['kode' => '500.4.8', 'keterangan' => 'Penelitian dan Pengembangan Kehutanan'],
            ['kode' => '500.4.8.1', 'keterangan' => 'Penelitian, Pengkajian dan Pengembangan Kehutanan'],
            ['kode' => '500.4.8.2', 'keterangan' => 'Monitoring dan Evaluasi Penelitian'],
            ['kode' => '500.4.8.3', 'keterangan' => 'Diseminasi'],
            ['kode' => '500.4.8.4', 'keterangan' => 'Gelar Teknologi'],
            ['kode' => '500.4.8.5', 'keterangan' => 'Forum Komunikasi Penelitian dan Pengembangan'],
            ['kode' => '500.5', 'keterangan' => 'KELAUTAN DAN PERIKANAN'],
            ['kode' => '500.5.1', 'keterangan' => 'Kebijakan di bidang Kelautan dan Perikanan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.5.2', 'keterangan' => 'Perikanan Tangkap'],
            ['kode' => '500.5.2.1', 'keterangan' => 'Data dan Statistik Perikanan Tangkap'],
            ['kode' => '500.5.2.2', 'keterangan' => 'Rancang Bangun dan Kelaikan Kapal Perikanan'],
            ['kode' => '500.5.2.3', 'keterangan' => 'Rancang Bangun dan Kelaikan Alat Tangkap Ikan'],
            ['kode' => '500.5.2.4', 'keterangan' => 'Pendaftaran Kapal Perikanan'],
            ['kode' => '500.5.2.5', 'keterangan' => 'Pengawakan Kapal dan Ketenagakerjaan Perikanan'],
            ['kode' => '500.5.2.6', 'keterangan' => 'Perbantuan dan Evaluasi Kapal Perikanan dan Alat Penangkapan Ikan'],
            ['kode' => '500.5.2.7', 'keterangan' => 'Alokasi Usaha Penangkapan Ikan'],
            ['kode' => '500.5.2.8', 'keterangan' => 'Tata Pengusahaan Penangkapan Ikan'],
            ['kode' => '500.5.2.9', 'keterangan' => 'Verifikasi Dokumen Penangkapan Ikan'],
            ['kode' => '500.5.2.10', 'keterangan' => 'Pelayanan Dokumen Penangkapan Ikan'],
            ['kode' => '500.5.2.11', 'keterangan' => 'Pemantauan dan Evaluasi Pelayanan Usaha Penangkapan Ikan'],
            ['kode' => '500.5.2.12', 'keterangan' => 'Kelembagaan Usaha Penangkapan'],
            ['kode' => '500.5.2.13', 'keterangan' => 'Investasi dan Permodalan Usaha'],
            ['kode' => '500.5.2.14', 'keterangan' => 'Kenelayanan'],
            ['kode' => '500.5.2.15', 'keterangan' => 'Pembinaan Pengelolaan Usaha'],
            ['kode' => '500.5.2.16', 'keterangan' => 'Pemantauan dan Evaluasi Usaha Penangkapan Ikan'],
            ['kode' => '500.5.3', 'keterangan' => 'Perikanan Budidaya'],
            ['kode' => '500.5.3.1', 'keterangan' => 'Potensi Lahan dan Air'],
            ['kode' => '500.5.3.2', 'keterangan' => 'Prasarana dan Sarana Budidaya Air Tawar'],
            ['kode' => '500.5.3.3', 'keterangan' => 'Pengelolaan Induk Perbenihan ikan air tawar'],
            ['kode' => '500.5.3.4', 'keterangan' => 'Perbenihan Skala Kecil'],
            ['kode' => '500.5.3.5', 'keterangan' => 'Informasi dan Distribusi Pembenihan'],
            ['kode' => '500.5.3.6', 'keterangan' => 'Budidaya Air Tawar'],
            ['kode' => '500.5.3.7', 'keterangan' => 'Budidaya Ikan Hias'],
            ['kode' => '500.5.3.8', 'keterangan' => 'Sertifikasi Budidaya Perikanan'],
            ['kode' => '500.5.3.9', 'keterangan' => 'Data dan Statistik Perikanan Budidaya'],
            ['kode' => '500.5.3.10', 'keterangan' => 'Hama dan Penyakit Ikan'],
            ['kode' => '500.5.3.11', 'keterangan' => 'Perlindungan Lingkungan Budidaya'],
            ['kode' => '500.5.3.12', 'keterangan' => 'Investasi dan Permodalan Usaha Budidaya'],
            ['kode' => '500.5.3.13', 'keterangan' => 'Kewirausahaan Budidaya'],
            ['kode' => '500.5.3.14', 'keterangan' => 'Pelayanan Usaha Budidaya'],
            ['kode' => '500.5.3.15', 'keterangan' => 'Kelembagaan dan Ketenagaakerjaan'],
            ['kode' => '500.5.3.16', 'keterangan' => 'Promosi Usaha dan Budaya'],
            ['kode' => '500.5.4', 'keterangan' => 'Pengolahan dan Pemasaran Hasil Perikanan'],
            ['kode' => '500.5.4.1', 'keterangan' => 'Standarisasi Pengolahan Hasil'],
            ['kode' => '500.5.4.2', 'keterangan' => 'Pengembangan Produk'],
            ['kode' => '500.5.4.3', 'keterangan' => 'Pengembangan Usaha Mikro, Kecil, dan Menengah'],
            ['kode' => '500.5.4.4', 'keterangan' => 'Industri Pengolahan'],
            ['kode' => '500.5.4.5', 'keterangan' => 'Sarana dan Prasarana Pengolahan Hasil'],
            ['kode' => '500.5.4.6', 'keterangan' => 'Standarisasi Pengembangan Produk Non Konsumsi'],
            ['kode' => '500.5.4.7', 'keterangan' => 'Promosi dan Jaringan Ikan Hias'],
            ['kode' => '500.5.4.8', 'keterangan' => 'Pengembangan Industri'],
            ['kode' => '500.5.4.9', 'keterangan' => 'Sarana dan Prasarana Pengembangan Produk Non Konsumsi'],
            ['kode' => '500.5.4.10', 'keterangan' => 'Kelembagaan Pemasaran Dalam Negeri'],
            ['kode' => '500.5.4.11', 'keterangan' => 'Analisis dan Informasi Pasar Dalam Negeri'],
            ['kode' => '500.5.4.12', 'keterangan' => 'Jaringan Distribusi dan Kemitraan Pemasaran Dalam Negeri'],
            ['kode' => '500.5.4.13', 'keterangan' => 'Promosi dan Kerja Sama Pemasaran Dalam Negeri'],
            ['kode' => '500.5.4.14', 'keterangan' => 'Sarana dan Prasarana Pemasaran Dalam Negeri'],
            ['kode' => '500.5.4.15', 'keterangan' => 'Kelembagaan Pemasaran Luar Negeri'],
            ['kode' => '500.5.4.16', 'keterangan' => 'Analisis dan Informasi Pemasaran Luar Negeri'],
            ['kode' => '500.5.4.17', 'keterangan' => 'Pengembangan Ekspor'],
            ['kode' => '500.5.4.18', 'keterangan' => 'Pengembangan Impor'],
            ['kode' => '500.5.4.19', 'keterangan' => 'Promosi dan Kerja Sama Pemasaran Luar Negeri'],
            ['kode' => '500.5.4.20', 'keterangan' => 'Pelayanan Usaha'],
            ['kode' => '500.5.4.21', 'keterangan' => 'Kemitraan Usaha'],
            ['kode' => '500.5.4.22', 'keterangan' => 'Ketenagakerjaan Pengolahan dan Pemasaran'],
            ['kode' => '500.5.4.23', 'keterangan' => 'Investasi dan Permodalan'],
            ['kode' => '500.5.4.24', 'keterangan' => 'Informasi dan Promosi'],
            ['kode' => '500.5.5', 'keterangan' => 'Kelautan, Pesisir, dan Pulau-Pulau Kecil'],
            ['kode' => '500.5.5.1', 'keterangan' => 'Rencana Tata Ruang Laut Nasional dan Perairan Yurisdiksi'],
            ['kode' => '500.5.5.2', 'keterangan' => 'Rencana Tata Ruang dan Zona Wilayah I'],
            ['kode' => '500.5.5.3', 'keterangan' => 'Rencana Tata Ruang dan Zona Wilayah II'],
            ['kode' => '500.5.5.4', 'keterangan' => 'Informasi dan Evaluasi Spasial'],
            ['kode' => '500.5.5.5', 'keterangan' => 'Jejaring, Data, dan Informasi Konservasi'],
            ['kode' => '500.5.5.6', 'keterangan' => 'Konservasi Wawasan'],
            ['kode' => '500.5.5.7', 'keterangan' => 'Konservasi Jenis Ikan'],
            ['kode' => '500.5.5.8', 'keterangan' => 'Pemanfaatan Kawasan dan Jenis Ikan'],
            ['kode' => '500.5.5.9', 'keterangan' => 'Mitigasi Bencana Lingkungan'],
            ['kode' => '500.5.5.10', 'keterangan' => 'Pendayagunaan Sumber Daya Kelautan'],
            ['kode' => '500.5.5.11', 'keterangan' => 'Penanggulangan Pencemaran Sumber Daya Pesisir dan Laut'],
            ['kode' => '500.5.5.12', 'keterangan' => 'Rehabilitasi dan Reklamasi'],
            ['kode' => '500.5.5.13', 'keterangan' => 'Identifikasi Pulau-Pulau Terkecil'],
            ['kode' => '500.5.5.14', 'keterangan' => 'Pengelolaan Ekosistem Pulau-Pulau Terkecil'],
            ['kode' => '500.5.5.15', 'keterangan' => 'Investasi dan Promosi Pulau-Pulau Terkecil'],
            ['kode' => '500.5.5.16', 'keterangan' => 'Sarana dan Prasarana Pulau-Pulau Terkecil'],
            ['kode' => '500.5.5.17', 'keterangan' => 'Akses Permodalan'],
            ['kode' => '500.5.5.18', 'keterangan' => 'Akses Ilmu Pengetahuan dan Teknologi'],
            ['kode' => '500.5.5.19', 'keterangan' => 'Sosial Budaya Masyarakat'],
            ['kode' => '500.5.5.20', 'keterangan' => 'Pengembangan Usaha'],
            ['kode' => '500.5.6', 'keterangan' => 'Pengawasan Sumber Daya Kelautan Dan Perikanan'],
            ['kode' => '500.5.6.1', 'keterangan' => 'Pengawasan Penangkapan Wilayah Barat'],
            ['kode' => '500.5.6.2', 'keterangan' => 'Pengawasan Penangkapan Wilayah Timur'],
            ['kode' => '500.5.6.3', 'keterangan' => 'Pengawasan Pengangkutan, Pengolahan dan Pemasaran'],
            ['kode' => '500.5.6.4', 'keterangan' => 'Pengawasan Usaha Budidaya'],
            ['kode' => '500.5.6.5', 'keterangan' => 'Pengawasan Ekosistem Perairan dan Kawasan Konservasi'],
            ['kode' => '500.5.6.6', 'keterangan' => 'Pengawasan Pencemaran Perairan'],
            ['kode' => '500.5.6.7', 'keterangan' => 'Pengawasan Pesisir dan Pulau-Pulau Terkecil'],
            ['kode' => '500.5.6.8', 'keterangan' => 'Pengawasan Jasa Kelautan dan Sumber Daya Non Hayati'],
            ['kode' => '500.5.6.9', 'keterangan' => 'Logistik dan Operasional Wilayah Barat'],
            ['kode' => '500.5.6.10', 'keterangan' => 'Logistik dan Operasional Wilayah Timur'],
            ['kode' => '500.5.6.11', 'keterangan' => 'Perawatan Kapal Pengawas'],
            ['kode' => '500.5.6.12', 'keterangan' => 'Pengawakan Kapal Pengawas'],
            ['kode' => '500.5.6.13', 'keterangan' => 'Sistem Pemantauan'],
            ['kode' => '500.5.6.14', 'keterangan' => 'Pemantauan Pemanfaatan Sumber Daya Kelautan'],
            ['kode' => '500.5.6.15', 'keterangan' => 'Pemantauan Sumber Daya Perikanan'],
            ['kode' => '500.5.6.16', 'keterangan' => 'Pengembangan Infrastruktur Pengawasan'],
            ['kode' => '500.5.6.17', 'keterangan' => 'Penyidikan'],
            ['kode' => '500.5.6.18', 'keterangan' => 'Penanganan Barang Bukti dan Awak Kapal'],
            ['kode' => '500.5.6.19', 'keterangan' => 'Kerja Sama Penegakan Hukum dan Fasilitas PPNS Perikanan'],
            ['kode' => '500.5.6.20', 'keterangan' => 'Pemantauan dan Evaluasi Penanganan Pelanggaran'],
            ['kode' => '500.5.7', 'keterangan' => 'Karantina Ikan'],
            ['kode' => '500.5.7.1', 'keterangan' => 'Pemeriksaan Ikan'],
            ['kode' => '500.5.7.2', 'keterangan' => 'Penahanan'],
            ['kode' => '500.5.7.3', 'keterangan' => 'Pengasingan'],
            ['kode' => '500.5.7.4', 'keterangan' => 'Pengamatan'],
            ['kode' => '500.5.7.5', 'keterangan' => 'Pengakuan'],
            ['kode' => '500.5.7.6', 'keterangan' => 'Penolakan'],
            ['kode' => '500.5.7.7', 'keterangan' => 'Pemusnahan'],
            ['kode' => '500.5.7.8', 'keterangan' => 'Persyaratan lalu Lintas Pemasukan'],
            ['kode' => '500.5.7.9', 'keterangan' => 'Persyaratan lalu Lintas Pengeluaran'],
            ['kode' => '500.5.7.10', 'keterangan' => 'Permohonan Sertifikat'],
            ['kode' => '500.5.7.11', 'keterangan' => 'Pemasukan Formulir'],
            ['kode' => '500.5.7.12', 'keterangan' => 'Pemasukan Sertifikat'],
            ['kode' => '500.5.7.13', 'keterangan' => 'Evaluasi dan Monitoring Sertifikat'],
            ['kode' => '500.5.7.14', 'keterangan' => 'Surat Perintah'],
            ['kode' => '500.5.7.15', 'keterangan' => 'Rekomendasi'],
            ['kode' => '500.5.7.16', 'keterangan' => 'Penutupan Suatu Area'],
            ['kode' => '500.5.7.17', 'keterangan' => 'Pelanggaran Lalu Lintas Ikan'],
            ['kode' => '500.5.7.18', 'keterangan' => 'Pengawasan Peraturan Perkarantinaan'],
            ['kode' => '500.5.7.19', 'keterangan' => 'Pengawasan Pelaksanaan Operasional'],
            ['kode' => '500.5.7.20', 'keterangan' => 'Instalasi Karantina Sementara'],
            ['kode' => '500.5.7.21', 'keterangan' => 'Lokasi Karantina'],
            ['kode' => '500.6', 'keterangan' => 'PERTANIAN'],
            ['kode' => '500.6.1', 'keterangan' => 'Kebijakan di bidang Pertanian yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '500.6.2', 'keterangan' => 'Perlindungan hortikultura'],
            ['kode' => '500.6.2.1', 'keterangan' => 'Perlindungan Tanaman Buah'],
            ['kode' => '500.6.2.2', 'keterangan' => 'Perlindungan Tanaman Sayuran dan Tanaman Obat'],
            ['kode' => '500.6.2.3', 'keterangan' => 'Perlindungan Tanaman Florikultura'],
            ['kode' => '500.6.2.4', 'keterangan' => 'Dampak iklim dan Persyaratan Teknis'],
            ['kode' => '500.6.3', 'keterangan' => 'Perbenihan Hortikultura'],
            ['kode' => '500.6.3.1', 'keterangan' => 'Penilaian Varietas'],
            ['kode' => '500.6.3.2', 'keterangan' => 'Pengawasan Mutu Benih'],
            ['kode' => '500.6.3.3', 'keterangan' => 'Budidaya dan Pascapanen Florikultura'],
            ['kode' => '500.6.4', 'keterangan' => 'Perluasan dan Pengelolaan Lahan'],
            ['kode' => '500.6.4.1', 'keterangan' => 'Basis Data Lahan'],
            ['kode' => '500.6.4.2', 'keterangan' => 'Pengendalian Lahan'],
            ['kode' => '500.6.4.3', 'keterangan' => 'Optimasi, Rehabilitasi dan Konservasi Lahan'],
            ['kode' => '500.6.4.4', 'keterangan' => 'Perluasan Kawasan Tanaman Pangan'],
            ['kode' => '500.6.4.5', 'keterangan' => 'Perluasan Kawasan Hortikultura, Perkebunan dan Peternakan'],
            ['kode' => '500.6.5', 'keterangan' => 'Pengelolaan Air Irigasi'],
            ['kode' => '500.6.5.1', 'keterangan' => 'Pengembangan Sumber Air'],
            ['kode' => '500.6.5.2', 'keterangan' => 'Pengembangan Jaringan dan Optimasi Air'],
            ['kode' => '500.6.5.3', 'keterangan' => 'Iklim, Konservasi Air dan Lingkungan Hidup'],
            ['kode' => '500.6.5.4', 'keterangan' => 'Kelembagaan'],
            ['kode' => '500.6.6', 'keterangan' => 'Pembiayaan Pertanian'],
            ['kode' => '500.6.6.1', 'keterangan' => 'Pembiayaan Program'],
            ['kode' => '500.6.6.2', 'keterangan' => 'Pembiayaan Syariah dan Kerja Sama'],
            ['kode' => '500.6.6.3', 'keterangan' => 'Pembiayaan agribisnis'],
            ['kode' => '500.6.6.4', 'keterangan' => 'Kelembagaan dan Pemberdayaan agribisnis'],
            ['kode' => '500.6.7', 'keterangan' => 'Pupuk Pestisida'],
            ['kode' => '500.6.7.1', 'keterangan' => 'Pupuk Organik dan Pembenah Tanah'],
            ['kode' => '500.6.7.2', 'keterangan' => 'Pupuk Anorganik'],
            ['kode' => '500.6.7.3', 'keterangan' => 'Pestisida'],
            ['kode' => '500.6.7.4', 'keterangan' => 'Pengawasan Pupuk dan Pestisida'],
            ['kode' => '500.6.8', 'keterangan' => 'Alat dan Mesin Pertanian'],
            ['kode' => '500.6.8.1', 'keterangan' => 'Pengembangan Alat dan Mesin Pertanian'],
            ['kode' => '500.6.8.2', 'keterangan' => 'Pengawasan dan Peredaran Alat dan Mesin Pertanian'],
            ['kode' => '500.6.8.3', 'keterangan' => 'Kelembagaan dan Pelayanan Alat dan Mesin Pertanian'],
            ['kode' => '500.6.9', 'keterangan' => 'Perbenihan Tanaman Pangan'],
            ['kode' => '500.6.9.1', 'keterangan' => 'Penilaian Varietas dan Pengawasan Mutu Benih'],
        ];

        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
