<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi800Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            ['kode' => '800', 'keterangan' => 'KEPEGAWAIAN'],
            ['kode' => '800.1', 'keterangan' => 'SUMBER DAYA MANUSIA'],
            ['kode' => '800.1.1', 'keterangan' => 'Penyusunan dan Penetapan Kebutuhan Aparatur Sipil Negara'],
            ['kode' => '800.1.1.1', 'keterangan' => 'Perencanaan Kebutuhan Aparatur Sipil Negara Antara lain: Bahan penyusunan rencana kebutuhan, Analisis Kebutuhan, Pengolahan data kebutuhan'],
            ['kode' => '800.1.1.2', 'keterangan' => 'Perencanaan Pertimbangan Formasi Antara lain: Pertimbangan teknis penetapan formasi ASN, Pertimbangan teknis penetapan formasi ikatan dinas'],
            ['kode' => '800.1.1.3', 'keterangan' => 'Penetapan Kebutuhan Aparatur Sipil Negara'],
            ['kode' => '800.1.1.4', 'keterangan' => 'Standarisasi Jabatan Antara lain: Informasi Jabatan, Kompetensi Jabatan, Klasifikasi Jabatan'],
            ['kode' => '800.1.2', 'keterangan' => 'Formasi dan Pengadaan Pegawai'],
            ['kode' => '800.1.2.1', 'keterangan' => 'Formasi ASN Antara lain: Usulan formasi, Usulan permintaan formasi kepada Menpan RB dan Kepala BKN, Persetujuan Formasi, Penetapan Formasi, Penetapan Formasi Khusus'],
            ['kode' => '800.1.2.2', 'keterangan' => 'Proses Rekrutmen/Pengadaan ASN Antara lain: Proses Rekrutmen ASN, Penetapan Pengumuman Kelulusan ASN'],
            ['kode' => '800.1.2.3', 'keterangan' => 'Pengumuman Kelulusan ASN'],
            ['kode' => '800.1.2.4', 'keterangan' => 'Berkas Lamaran Yang Tidak Diterima'],
            ['kode' => '800.1.2.5', 'keterangan' => 'Pengangkatan ASN'],
            ['kode' => '800.1.2.6', 'keterangan' => 'Open Biding (Seleksi Terbuka Jabatan)'],
            ['kode' => '800.1.2.7', 'keterangan' => 'Pengelolaan Sistem Rekrutmen ASN'],
            ['kode' => '800.1.2.8', 'keterangan' => 'Fasilitasi Penyelenggaraan Seleksi ASN'],
            ['kode' => '800.1.3', 'keterangan' => 'Mutasi Pegawai'],
            ['kode' => '800.1.3.1', 'keterangan' => 'Usulan Alih Status, Pindah Instansi, Pindah Wilayah Kerja, Diperbantukan, Dipekerjakan, Penugasan Sementara, Mutasi antar Perwakilan, Mutasi ke dan dari Perwakilan, Pemindahan Sementara, Persetujuan/Pertimbangan Kepala BKN'],
            ['kode' => '800.1.3.2', 'keterangan' => 'Kenaikan Pangkat/Golongan/Jabatan'],
            ['kode' => '800.1.3.3', 'keterangan' => 'Pengangkatan dan Pemberhentian Jabatan Struktural/Fungsional'],
            ['kode' => '800.1.3.4', 'keterangan' => 'Perubahan Data Dasar/Status/Kedudukan Hukum Pegawai'],
            ['kode' => '800.1.3.5', 'keterangan' => 'Peninjauan Masa Kerja'],
            ['kode' => '800.1.3.6', 'keterangan' => 'Badan Pertimbangan Jabatan dan Pangkat (BAPERJAKAT)'],
            ['kode' => '800.1.4', 'keterangan' => 'Pengembangan Karir'],
            ['kode' => '800.1.4.1', 'keterangan' => 'Usulan Tugas Belajar/ Ijin Belajar/ Diklat/ Kursus/ Magang/ Ujian Dinas/ Praktek Kerja di Instansi lain/ Pertukaran antar ASN dengan pegawai swasta'],
            ['kode' => '800.1.4.2', 'keterangan' => 'Penyesuaian ijazah'],
            ['kode' => '800.1.4.3', 'keterangan' => 'Penyusunan Sistem Karier'],
            ['kode' => '800.1.4.4', 'keterangan' => 'Standar Kinerja Pegawai (SKP) dan Penilaian Prestasi Kerja'],
            ['kode' => '800.1.4.5', 'keterangan' => 'Angka Kredit Antara lain: Pengajuan Daftar Usul Pengajuan Angka Kredit, Penilaian Daftar Usul Pengajuan Angka Kredit'],
            ['kode' => '800.1.5', 'keterangan' => 'Kinerja Aparatur Sipil Negara'],
            ['kode' => '800.1.5.1', 'keterangan' => 'Hasil Penilaian Kinerja dan Standar Kerja'],
            ['kode' => '800.1.5.2', 'keterangan' => 'Pengelolaan Database dan Analisis Sistem Informasi Kinerja'],
            ['kode' => '800.1.5.3', 'keterangan' => 'Evaluasi dan Pemantauan Penilaian Kinerja dan Standar Kerja'],
            ['kode' => '800.1.6', 'keterangan' => 'Kode Etik, Disiplin, Pemberhentian dan Pensiun ASN'],
            ['kode' => '800.1.6.1', 'keterangan' => 'Kode Etik Pegawai'],
            ['kode' => '800.1.6.2', 'keterangan' => 'Disiplin'],
            ['kode' => '800.1.6.3', 'keterangan' => 'Pemberhentian Dengan Hormat'],
            ['kode' => '800.1.6.4', 'keterangan' => 'Pemberhentian Dengan Tidak Hormat'],
            ['kode' => '800.1.6.5', 'keterangan' => 'Pemberhentian Sementara'],
            ['kode' => '800.1.6.6', 'keterangan' => 'Pensiun ASN Antara lain: Administrasi Pensiun ASN, Penetapan Pensiun ASN, Penetapan Pertimbangan Teknis Pensiun ASN, Pensiun Pejabat Negara dan Janda/ Dudanya'],
            ['kode' => '800.1.7', 'keterangan' => 'Bantuan Hukum'],
            ['kode' => '800.1.8', 'keterangan' => 'Status dan Kedudukan Pegawai'],
            ['kode' => '800.1.8.1', 'keterangan' => 'Status Kepegawaian'],
            ['kode' => '800.1.8.2', 'keterangan' => 'Kedudukan Kepegawaian'],
            ['kode' => '800.1.8.3', 'keterangan' => 'Keberatan Pegawai'],
            ['kode' => '800.1.8.4', 'keterangan' => 'Perselisihan/Sengketa Kepegawaian'],
            ['kode' => '800.1.9', 'keterangan' => 'Sistem Informasi Kepegawaian'],
            ['kode' => '800.1.9.1', 'keterangan' => 'Pengolahan Data dan Informasi Kepegawaian'],
            ['kode' => '800.1.9.2', 'keterangan' => 'Pengembangan Sistem Informasi Kepegawaian'],
            ['kode' => '800.1.9.3', 'keterangan' => 'Pengembangan Sistem Pengelolaan Arsip Kepegawaian Elektronik'],
            ['kode' => '800.1.9.4', 'keterangan' => 'Sistem Pengelolaan Arsip Kepegawaian Fisik'],
            ['kode' => '800.1.10', 'keterangan' => 'Pengawasan dan pengendalian'],
            ['kode' => '800.1.10.1', 'keterangan' => 'Formasi, Pengadaan dan Pasca Diklat'],
            ['kode' => '800.1.10.2', 'keterangan' => 'Kepangkatan, Pengangkatan, dan Pemberhentian Dalam Jabatan'],
            ['kode' => '800.1.10.3', 'keterangan' => 'Gaji dan Tunjangan, Kesejahteraan dan Kinerja'],
            ['kode' => '800.1.10.4', 'keterangan' => 'Kode Etik, Disiplin, Pemberhentian dan Pensiun ASN'],
            ['kode' => '800.1.10.5', 'keterangan' => 'Laporan Hasil Pengawasan dan Pengendalian'],
            ['kode' => '800.1.10.6', 'keterangan' => 'Sanggahan terhadap Permasalahan Tenaga Honorer'],
            ['kode' => '800.1.11', 'keterangan' => 'Administrasi Pegawai'],
            ['kode' => '800.1.11.1', 'keterangan' => 'Surat Perintah Dinas/Surat Tugas'],
            ['kode' => '800.1.11.2', 'keterangan' => 'Cuti Sakit'],
            ['kode' => '800.1.11.3', 'keterangan' => 'Cuti Bersalin'],
            ['kode' => '800.1.11.4', 'keterangan' => 'Cuti Tahunan'],
            ['kode' => '800.1.11.5', 'keterangan' => 'Cuti Alasan Penting'],
            ['kode' => '800.1.11.6', 'keterangan' => 'Cuti Besar'],
            ['kode' => '800.1.11.7', 'keterangan' => 'Cuti Di luar Tanggungan Negara'],
            ['kode' => '800.1.11.8', 'keterangan' => 'Karpeg/KPE/Karis/Karsu'],
            ['kode' => '800.1.11.9', 'keterangan' => 'Keanggotaan Organisasi Profesi/ Kedinasan'],
            ['kode' => '800.1.11.10', 'keterangan' => 'Laporan Pajak Penghasilan Pribadi (LP2P)'],
            ['kode' => '800.1.11.11', 'keterangan' => 'Keterangan Penerimaan Pembayaran Penghasilan Pegawai (KP4)'],
            ['kode' => '800.1.11.12', 'keterangan' => 'Daftar Urut Kepangkatan (DUK)'],
            ['kode' => '800.1.11.13', 'keterangan' => 'Pengurusan Kenaikan Gaji Berkala, Mutasi Gaji/ tunjangan'],
            ['kode' => '800.1.12', 'keterangan' => 'Kesejahteraan Pegawai'],
            ['kode' => '800.1.12.1', 'keterangan' => 'Pemeliharaan Kesehatan Pegawai'],
            ['kode' => '800.1.12.2', 'keterangan' => 'Asuransi Pegawai/BPJS'],
            ['kode' => '800.1.12.3', 'keterangan' => 'Tabungan Perumahan'],
            ['kode' => '800.1.12.4', 'keterangan' => 'Bantuan Sosial'],
            ['kode' => '800.1.12.5', 'keterangan' => 'Pakaian Dinas'],
            ['kode' => '800.1.12.6', 'keterangan' => 'Layanan Pegawai yang Meninggal Karena Dinas'],
            ['kode' => '800.1.12.7', 'keterangan' => 'Pemberian Tali Kasih'],
            ['kode' => '800.1.12.8', 'keterangan' => 'Pemberian Piagam Penghargaan dan Tanda Jasa'],
            ['kode' => '800.1.12.9', 'keterangan' => 'Olahraga dan Rekreasi'],
            ['kode' => '800.1.12.10', 'keterangan' => 'Rekam Medis'],
            ['kode' => '800.1.13', 'keterangan' => 'Administrasi Perseorangan'],
            ['kode' => '800.1.13.1', 'keterangan' => 'Pegawai Negeri Sipil (PNS)'],
            ['kode' => '800.1.13.2', 'keterangan' => 'Pegawai Pemerintah dengan Perjanjian Kerja (PPPK)'],
            ['kode' => '800.1.13.3', 'keterangan' => 'Pejabat Negara dan pejabat lainnya yang disetarakan'],
            ['kode' => '800.1.13.4', 'keterangan' => 'Sekretaris Daerah'],
            ['kode' => '800.1.13.5', 'keterangan' => 'ASN berjasa/terlibat dalam peristiwa berskala nasional'],
            ['kode' => '800.1.14', 'keterangan' => 'Penilaian Kompetensi'],
            ['kode' => '800.1.14.1', 'keterangan' => 'Penilaian Kompetensi'],
            ['kode' => '800.1.14.2', 'keterangan' => 'Hasil Penilaian Kompetensi'],
            ['kode' => '800.2', 'keterangan' => 'PENDIDIKAN DAN PELATIHAN'],
            ['kode' => '800.2.1', 'keterangan' => 'Kebijakan di bidang Pendidikan dan Pelatihan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '800.2.2', 'keterangan' => 'Pendidikan dan Pelatihan'],
            ['kode' => '800.2.2.1', 'keterangan' => 'Sistem Informasi program dan pembinaan diklat'],
            ['kode' => '800.2.2.2', 'keterangan' => 'Pedoman-pedoman kediklatan'],
            ['kode' => '800.2.2.3', 'keterangan' => 'Kurikulum-kurikulum diklat'],
            ['kode' => '800.2.2.4', 'keterangan' => 'Modul-modul diklat'],
            ['kode' => '800.2.2.5', 'keterangan' => 'Panduan fasilitator'],
            ['kode' => '800.2.2.6', 'keterangan' => 'Saran/rekomendasi penyelenggaraan diklat'],
            ['kode' => '800.2.2.7', 'keterangan' => 'Notulen sosialisasi/Rapat Koordinasi Kebijakan Diklat'],
            ['kode' => '800.2.2.8', 'keterangan' => 'Monitoring dan evaluasi program dan pembinaan diklat'],
            ['kode' => '800.2.2.9', 'keterangan' => 'Konsultasi, advokasi, asistensi diklat'],
            ['kode' => '800.2.3', 'keterangan' => 'Widyaiswara'],
            ['kode' => '800.2.3.1', 'keterangan' => 'Seleksi dan pengembangan Widyaiswara'],
            ['kode' => '800.2.3.2', 'keterangan' => 'Sertifikasi Widyaiswara'],
            ['kode' => '800.2.3.3', 'keterangan' => 'Monitoring dan evaluasi Widyaiswara'],
            ['kode' => '800.2.3.4', 'keterangan' => 'Penilaian Widyaiswara'],
            ['kode' => '800.2.3.5', 'keterangan' => 'Konsultasi, advokasi dan asistensi Widyaiswara'],
            ['kode' => '800.2.3.6', 'keterangan' => 'Sistem Informasi Pembinaan Widyaiswara'],
            ['kode' => '800.2.4', 'keterangan' => 'Penyelenggaraan Diklat'],
            ['kode' => '800.2.4.1', 'keterangan' => 'Perencanaan; peserta, pengajar, penjadwalan Penyelenggaraan Diklat'],
            ['kode' => '800.2.4.2', 'keterangan' => 'Penyelenggaraan Penyelenggaraan Diklat'],
            ['kode' => '800.2.4.3', 'keterangan' => 'Konsultasi, advokasi, asistensi penyelenggaraan diklat'],
            ['kode' => '800.2.4.4', 'keterangan' => 'Pengembangan bahan ajar dan metodologi pembelajaran'],
            ['kode' => '800.2.4.5', 'keterangan' => 'Sistem informasi diklat'],
            ['kode' => '800.2.4.6', 'keterangan' => 'Monitoring Penyelenggara Diklat'],
            ['kode' => '800.2.4.7', 'keterangan' => 'Monitoring dan evaluasi Pasca diklat'],
            ['kode' => '800.2.5', 'keterangan' => 'Alumni'],
        ];

        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
