<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi000Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            ['kode' => '000', 'keterangan' => 'UMUM'],
            ['kode' => '000.1', 'keterangan' => 'KETATAUSAHAAN DAN KERUMAHTANGGAAN'],
            ['kode' => '000.1.1', 'keterangan' => 'Telekomunikasi'],
            ['kode' => '000.1.2', 'keterangan' => 'Perjalanan Dinas Dalam Negeri'],
            ['kode' => '000.1.2.1', 'keterangan' => 'Perjalanan Dinas Kepala Daerah'],
            ['kode' => '000.1.2.2', 'keterangan' => 'Perjalanan Dinas DPRD'],
            ['kode' => '000.1.2.3', 'keterangan' => 'Perjalanan Dinas Pegawai'],
            ['kode' => '000.1.3', 'keterangan' => 'Perjalanan Dinas Luar Negeri'],
            ['kode' => '000.1.3.1', 'keterangan' => 'Perjalanan Dinas Kepala Daerah'],
            ['kode' => '000.1.3.2', 'keterangan' => 'Perjalanan Dinas DPRD'],
            ['kode' => '000.1.3.3', 'keterangan' => 'Perjalanan Dinas Pegawai'],
            ['kode' => '000.1.4', 'keterangan' => 'Penggunaan Fasilitas Kantor (antara lain: Permintaan dan penggunaan ruang, gedung, kendaraan, wisma, rumah dinas dan fasilitas kantor lainnya)'],
            ['kode' => '000.1.5', 'keterangan' => 'Rapat pimpinan antara lain: Notula/Risalah Rapat'],
            ['kode' => '000.1.6', 'keterangan' => 'Penyediaan Konsumsi'],
            ['kode' => '000.1.7', 'keterangan' => 'Pengurusan Kendaraan Dinas'],
            ['kode' => '000.1.7.1', 'keterangan' => 'Pengurusan surat-surat kendaraan dinas'],
            ['kode' => '000.1.7.2', 'keterangan' => 'Pemeliharaan dan perbaikan'],
            ['kode' => '000.1.7.3', 'keterangan' => 'Pengurusan kehilangan dan masalah kendaraan'],
            ['kode' => '000.1.8', 'keterangan' => 'Pemeliharaan Gedung, Taman dan Peralatan Kantor'],
            ['kode' => '000.1.8.1', 'keterangan' => 'Pertamanan/ Landscape'],
            ['kode' => '000.1.8.2', 'keterangan' => 'Penghijauan'],
            ['kode' => '000.1.8.3', 'keterangan' => 'Perbaikan Gedung'],
            ['kode' => '000.1.8.4', 'keterangan' => 'Perbaikan Peralatan Kantor'],
            ['kode' => '000.1.8.5', 'keterangan' => 'Perbaikan Rumah Dinas/ Wisma'],
            ['kode' => '000.1.8.6', 'keterangan' => 'Kebersihan Gedung dan Taman'],
            ['kode' => '000.1.9', 'keterangan' => 'Pengelolaan Jaringan Listrik, Air, Telepon dan Komputer'],
            ['kode' => '000.1.9.1', 'keterangan' => 'Perbaikan / Pemeliharaan'],
            ['kode' => '000.1.9.2', 'keterangan' => 'Pemasangan'],
            ['kode' => '000.1.10', 'keterangan' => 'Ketertiban dan Keamanan'],
            ['kode' => '000.1.10.1', 'keterangan' => 'Pengamanan, Penjagaan, dan Pengawalan terhadap Pejabat, Kantor dan Rumah Dinas'],
            ['kode' => '000.1.10.2', 'keterangan' => 'Laporan Ketertiban dan Keamanan'],
            ['kode' => '000.1.11', 'keterangan' => 'Administrasi Pengelolaan Parkir'],
            ['kode' => '000.1.12', 'keterangan' => 'Administrasi Pakaian Dinas Pegawai, Satpam, Petugas Kebersihan dan Pegawai lainnya'],
            ['kode' => '000.2', 'keterangan' => 'PERLENGKAPAN'],
            ['kode' => '000.2.1', 'keterangan' => 'Inventarisasi dan Penyimpanan'],
            ['kode' => '000.2.1.1', 'keterangan' => 'Data hasil inventarisasi dan penyimpanan'],
            ['kode' => '000.2.1.2', 'keterangan' => 'Laporan dan evaluasi inventarisasi dan penyimpanan'],
            ['kode' => '000.2.2', 'keterangan' => 'Pemeliharaan peralatan kantor'],
            ['kode' => '000.2.2.1', 'keterangan' => 'Data hasil pemeliharaan kantor'],
            ['kode' => '000.2.2.2', 'keterangan' => 'Laporan dan evaluasi pemeliharaan kantor'],
            ['kode' => '000.2.3', 'keterangan' => 'Distribusi'],
            ['kode' => '000.2.3.1', 'keterangan' => 'Barang habis pakai'],
            ['kode' => '000.2.3.2', 'keterangan' => 'Barang milik daerah'],
            ['kode' => '000.2.4', 'keterangan' => 'Penghapusan Barang Milik Daerah antara lain: Keputusan Pembentukan Tim, Berita Acara Penghapusan Barang Milik Daerah, Daftar Barang yang dihapuskan, Laporan Hasil Pelaksanaan Penghapusan BMD termasuk didalamnya proses lelang penghapusan'],
            ['kode' => '000.2.5', 'keterangan' => 'Pengelolaan Database Barang Milik Daerah'],
            ['kode' => '000.3', 'keterangan' => 'PENGADAAN'],
            ['kode' => '000.3.1', 'keterangan' => 'Rencana pengadaan Barang dan jasa (antara lain: : Identifikasi dan analisis kebutuhan barang/jasa, penyusunan dan penetapan rencana penganggaran pengadaan, penetapan kebijakan umum, penyusunan kerangka Acuan Kerja (KAK), Pengumuman Rencana Umum Pengadaan)'],
            ['kode' => '000.3.2', 'keterangan' => 'Pengadaan Langsung (antara lain: persiapan pemilihan penyedia, pelaksanaan pemilihan penyedia, penandatanganan kontrak, pelaksanaan kontrak)'],
            ['kode' => '000.3.3', 'keterangan' => 'Pengadaan Tidak Langsung/Lelang (antara lain: persiapan pemilihan penyedia, pelaksanaan pemilihan penyedia, penandatanganan kontrak, pelaksanaan kontrak)'],
            ['kode' => '000.3.4', 'keterangan' => 'Swakelola (antara lain: perencanaan, pelaksanaan dan evaluasi)'],
            ['kode' => '000.3.5', 'keterangan' => 'Pengolahan Sistem Informasi Pengadaan antara lain : Data base pengguna sistem informasi pengadaan barang/jasa, Data Base kontrak, Data Base Pengadaan Barang/jasa'],
            ['kode' => '000.3.6', 'keterangan' => 'Monitoring dan evaluasi pelaksanaan kebijakan dan pelaksanaan pengadaan antara lain: Laporan Hasil Monitoring, Laporan hasil evaluasi'],
            ['kode' => '000.4', 'keterangan' => 'PERPUSTAKAAN'],
            ['kode' => '000.4.1', 'keterangan' => 'Kebijakan di bidang Perpustakaan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '000.4.2', 'keterangan' => 'Deposit Bahan Pustaka'],
            ['kode' => '000.4.2.1', 'keterangan' => 'Serah Simpan Karya Cetak dan Karya Rekam'],
            ['kode' => '000.4.2.2', 'keterangan' => 'Pangkalan Data Penerbit dan Pengusaha Rekaman'],
            ['kode' => '000.4.2.3', 'keterangan' => 'Terbitan Internasional dan Regional'],
            ['kode' => '000.4.2.4', 'keterangan' => 'Pemantauan Wajib Serah Simpan Karya Cetak dan Karya Rekam'],
            ['kode' => '000.4.2.5', 'keterangan' => 'Bibliografi dan Katalog'],
            ['kode' => '000.4.3', 'keterangan' => 'Koleksi Pustaka'],
            ['kode' => '000.4.3.1', 'keterangan' => 'Pembelian'],
            ['kode' => '000.4.3.2', 'keterangan' => 'Hibah'],
            ['kode' => '000.4.3.3', 'keterangan' => 'Hadiah'],
            ['kode' => '000.4.3.4', 'keterangan' => 'Tukar Menukar'],
            ['kode' => '000.4.3.5', 'keterangan' => 'Implementasi Undang-Undang KCKR'],
            ['kode' => '000.4.3.6', 'keterangan' => 'Terbitan Internal'],
            ['kode' => '000.4.3.7', 'keterangan' => 'Pendistribusian bahan pustaka surplus'],
            ['kode' => '000.4.3.8', 'keterangan' => 'Inventarisasi koleksi (Buku Induk)'],
            ['kode' => '000.4.4', 'keterangan' => 'Pengolahan Bahan Pustaka'],
            ['kode' => '000.4.5', 'keterangan' => 'Pangkalan Data Katalog Koleksi'],
            ['kode' => '000.4.6', 'keterangan' => 'Layanan Perpustakaan'],
            ['kode' => '000.4.6.1', 'keterangan' => 'Keanggotaan'],
            ['kode' => '000.4.6.2', 'keterangan' => 'Peminjaman'],
            ['kode' => '000.4.6.3', 'keterangan' => 'Pengembangan gemar baca'],
            ['kode' => '000.4.7', 'keterangan' => 'Kerjasama Perpustakaan'],
            ['kode' => '000.4.7.1', 'keterangan' => 'MoU'],
            ['kode' => '000.4.7.2', 'keterangan' => 'Perjanjian kerjasama'],
            ['kode' => '000.4.7.3', 'keterangan' => 'Partisipasi organisasi profesi dan kerjasama internasional'],
            ['kode' => '000.4.8', 'keterangan' => 'Pengembangan Implementasi Teknologi Informasi Perpustakaan'],
            ['kode' => '000.4.8.1', 'keterangan' => 'Pengembangan situs web'],
            ['kode' => '000.4.8.2', 'keterangan' => 'Pengembangan kemas ulang informasi multimedia'],
            ['kode' => '000.4.8.3', 'keterangan' => 'Pengembangan program aplikasi perpustakaan'],
            ['kode' => '000.4.8.4', 'keterangan' => 'Pengembangan pangkalan data kepustakaan digital'],
            ['kode' => '000.4.9', 'keterangan' => 'Pangkalan Data Layanan Perpustakaan'],
            ['kode' => '000.4.10', 'keterangan' => 'Konservasi'],
            ['kode' => '000.4.10.1', 'keterangan' => 'Perawatan Bahan Perpustakaan'],
            ['kode' => '000.4.10.2', 'keterangan' => 'Perbaikan Bahan Perpustakaan'],
            ['kode' => '000.4.10.3', 'keterangan' => 'Penjilidan Bahan Perpustakaan'],
            ['kode' => '000.4.11', 'keterangan' => 'Reprografi (Mikrofilm, Reproduksi Foto)'],
            ['kode' => '000.4.12', 'keterangan' => 'Transformasi Digital'],
            ['kode' => '000.4.13', 'keterangan' => 'Kurasi Digital'],
            ['kode' => '000.4.14', 'keterangan' => 'Pengembangan Perpustakaan'],
            ['kode' => '000.4.14.1', 'keterangan' => 'Perpustakaan Umum'],
            ['kode' => '000.4.14.2', 'keterangan' => 'Perpustakaan Khusus'],
            ['kode' => '000.4.14.3', 'keterangan' => 'Perpustakaan Sekolah'],
            ['kode' => '000.4.14.4', 'keterangan' => 'Perpustakaan Perguruan Tinggi'],
            ['kode' => '000.5', 'keterangan' => 'KEARSIPAN'],
            ['kode' => '000.5.1', 'keterangan' => 'Kebijakan di bidang kearsipan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '000.5.2', 'keterangan' => 'Pembinaan Kearsipan'],
            ['kode' => '000.5.2.1', 'keterangan' => 'Pengembangan Profesi Arsiparis, antara lain Formasi Jabatan Arsiparis, Analisis Kebutuhan Arsiparis'],
            ['kode' => '000.5.2.2', 'keterangan' => 'Bimbingan Konsultasi Arsiparis'],
            ['kode' => '000.5.2.3', 'keterangan' => 'Penilaian Arsiparis'],
            ['kode' => '000.5.2.4', 'keterangan' => 'Pemilihan Arsiparis Teladan, antara lain Berkas Penyelenggaraan Pemilihan Arsiparis Teladan, Berkas Penetapan Arsiparis Teladan'],
            ['kode' => '000.5.2.5', 'keterangan' => 'Data Base Arsiparis'],
            ['kode' => '000.5.2.6', 'keterangan' => 'Bimbingan Konsultasi Kearsipan'],
            ['kode' => '000.5.2.7', 'keterangan' => 'Supervisi dan Evaluasi, antara lain: Perencaan Supervisi dan Evaluasi, Pelaksanaan Supervisi dan Evaluasi, Laporan Hasil Supervisi dan Evaluasi'],
            ['kode' => '000.5.2.8', 'keterangan' => 'Data Base Bimbingan dan Konsultasi dan Supervisi'],
            ['kode' => '000.5.2.9', 'keterangan' => 'Fasilitasi Kearsipan, antara lain: Fasilitasi SDM Kearsipan, Fasilitasi Prasarana dan Sarana Kearsipan'],
            ['kode' => '000.5.2.10', 'keterangan' => 'Lembaga/Unit Kearsipan Teladan, antara lain: Berkas Penyelenggaraan Pemilihan Lembaga/Unit Kearsipan, Berkas Penetapan Lembaga/Unit Kearsipan Teladan'],
            ['kode' => '000.5.2.11', 'keterangan' => 'Jadwal Retensi Arsip, antara lain: Berkas Usulan Persetujuan JRA, Surat Persetujuan JRA dari Kepala ANRI'],
            ['kode' => '000.5.3', 'keterangan' => 'Pengelolaan Arsip Dinamis'],
            ['kode' => '000.5.3.1', 'keterangan' => 'Penciptaan (antara lain: Buku Registrasi Naskah Masuk dan Keluar, Buku Agenda, Kartu Kendali, Lembar Pengantar/Buku Ekspedisi)'],
            ['kode' => '000.5.3.2', 'keterangan' => 'Pemberkasan Arsip Aktif (antara lain: daftar berkas dan daftar isi berkas)'],
            ['kode' => '000.5.3.3', 'keterangan' => 'Penataan Arsip Inaktif (antara lain: daftar arsip inaktif, daftar arsip inaktif tematik)'],
            ['kode' => '000.5.3.4', 'keterangan' => 'Penggunaan (antara lain: daftar arsip dinamis berdasarkan sistem klasifikasi keamanan dan akses arsip dinamis, bukti peminjaman arsip)'],
            ['kode' => '000.5.3.5', 'keterangan' => 'Autentikasi Arsip Dinamis (antara lain: pembuktian autentisitas, pendapat tenaga ahli, pengujian, penetapan autentisitas arsip dinamis)'],
            ['kode' => '000.5.4', 'keterangan' => 'Program Arsip Vital (antara lain: Identifikasi Arsip Vital, Perlindungan dan Pengamanan Arsip Vital, Penyelamatan Arsip Vital dan Pemulihan Arsip Vital)'],
            ['kode' => '000.5.5', 'keterangan' => 'Pengelolaan Arsip Terjaga (antara lain: Daftar Identifikasi Arsip Terjaga, Daftar Berkas Arsip Terjaga, Daftar Isi Berkas Arsip Terjaga, Surat Penetapan Autentifikasi Arsip Terjaga, Surat Penyerahan Arsip Terjaga, Daftar Salinan Autentik Arsip Terjaga, Berita Acara Penyerahan Salinan Autentik Arsip Terjaga'],
            ['kode' => '000.5.6', 'keterangan' => 'Pemusnahan Arsip'],
            ['kode' => '000.5.6.1', 'keterangan' => 'Pemindahan Arsip (antara lain: Berita Acara Pemindahan, Daftar Arsip yang dipindahkan)'],
            ['kode' => '000.5.6.2', 'keterangan' => 'Pemusnahan Arsip (antara lain: SK Penetapan Panitia Penilai Arsip, Pertimbangan Panitia Penilai, Permintaan Persetujuan Kepala ANRI untuk pemusnahan arsip dengan retensi sekurang-kurangnya 10 Tahun atau Persetujuan Kepala Daerah selaku Pimpinan Pencipta Arsip untuk pemusnahan arsip dengan retensi di bawah 10 Tahun, Penetapan Arsip Yang Dimusnahkan, Berita Acara Pemusnahan Arsip, Daftar Arsip Yang Dimusnahkan.'],
            ['kode' => '000.5.6.3', 'keterangan' => 'Penyerahan Arsip Statis (antara lain: Pembentukan panitia penilai, Notulen rapat panitia, Surat pertimbangan panitia penilai, Surat persetujuan dari Kepala Lembaga Kearsipan, Surat pernyataan autentik, terpercaya, utuh, dan digunakan dari pencipta arsip, Keputusan Penetapan Penyerahan, Berita Acara Penyerahan Arsip, Daftar Arsip yang diserahkan)'],
            ['kode' => '000.5.7', 'keterangan' => 'Alih Media Arsip (antara lain: Kebijakan alih media, Autentikasi, Berita Acara, Daftar Arsip yang alih mediakan)'],
            ['kode' => '000.5.8', 'keterangan' => 'Data Base Pengelolaan Arsip Dinamis'],
            ['kode' => '000.5.8.1', 'keterangan' => 'Data Base Pengelolaan Arsip Aktif'],
            ['kode' => '000.5.8.2', 'keterangan' => 'Data Base Pengelolaan Arsip Inaktif'],
            ['kode' => '000.5.9', 'keterangan' => 'Pengelolaan Arsip Statis'],
            ['kode' => '000.5.9.1', 'keterangan' => 'Akuisisi (antara lain: Monitoring fisik dan daftar, Verifikasi terhadap daftar arsip, Menetapkan status arsip statis, Persetujuan untuk Penyerahan, Penetapan arsip yang diserahkan Berita Acara Penyerahan, Daftar Arsip yang diserahkan'],
            ['kode' => '000.5.9.2', 'keterangan' => 'Penghargaan dan Imbalan'],
            ['kode' => '000.5.9.3', 'keterangan' => 'Sejarah Lisan (antara lain: Administrasi kegiatan, Berita Acara Wawancara Sejarah Lisan, Laporan Kegiatan, Hasil Wawancara (Kaser/CD/media lain sesuai perkembangan TI, dan Transkip)'],
            ['kode' => '000.5.9.4', 'keterangan' => 'Daftar Pencarian Arsip Statis (antara lain: pengumuman, akuisisi daftar pencarian arsip statis)'],
            ['kode' => '000.5.9.5', 'keterangan' => 'Menyusun Sarana Bantu Temu Balik (antara lain: daftar arsip statis, inventaris arsip statis, guide)'],
            ['kode' => '000.5.9.6', 'keterangan' => 'Preservasi Preventif (antara lain: penyimpanan, pengendalian hama terpadu, reproduksi (alih media)'],
            ['kode' => '000.5.9.7', 'keterangan' => 'Preservasi Kuratif'],
            ['kode' => '000.5.9.8', 'keterangan' => 'Autentikasi Arsip Statis (antara lain: pembuktian autentisitas, pendapat tenaga ahli, pengujian, penetapan autentitas arsip statis)'],
            ['kode' => '000.5.9.9', 'keterangan' => 'Akses Arsip Statis (antara lain: Layanan arsip, Penerbitan naskah sumber)'],
            ['kode' => '000.5.10', 'keterangan' => 'Jasa Kearsipan (antara lain konsultasi kearsipan, manual kearsipan, penataan arsip, otomasi kearsipan, penyimpanan arsip, perawatan dan pemeliharaan arsip)'],
            ['kode' => '000.5.11', 'keterangan' => 'Pengelolaan SIKN dan JIKN'],
            ['kode' => '000.5.12', 'keterangan' => 'Pelindungan dan penyelamatan arsip akibat bencana'],
            ['kode' => '000.5.13', 'keterangan' => 'Penyelamatan arsip Perangkat Daerah digabung dan/atau dibubarkan'],
            ['kode' => '000.5.14', 'keterangan' => 'Penerbitan izin penggunaan arsip yang bersifat tertutup'],
            ['kode' => '000.5.15', 'keterangan' => 'Pengawasan Kearsipan'],
            ['kode' => '000.5.15.1', 'keterangan' => 'Pengawasan Kearsipan Internal'],
            ['kode' => '000.5.15.2', 'keterangan' => 'Pengawasan Kearsipan Eksternal'],
            ['kode' => '000.5.15.3', 'keterangan' => 'Sanksi'],
            ['kode' => '000.6', 'keterangan' => 'PERSANDIAN'],
            ['kode' => '000.6.1', 'keterangan' => 'Kebijakan di bidang Persandian yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '000.6.2', 'keterangan' => 'Pengamanan persandian'],
            ['kode' => '000.6.2.1', 'keterangan' => 'Pengamanan sinyal: teknik sandi dan kripto'],
            ['kode' => '000.6.2.2', 'keterangan' => 'Analisis sinyal: teknik sandi dan kripto'],
            ['kode' => '000.6.2.3', 'keterangan' => 'Materiil sandi: sistem dan peralatan'],
            ['kode' => '000.6.3', 'keterangan' => 'Pengkajian persandian: Kriptografi, Peralatan Sandi, Komunikasi Sandi'],
            ['kode' => '000.6.3.1', 'keterangan' => 'Perencanaan Pengkajian'],
            ['kode' => '000.6.3.2', 'keterangan' => 'Administrasi Pengkajian'],
            ['kode' => '000.6.3.3', 'keterangan' => 'Pelaksanaan'],
            ['kode' => '000.6.3.4', 'keterangan' => 'Pelaporan'],
            ['kode' => '000.6.4', 'keterangan' => 'Pembinaan dan Pengendalian Persandian'],
            ['kode' => '000.6.4.1', 'keterangan' => 'Sumber Daya Manusia (SDM)'],
            ['kode' => '000.6.4.2', 'keterangan' => 'Jaring Komunikasi'],
            ['kode' => '000.6.5', 'keterangan' => 'Layanan Sertifikasi Elektronik'],
            ['kode' => '000.6.5.1', 'keterangan' => 'Perencanaan dan Administrasi'],
            ['kode' => '000.6.5.2', 'keterangan' => 'Pelaksanaan Verifikasi'],
            ['kode' => '000.6.5.3', 'keterangan' => 'Pelaksanaan Perjanjian Kerjasama'],
            ['kode' => '000.6.5.4', 'keterangan' => 'Penyesuaian Sistem dan Testing'],
            ['kode' => '000.6.5.5', 'keterangan' => 'Pelaksanaan Bimbingan Teknis Pengguna'],
            ['kode' => '000.6.5.6', 'keterangan' => 'Pelaksanaan Penerbitan Sertifikat Elektronik'],
            ['kode' => '000.6.5.7', 'keterangan' => 'Pelaporan'],
            ['kode' => '000.7', 'keterangan' => 'PERENCANAAN PEMBANGUNAN'],
            ['kode' => '000.7.1', 'keterangan' => 'Musyawarah Perencanaan Pembangunan/Musrenbang'],
            ['kode' => '000.7.1.1', 'keterangan' => 'Musrenbang Provinsi'],
            ['kode' => '000.7.1.2', 'keterangan' => 'Musrenbang Nasional'],
            ['kode' => '000.7.1.3', 'keterangan' => 'Musrenbang Kab/Kota'],
            ['kode' => '000.7.1.4', 'keterangan' => 'Musrenbang Kecamatan'],
            ['kode' => '000.7.1.5', 'keterangan' => 'Musrenbang Kelurahan'],
            ['kode' => '000.7.1.6', 'keterangan' => 'Musrenbang Desa'],
            ['kode' => '000.7.2', 'keterangan' => 'Perencanaan Pembangunan Daerah'],
            ['kode' => '000.7.2.1', 'keterangan' => 'Rencana Pembangunan Jangka Panjang'],
            ['kode' => '000.7.2.2', 'keterangan' => 'Rencana Pembangunan Jangka Menengah'],
            ['kode' => '000.7.2.3', 'keterangan' => 'Rencana Anggaran Daerah'],
            ['kode' => '000.7.2.4', 'keterangan' => 'Rencana Pembangunan Tahunan'],
            ['kode' => '000.7.2.5', 'keterangan' => 'Rencana Pembentukan Satuan Kerja Perangkat Daerah'],
            ['kode' => '000.7.2.6', 'keterangan' => 'Program kerja tahunan'],
            ['kode' => '000.7.2.7', 'keterangan' => 'Penetapan / Kontrak Kinerja'],
            ['kode' => '000.7.2.8', 'keterangan' => 'Laporan Berkala'],
            ['kode' => '000.7.2.9', 'keterangan' => 'Laporan Insidential'],
            ['kode' => '000.7.2.10', 'keterangan' => 'Evaluasi Program'],
            ['kode' => '000.7.3', 'keterangan' => 'Koordinasi dan Sinkronisasi Perencanaan Pembangunan'],
            ['kode' => '000.7.4', 'keterangan' => 'Konsultasi Perencanaan Pembangunan'],
            ['kode' => '000.7.5', 'keterangan' => 'Pemantauan, Evaluasi, Penilaian, dan Pelaporan Perencanaan Pembangunan'],
            ['kode' => '000.7.6', 'keterangan' => 'Aksi Strategis Daerah'],
            ['kode' => '000.7.6.1', 'keterangan' => 'Rancangan awal perencanaan aksi strategi daerah'],
            ['kode' => '000.7.6.2', 'keterangan' => 'Rapat pembahasan rancangan awal dengan Perangkat Daerah'],
            ['kode' => '000.7.6.3', 'keterangan' => 'Sosisalisasi dengan Perangkat Daerah'],
            ['kode' => '000.7.6.4', 'keterangan' => 'Rancangan akhir perencanaan aksi strategi daerah'],
            ['kode' => '000.7.6.5', 'keterangan' => 'Penerapan perencaan aksi strategi daerah'],
            ['kode' => '000.7.7', 'keterangan' => 'Perencanaan Pendanaan Pembangunan'],
            ['kode' => '000.7.7.1', 'keterangan' => 'Pendanaan Nasional dan Hibah'],
            ['kode' => '000.7.7.2', 'keterangan' => 'Pendanaan Daerah'],
            ['kode' => '000.7.7.3', 'keterangan' => 'Kerjasama Pembangunan Nasional'],
            ['kode' => '000.7.7.4', 'keterangan' => 'Surat Berharga Syariah Negara'],
            ['kode' => '000.7.7.5', 'keterangan' => 'Pendanaan On Top atau Inisiatif Baru'],
            ['kode' => '000.8', 'keterangan' => 'ORGANISASI DAN TATA LAKSANA'],
            ['kode' => '000.8.1', 'keterangan' => 'Struktur Organisasi di lingkungan Pemerintahan Daerah Kab/Kota'],
            ['kode' => '000.8.1.1', 'keterangan' => 'Pembentukan'],
            ['kode' => '000.8.1.2', 'keterangan' => 'Pengubahan'],
            ['kode' => '000.8.1.3', 'keterangan' => 'Pembubaran'],
            ['kode' => '000.8.2', 'keterangan' => 'Uraian Jabatan'],
            ['kode' => '000.8.2.1', 'keterangan' => 'Analisa Jabatan'],
            ['kode' => '000.8.2.2', 'keterangan' => 'Analisa Beban Kerja'],
            ['kode' => '000.8.3', 'keterangan' => 'Ketatalaksanaan'],
            ['kode' => '000.8.3.1', 'keterangan' => 'Proses Bisnis'],
            ['kode' => '000.8.3.2', 'keterangan' => 'Standar Pelayanan'],
            ['kode' => '000.8.3.3', 'keterangan' => 'Standar Operasional Prosedur'],
            ['kode' => '000.8.3.4', 'keterangan' => 'Pelayanan Publik'],
            ['kode' => '000.8.4', 'keterangan' => 'Standar Kompetensi jabatan struktural dan fungsional'],
            ['kode' => '000.8.5', 'keterangan' => 'Evaluasi Kelembagaan'],
            ['kode' => '000.8.6', 'keterangan' => 'Koordinasi Penguatan Reformasi dan Birokrasi'],
            ['kode' => '000.8.6.1', 'keterangan' => 'Budaya Kerja'],
            ['kode' => '000.8.6.2', 'keterangan' => 'Penilaian Mandiri Reformasi Birokrasi'],
            ['kode' => '000.8.6.3', 'keterangan' => 'Akuntabilitas Kinerja Instansi Pemerintah'],
            ['kode' => '000.9', 'keterangan' => 'PENELITIAN, PENGKAJIAN, DAN PENGEMBANGAN'],
            ['kode' => '000.9.1', 'keterangan' => 'Kebijakan di bidang penelitian, pengkajian, pengembangan yang dilakukan oleh pemerintah daerah'],
            ['kode' => '000.9.2', 'keterangan' => 'Penelitian, Pengkajian dan Pengembangan meliputi: rencana kerja, administrasi penelitian, pelaksanaan, hasil penelitian/pengkajian/rekomendasi'],
            ['kode' => '000.9.3', 'keterangan' => 'Sosialisasi dan desiminasi hasil penelitian, hasil pengkajian dan pengembangan'],
            ['kode' => '000.9.4', 'keterangan' => 'Bimbingan teknis penelitian, pengkajian dan pengembangan'],
            ['kode' => '000.9.5', 'keterangan' => 'Forum komunikasi penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '000.9.6', 'keterangan' => 'Data dan informasi hasil penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '000.9.6.1', 'keterangan' => 'Data'],
            ['kode' => '000.9.6.2', 'keterangan' => 'Statistik'],
            ['kode' => '000.9.6.3', 'keterangan' => 'Jurnal Hasil Penelitian/Pengkajian'],
            ['kode' => '000.9.7', 'keterangan' => 'Master proceeding/ jurnal penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['kode' => '000.9.8', 'keterangan' => 'Hak atas kekayaan intelektual (HaKI)'],
            ['kode' => '000.9.9', 'keterangan' => 'Evaluasi Pelaksanaan Kebijakan'],
            ['kode' => '000.9.10', 'keterangan' => 'Seminar, lokakarya, mulakarya, workshop'],
        ];
        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
