<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi400P2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode' => '400.7.22.1', 'keterangan' => 'Surat keterangan'],
            ['kode' => '400.7.22.2', 'keterangan' => 'Sertifikasi dan perijinan'],
            ['kode' => '400.7.23', 'keterangan' => 'Penanggulangan Krisis Kesehatan'],
            ['kode' => '400.7.23.1', 'keterangan' => 'Pencegahan, mitigasi dan kesiapsiagaan'],
            ['kode' => '400.7.23.2', 'keterangan' => 'Tanggap darurat dan pemulihan'],
            ['kode' => '400.7.23.3', 'keterangan' => 'Pemantauan dan informasi'],
            ['kode' => '400.7.23.4', 'keterangan' => 'Penanggulangan krisis kesehatan dalam bidang pengendalian penyakit dan penyehatan'],
            ['kode' => '400.7.23.5', 'keterangan' => 'Pelayanan kesehatan reproduksi situasi bencana'],
            ['kode' => '400.7.24', 'keterangan' => 'Pengembangan dan Jaminan Kesehatan'],
            ['kode' => '400.7.24.1', 'keterangan' => 'Tersedianya data NHA setiap tahun'],
            ['kode' => '400.7.24.2', 'keterangan' => 'Tersedianya dokumen teknis penguatan pelaksanaan JKN'],
            ['kode' => '400.7.25', 'keterangan' => 'Intelegensia Kesehatan'],
            ['kode' => '400.7.25.1', 'keterangan' => 'Pemeliharaan dan peningkatan kemampuan intelegensia kesehatan'],
            ['kode' => '400.7.25.2', 'keterangan' => 'Penanggulangan masalah intelegensia kesehatan'],
            ['kode' => '400.7.26', 'keterangan' => 'Kesehatan Haji'],
            ['kode' => '400.7.26.1', 'keterangan' => 'Pelayanan dan pendayagunaan sumber daya kesehatan haji'],
            ['kode' => '400.7.26.2', 'keterangan' => 'Peningkatan kesehatan dan pengendalian faktor risiko kesehatan haji'],
            ['kode' => '400.7.27', 'keterangan' => 'Promosi Kesehatan'],
            ['kode' => '400.7.27.1', 'keterangan' => 'Sarana Promosi Kesehatan'],
            ['kode' => '400.7.27.2', 'keterangan' => 'Pembinaan advokasi dan kemitraan serta pemberdayaan peran'],
            ['kode' => '400.7.27.3', 'keterangan' => 'Pengembangan pesan promosi kesehatan'],
            ['kode' => '400.7.27.4', 'keterangan' => 'Hari Kesehatan'],
            ['kode' => '400.7.28', 'keterangan' => 'Data dan Informasi'],
            ['kode' => '400.7.28.1', 'keterangan' => 'Statistik kesehatan'],
            ['kode' => '400.7.28.2', 'keterangan' => 'Analisis dan diseminasi informasi'],
            ['kode' => '400.7.28.3', 'keterangan' => 'Pengembangan sistem informasi dan bank data kesehatan'],
            ['kode' => '400.7.29', 'keterangan' => 'Pengawasan Obat Tradisional, Kosmetik dan Produk Komplimen'],
            ['kode' => '400.7.29.1', 'keterangan' => 'Penilaian obat tradisional, suplemen makanan dan kosmetik'],
            ['kode' => '400.7.29.2', 'keterangan' => 'Standardisasi obat tradisional, kosmetik dan produk komplimen'],
            ['kode' => '400.7.29.3', 'keterangan' => 'Inspeksi dan sertifikasi obat tradisional, kosmetik dan produk komplimen'],
            ['kode' => '400.7.29.4', 'keterangan' => 'Obat Asli Indonesia'],
            ['kode' => '400.7.30', 'keterangan' => 'Pengawasan Keamanan Pangan dan Bahan Berbahaya'],
            ['kode' => '400.7.30.1', 'keterangan' => 'Penilaian keamanan pangan'],
            ['kode' => '400.7.30.2', 'keterangan' => 'Standardisasi produk pangan'],
            ['kode' => '400.7.30.3', 'keterangan' => 'Inspeksi dan sertifikasi produk pangan'],
            ['kode' => '400.7.30.4', 'keterangan' => 'Surveilan dan penyuluhan keamanan pangan'],
            ['kode' => '400.7.30.5', 'keterangan' => 'Pengawasan produk dan bahan berbahaya'],
            ['kode' => '400.7.31', 'keterangan' => 'Rekam Medis'],
            ['kode' => '400.8', 'keterangan' => 'AGAMA DAN KEPERCAYAAN'],
            ['kode' => '400.8.1', 'keterangan' => 'Kebijakan di bidang Agama dan Kepercayaan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.8.2', 'keterangan' => 'Fasilitasi'],
            ['kode' => '400.8.2.1', 'keterangan' => 'Data Forum Komunikasi Umat Beragama (FKUB) Prov/Kab/Kota'],
            ['kode' => '400.8.2.2', 'keterangan' => 'Pelaksanaan Kerukunan Umat Beragama dan Kepercayaan'],
            ['kode' => '400.8.2.3', 'keterangan' => 'Pelestarian Nilai-Nilai Keagamaan dan Kepercayan'],
            ['kode' => '400.8.2.4', 'keterangan' => 'Kasus Keagamaan'],
            ['kode' => '400.8.2.5', 'keterangan' => 'Kasus Aliran Keagamaan'],
            ['kode' => '400.8.3', 'keterangan' => 'Pembinaan Kepercayaan Kepada Tuhan YME'],
            ['kode' => '400.8.3.1', 'keterangan' => 'Kelembagaan dan kepercayaan'],
            ['kode' => '400.8.3.2', 'keterangan' => 'Pembinaan Kerukunan Hidup Beragama'],
            ['kode' => '400.8.3.3', 'keterangan' => 'Komunitas Kepercayaan'],
            ['kode' => '400.8.3.4', 'keterangan' => 'Pengetahuan dan ekspresi budaya tradisional'],
            ['kode' => '400.8.3.5', 'keterangan' => 'Lingkungan Budaya dan Pranata Sosial'],
            ['kode' => '400.9', 'keterangan' => 'SOSIAL'],
            ['kode' => '400.9.1', 'keterangan' => 'Kebijakan di bidang Sosial yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.9.2', 'keterangan' => 'Kesejahteraan Sosial Anak'],
            ['kode' => '400.9.2.1', 'keterangan' => 'Kesejahteraan sosial anak balita'],
            ['kode' => '400.9.2.2', 'keterangan' => 'Kesejahteraan sosial anak terlantar'],
            ['kode' => '400.9.2.3', 'keterangan' => 'Kesejahteraan sosial anak berhadapan dengan hukum'],
            ['kode' => '400.9.2.4', 'keterangan' => 'Kesejahteraan sosial anak dengan kecatatan'],
            ['kode' => '400.9.2.5', 'keterangan' => 'Kesejahteraan sosial anak yang membutuhkan perlindungan khusus'],
            ['kode' => '400.9.3', 'keterangan' => 'Rehabilitasi Sosial'],
            ['kode' => '400.9.3.1', 'keterangan' => 'Rehabilitasi sosial orang dengan kecacatan tubuh dan bekas penderita penyakit kronis, netra dan rungu wicara, mental'],
            ['kode' => '400.9.3.2', 'keterangan' => 'Kelembagaan dan advokasi social'],
            ['kode' => '400.9.3.3', 'keterangan' => 'Asistensi dan pemeliharaan kesejahteraan sosial'],
            ['kode' => '400.9.4', 'keterangan' => 'Rehabilitasi Sosial Tuna Sosial'],
            ['kode' => '400.9.4.1', 'keterangan' => 'Gelandangan, pengemis dan pemulung'],
            ['kode' => '400.9.4.2', 'keterangan' => 'Tuna susila dan korban traffiking perempuan'],
            ['kode' => '400.9.4.3', 'keterangan' => 'Warga binaan lembaga pemasyarakatan meliputi penyiapan, reintegrasi'],
            ['kode' => '400.9.4.4', 'keterangan' => 'Pelayanan sosial orang dengan HIV / AIDS dan kelompok minoritas'],
            ['kode' => '400.9.5', 'keterangan' => 'Rehabilitasi Sosial Korban Penyalahgunaan NAPZA'],
            ['kode' => '400.9.6', 'keterangan' => 'Pelayanan sosial lanjut usia'],
            ['kode' => '400.9.6.1', 'keterangan' => 'Pelayanan sosial dalam dan luar panti'],
            ['kode' => '400.9.6.2', 'keterangan' => 'Pengembangan kelembagaan meliputi pembinaan lembaga, kerjasama lembaga'],
            ['kode' => '400.9.6.3', 'keterangan' => 'Advokasi dan pelayanan sosial kedaruratan'],
            ['kode' => '400.9.7', 'keterangan' => 'Pengumpulan dan Pengelolaan sumber dana bantuan sosial'],
            ['kode' => '400.9.8', 'keterangan' => 'Perlindungan Sosial Korban Tindak Kekerasan dan Pekerja Migran'],
            ['kode' => '400.9.9', 'keterangan' => 'Perilindungan Sosial Korban Bencana Sosial'],
            ['kode' => '400.9.9.1', 'keterangan' => 'Ketahanan sosial masyarakat meliputi keserasian sosial, penguatan Sumber Daya'],
            ['kode' => '400.9.9.2', 'keterangan' => 'Tanggap darurat meliputi bantuan darurat, advokasi sosial'],
            ['kode' => '400.9.9.3', 'keterangan' => 'Pemulihan sosial meliputi penguatan sosial, reintegrasi sosial'],
            ['kode' => '400.9.9.4', 'keterangan' => 'Kerjasama meliputi kerjasama pemerintah, kerjasama non pemerintah'],
            ['kode' => '400.9.10', 'keterangan' => 'Perlindungan Sosial Korban Bencana Alam'],
            ['kode' => '400.9.10.1', 'keterangan' => 'Kesiapsiagaan dan mitigasi'],
            ['kode' => '400.9.10.2', 'keterangan' => 'Tanggap darurat meliputi bantuan darurat, advokasi sosial'],
            ['kode' => '400.9.10.3', 'keterangan' => 'Pemulihan sosial dan penguatan sosial'],
            ['kode' => '400.9.10.4', 'keterangan' => 'Kerjasama'],
            ['kode' => '400.9.11', 'keterangan' => 'Jaminan Sosial'],
            ['kode' => '400.9.11.1', 'keterangan' => 'Seleksi dan vrifikasi'],
            ['kode' => '400.9.11.2', 'keterangan' => 'Asuransi kesejahteraan sosial meliputi kelembagaan, pengelolaan premi'],
            ['kode' => '400.9.11.3', 'keterangan' => 'Bantuan langsung dan tunjangan berkelanjutan meliputi pendampingan dan penyaluran'],
            ['kode' => '400.9.11.4', 'keterangan' => 'Kerjasama'],
            ['kode' => '400.9.12', 'keterangan' => 'Pemberdayaan keluarga dan kelembagaan Sosial'],
            ['kode' => '400.9.12.1', 'keterangan' => 'Ketahanan keluarga'],
            ['kode' => '400.9.12.2', 'keterangan' => 'Asistensi keluarga dan pemberdayaan perempuan'],
            ['kode' => '400.9.12.3', 'keterangan' => 'Tenaga kesejahteraan sosial masyarakat dan organisasi sosial'],
            ['kode' => '400.9.12.4', 'keterangan' => 'Kemitraan dunia usaha'],
            ['kode' => '400.9.12.5', 'keterangan' => 'Karang taruna meliputi kelembagaan, pengembangan kapasitas'],
            ['kode' => '400.9.13', 'keterangan' => 'Pemberdayaan komunitas adat terpencil'],
            ['kode' => '400.9.13.1', 'keterangan' => 'Persiapan pemberdayaan'],
            ['kode' => '400.9.13.2', 'keterangan' => 'Pemberdayaan sumber daya manusia'],
            ['kode' => '400.9.13.3', 'keterangan' => 'Penggalian dan pengembangan potensi'],
            ['kode' => '400.9.13.4', 'keterangan' => 'Keserasian dan penguatan komunitas adat terpencil'],
            ['kode' => '400.9.13.5', 'keterangan' => 'Kerjasama kelembagaan'],
            ['kode' => '400.9.14', 'keterangan' => 'Penanggulangan Kemiskinan Perkotaan dan Perdesaan'],
            ['kode' => '400.9.14.1', 'keterangan' => 'Identifikasi dan analisis'],
            ['kode' => '400.9.14.2', 'keterangan' => 'Pengembangan kapasitas'],
            ['kode' => '400.9.14.3', 'keterangan' => 'Penataan sosial lingkungan kumuh'],
            ['kode' => '400.9.14.4', 'keterangan' => 'Advokasi sosial dan pengembangan aksesibilitas'],
            ['kode' => '400.9.14.5', 'keterangan' => 'Bantuan Langsung'],
            ['kode' => '400.9.14.6', 'keterangan' => 'Kerjasama Kelembagaan'],
            ['kode' => '400.9.15', 'keterangan' => 'Kepahlawanan, Keperintisan dan Kesetiakawanan Sosial'],
            ['kode' => '400.9.15.1', 'keterangan' => 'Penghargaan dan kesejahteraan keluarga pahlawan'],
            ['kode' => '400.9.15.2', 'keterangan' => 'Pelestarian nilai-nilai kepahlawanan dan keperintisan'],
            ['kode' => '400.9.15.3', 'keterangan' => 'Pengembangan kesetiakawanan sosial'],
            ['kode' => '400.9.15.4', 'keterangan' => 'Pengelolaan taman makam pahlawan'],
            ['kode' => '400.10', 'keterangan' => 'PEMBERDAYAAN MASYARAKAT DESA'],
            ['kode' => '400.10.1', 'keterangan' => 'Kebijakan di bidang Pemberdayaan Masyarakat Desa yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.10.2', 'keterangan' => 'Pemerintahan Desa dan Kelurahan'],
            ['kode' => '400.10.2.1', 'keterangan' => 'Fasilitasi Pengembangan Desa dan Kelurahan'],
            ['kode' => '400.10.2.2', 'keterangan' => 'Administrasi Pemerintahan Desa dan Kelurahan'],
            ['kode' => '400.10.2.3', 'keterangan' => 'Fasilitasi Permusyawaratan Desa'],
            ['kode' => '400.10.2.4', 'keterangan' => 'Fasilitasi Pengelolaan Keuangan dan Aset Desa'],
            ['kode' => '400.10.2.5', 'keterangan' => 'Pengembangan Kapasitas Desa'],
            ['kode' => '400.10.3', 'keterangan' => 'Kelembagaan dan Pelatihan Masyarakat'],
            ['kode' => '400.10.3.1', 'keterangan' => 'Lembaga Masyarakat'],
            ['kode' => '400.10.3.2', 'keterangan' => 'Pembangunan Partisipatif'],
            ['kode' => '400.10.3.3', 'keterangan' => 'Pendataan Potensi Masyarakat'],
            ['kode' => '400.10.3.4', 'keterangan' => 'Pengembangan Kawasan Perdesaan'],
            ['kode' => '400.10.3.5', 'keterangan' => 'Pelatihan Masyarakat'],
            ['kode' => '400.10.4', 'keterangan' => 'Pemberdayaan Adat dan Sosial Budaya Masyarakat'],
            ['kode' => '400.10.4.1', 'keterangan' => 'Budaya Nusantara'],
            ['kode' => '400.10.4.2', 'keterangan' => 'Pemberdayaan Perempuan'],
            ['kode' => '400.10.4.3', 'keterangan' => 'Pemberdayaan dan Kesejahteraan Keluarga'],
            ['kode' => '400.10.4.4', 'keterangan' => 'Kesejahteraan Sosial'],
            ['kode' => '400.10.4.5', 'keterangan' => 'Tenaga Kerja Perdesaan'],
            ['kode' => '400.10.5', 'keterangan' => 'Usaha Ekonomi Masyarakat'],
            ['kode' => '400.10.5.1', 'keterangan' => 'Usaha Pertanian dan Pangan'],
            ['kode' => '400.10.5.2', 'keterangan' => 'Usaha Perkreditan dan Simpan Pinjam'],
            ['kode' => '400.10.5.3', 'keterangan' => 'Produksi dan Pemasaran'],
            ['kode' => '400.10.5.4', 'keterangan' => 'Usaha Ekonomi dan Keluarga'],
            ['kode' => '400.10.5.5', 'keterangan' => 'Ekonomi Perdesaan dan Masyarakat Tertinggal'],
            ['kode' => '400.10.6', 'keterangan' => 'Sumberdaya Alam dan Teknologi Tepat Guna Perdesaan'],
            ['kode' => '400.10.6.1', 'keterangan' => 'Fasilitasi Konservasi dan Rehabilitasi Lingkungan Perdesaan'],
            ['kode' => '400.10.6.2', 'keterangan' => 'Fasilitasi Pemanfaatan Lahan dan Pesisir Perdesaan'],
            ['kode' => '400.10.6.3', 'keterangan' => 'Fasilitasi Prasarana dan Sarana Perdesaan'],
            ['kode' => '400.10.6.4', 'keterangan' => 'Fasilitasi Pemetaan Kebutuhan dan Pengkajian Teknologi Perdesaan'],
            ['kode' => '400.10.6.5', 'keterangan' => 'Pemasyarakatan dan Kerjasama Teknologi Perdesaan'],
            ['kode' => '400.10.7', 'keterangan' => 'Badan Usaha Milik Desa (Bumdes)'],
            ['kode' => '400.11', 'keterangan' => 'PERTAMANAN DAN PEMAKAMAN'],
            ['kode' => '400.11.1', 'keterangan' => 'Kebijakan di bidang Pertamanan dan Pemakaman yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.11.2', 'keterangan' => 'Pertamanan'],
            ['kode' => '400.11.2.1', 'keterangan' => 'Perencanaan Pertamanan'],
            ['kode' => '400.11.2.2', 'keterangan' => 'Taman Kota'],
            ['kode' => '400.11.2.3', 'keterangan' => 'Tata Hias dan Ornamen Kota'],
            ['kode' => '400.11.3', 'keterangan' => 'Pemakaman'],
            ['kode' => '400.11.3.1', 'keterangan' => 'Perencanaan Pemakaman'],
            ['kode' => '400.11.3.2', 'keterangan' => 'Pemakaman'],
            ['kode' => '400.11.3.3', 'keterangan' => 'Pelayanan Pemakaman'],
            ['kode' => '400.11.4', 'keterangan' => 'Jalur Hijau'],
            ['kode' => '400.11.4.1', 'keterangan' => 'Perencanaan Jalur Hijau'],
            ['kode' => '400.11.4.2', 'keterangan' => 'Jalur Hijau Jalan'],
            ['kode' => '400.11.4.3', 'keterangan' => 'Jalur Hijau Penyempurna dan Tepian Air'],
            ['kode' => '400.11.5', 'keterangan' => 'Peran Serta Masyarakat'],
            ['kode' => '400.11.6', 'keterangan' => 'Pengawasan dan Penindakan'],
            ['kode' => '400.11.7', 'keterangan' => 'Pengelolaan Data'],
            ['kode' => '400.11.8', 'keterangan' => 'Evaluasi dan Pelaporan'],
            ['kode' => '400.12', 'keterangan' => 'KEPENDUDUKAN DAN CATATAN SIPIL'],
            ['kode' => '400.12.1', 'keterangan' => 'Kebijakan di bidang Kependudukan dan Catatan Sipil yang dilakukan oleh Pemerintah Daerah.'],
            ['kode' => '400.12.2', 'keterangan' => 'Pendaftaran Penduduk'],
            ['kode' => '400.12.2.1', 'keterangan' => 'Identitas Penduduk'],
            ['kode' => '400.12.2.2', 'keterangan' => 'Pindah Datang Penduduk Dalam Wilayah NKRI'],
            ['kode' => '400.12.2.3', 'keterangan' => 'Pindah Datang Penduduk Antar Negara'],
            ['kode' => '400.12.2.4', 'keterangan' => 'Pendataan Penduduk Rentan'],
            ['kode' => '400.12.2.5', 'keterangan' => 'Monitoring Evaluasi dan Dokumentasi'],
            ['kode' => '400.12.3', 'keterangan' => 'Pencatatan Sipil'],
            ['kode' => '400.12.3.1', 'keterangan' => 'Kelahiran dan Kematian'],
            ['kode' => '400.12.3.2', 'keterangan' => 'Perkawinan dan Perceraian'],
            ['kode' => '400.12.3.3', 'keterangan' => 'Pengangkatan Pengakuan dan Pengesahan Anak serta Perubahan'],
            ['kode' => '400.12.3.4', 'keterangan' => 'Pencatatan Kewarganegaraan'],
            ['kode' => '400.12.3.5', 'keterangan' => 'Monitoring Evaluasi dan Dokumentasi'],
            ['kode' => '400.12.4', 'keterangan' => 'Pengelolaan Informasi Administrasi Kependudukan'],
            ['kode' => '400.12.4.1', 'keterangan' => 'Sistem Informasi Administrasi Kependudukan'],
            ['kode' => '400.12.4.2', 'keterangan' => 'Kelembagaan Informasi Administrasi Kependudukan'],
            ['kode' => '400.12.4.3', 'keterangan' => 'Pengelolaan data Administrasi Kependudukan'],
            ['kode' => '400.12.4.4', 'keterangan' => 'Penyajian dan Layanan Informasi Administrasi Kependudukan'],
            ['kode' => '400.12.4.5', 'keterangan' => 'Monitoring Evaluasi dan Dokumentasi'],
            ['kode' => '400.12.5', 'keterangan' => 'Pengembangan Kebijakan Kependudukan'],
            ['kode' => '400.12.5.1', 'keterangan' => 'Kuantitas Penduduk'],
            ['kode' => '400.12.5.2', 'keterangan' => 'Kualitas Penduduk'],
            ['kode' => '400.12.5.3', 'keterangan' => 'Mobilitas Penduduk'],
            ['kode' => '400.12.5.4', 'keterangan' => 'Perlindungan dan Pemberdayaan Penduduk'],
            ['kode' => '400.12.5.5', 'keterangan' => 'Pengembangan Wawasan Kependudukan, Monitoring dan Evaluasi'],
            ['kode' => '400.12.6', 'keterangan' => 'Penyeriasian Kependudukan'],
            ['kode' => '400.12.6.1', 'keterangan' => 'Indikator Kependudukan'],
            ['kode' => '400.12.6.2', 'keterangan' => 'Proyeksi Penduduk'],
            ['kode' => '400.12.6.3', 'keterangan' => 'Perencanaan Kependudukan'],
            ['kode' => '400.12.6.4', 'keterangan' => 'Penyeriasian Kebijakan Kependudukan dengan Lembaga Non Pemerintah'],
            ['kode' => '400.12.6.5', 'keterangan' => 'Pelaksanaan Penyeriasian Kebijakan Kependudukan dengan Lembaga Pemerintah'],
            ['kode' => '400.13', 'keterangan' => 'KELUARGA BERENCANA'],
            ['kode' => '400.13.1', 'keterangan' => 'Kebijakan di bidang Keluarga Berencana yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.13.2', 'keterangan' => 'Analisis pengaduan kebijakan pengendalian penduduk'],
            ['kode' => '400.13.2.1', 'keterangan' => 'Pengumpulan dan pengolahan data'],
            ['kode' => '400.13.2.2', 'keterangan' => 'Evaluasi dan pelaporan'],
            ['kode' => '400.13.3', 'keterangan' => 'Fasilitas pengaduan kebijakan pengendalian penduduk'],
            ['kode' => '400.13.3.1', 'keterangan' => 'Penyiapan fasilitas'],
            ['kode' => '400.13.3.2', 'keterangan' => 'Evaluasi dan pelaporan'],
            ['kode' => '400.13.4', 'keterangan' => 'Profil dan proyeksi penduduk'],
            ['kode' => '400.13.4.1', 'keterangan' => 'Data profil dan proyeksi penduduk'],
            ['kode' => '400.13.4.2', 'keterangan' => 'Evaluasi data profil dan proyeksi penduduk'],
            ['kode' => '400.13.5', 'keterangan' => 'Penetapan parameter pengendalian penduduk'],
            ['kode' => '400.13.5.1', 'keterangan' => 'Penetapan sasaran parameter'],
            ['kode' => '400.13.5.2', 'keterangan' => 'Evaluasi sasaran parameter'],
            ['kode' => '400.13.6', 'keterangan' => 'Pemanfaatan perencanaan pengendalian penduduk'],
            ['kode' => '400.13.6.1', 'keterangan' => 'Pemanfaatan profil dan proyeksi'],
            ['kode' => '400.13.6.2', 'keterangan' => 'Pemanfaatan parameter'],
            ['kode' => '400.13.7', 'keterangan' => 'Pengembangan Sistem'],
            ['kode' => '400.13.7.1', 'keterangan' => 'Pengembangan Sistem Jalur Pendidikan Formal'],
            ['kode' => '400.13.7.2', 'keterangan' => 'Pengembangan Sistem Jalur Pendidikan Nonformal dan Informal'],
            ['kode' => '400.13.8', 'keterangan' => 'Pengembangan Materi'],
            ['kode' => '400.13.8.1', 'keterangan' => 'Pengembangan Materi Jalur Pendidikan Formal'],
            ['kode' => '400.13.8.2', 'keterangan' => 'Pengembangan Materi Jalur Pendidikan Nonformal dan Informal'],
            ['kode' => '400.13.9', 'keterangan' => 'Monitoring dan Evaluasi'],
            ['kode' => '400.13.9.1', 'keterangan' => 'Monitoring dan Evaluasi Jalur Pendidikan Formal'],
            ['kode' => '400.13.9.2', 'keterangan' => 'Monitoring dan Evaluasi Jalur Pendidikan Nonformal dan Informal'],
            ['kode' => '400.13.10', 'keterangan' => 'Analisis Sosial'],
            ['kode' => '400.13.11', 'keterangan' => 'Analisis Ekonomi'],
            ['kode' => '400.13.12', 'keterangan' => 'Analisis Dampak Politik, Pertahanan dan Keamanan'],
            ['kode' => '400.13.13', 'keterangan' => 'Analisis Daya Dukung dan Daya Tampung Lingkungan'],
            ['kode' => '400.13.14', 'keterangan' => 'Bina Keluarga Berencana Rumah Sakit dan Klinik Pemerintah'],
            ['kode' => '400.13.15', 'keterangan' => 'Jaminan pelayanan dan penyediaan sarana keluarga berencana'],
            ['kode' => '400.13.16', 'keterangan' => 'Kualitas pelayanan keluarga berencana pemerintah'],
            ['kode' => '400.13.16.1', 'keterangan' => 'Standarisasi pelayanan keluarga berencana pemerintah'],
            ['kode' => '400.13.16.2', 'keterangan' => 'Monitoring dan evaluasi pelayanan keluarga berencana pemerintah'],
            ['kode' => '400.13.17', 'keterangan' => 'Bina keluarga berencana rumah sakit dan klinik swasta'],
            ['kode' => '400.13.18', 'keterangan' => 'Jaminan dan ketersediaan sarana keluarga berencana swasta'],
            ['kode' => '400.13.19', 'keterangan' => 'Kualitas pelayanan keluarga berencana swasta'],
            ['kode' => '400.13.19.1', 'keterangan' => 'Standarisasi pelayanan keluarga berencana swasta'],
            ['kode' => '400.13.19.2', 'keterangan' => 'Monitoring dan Evaluasi pelayanan keluarga berencana swasta'],
            ['kode' => '400.13.20', 'keterangan' => 'Akses dan kualitas pelayanan keluarga berencana jalur wilayah tertinggal, terpencil dan perbatasan'],
            ['kode' => '400.13.20.1', 'keterangan' => 'Peningkatan akses pelayanan keluarga berencana wilayah tertinggal, terpencil, dan perbatasan'],
            ['kode' => '400.13.20.2', 'keterangan' => 'Peningkatan kualitas pelayanan keluarga berencana wilayah tertinggal, terpencil, dan perbatasan'],
            ['kode' => '400.13.21', 'keterangan' => 'Akses dan kualitas pelayanan keluarga berencana wilayah miskin perkotaan'],
            ['kode' => '400.13.21.1', 'keterangan' => 'Peningkatan akses pelayanan keluarga berencana wilayah miskin perkotaan'],
            ['kode' => '400.13.21.2', 'keterangan' => 'Peningkatan kualitas pelayanan keluarga berencana wilayah miskin perkotaan'],
            ['kode' => '400.13.22', 'keterangan' => 'Kesertaan keluarga berencana pria'],
            ['kode' => '400.13.22.1', 'keterangan' => 'Peningkatan akses keluarga berencana pria'],
            ['kode' => '400.13.22.2', 'keterangan' => 'Peningkatan partisipasi keluarga berencana pria'],
            ['kode' => '400.13.23', 'keterangan' => 'Kelangsungan hidup ibu, bayi, dan anak'],
            ['kode' => '400.13.24', 'keterangan' => 'Pencegahan PMS dan HIV/AIDS'],
            ['kode' => '400.13.25', 'keterangan' => 'Pencegahan kanker alat reproduksi dan penanggulangan infertilitas'],
            ['kode' => '400.13.26', 'keterangan' => 'Pelembagaan bina keluarga Balita dan anak'],
            ['kode' => '400.13.26.1', 'keterangan' => 'Pengembangan kelompok bina keluarga Balita dan anak'],
            ['kode' => '400.13.26.2', 'keterangan' => 'Pengembangan kemitraan bina keluarga dan anak'],
            ['kode' => '400.13.27', 'keterangan' => 'Monitoring dan evaluasi bina keluarga Balita dan anak'],
            ['kode' => '400.13.27.1', 'keterangan' => 'Monitoring bina keluarga Balita dan anak'],
            ['kode' => '400.13.27.2', 'keterangan' => 'Evaluasi dan pelaporan bina keluarga Balita dan anak'],
            ['kode' => '400.13.28', 'keterangan' => 'Pelembagaan bina ketahanan remaja'],
            ['kode' => '400.13.28.1', 'keterangan' => 'Pelembagaan bina ketahanan remaja jalur pendidikan'],
            ['kode' => '400.13.28.2', 'keterangan' => 'Pelembagaan bina ketahanan remaja jalur masyarakat'],
            ['kode' => '400.13.29', 'keterangan' => 'Monitoring dan evaluasi bina ketahanan remaja'],
            ['kode' => '400.13.29.1', 'keterangan' => 'Monitoring bina ketahanan remaja'],
            ['kode' => '400.13.29.2', 'keterangan' => 'Evaluasi dan pelaporan bina ketahanan remaja'],
            ['kode' => '400.13.30', 'keterangan' => 'Pengembangan Program Bina Ketahanan Keluarga Lansia dan Rentan'],
            ['kode' => '400.13.30.1', 'keterangan' => 'Pengembangan Program Bina Ketahanan keluarga Lansia'],
            ['kode' => '400.13.30.2', 'keterangan' => 'Pengembangan Program Bina Ketahanan keluarga Rentan'],
            ['kode' => '400.13.31', 'keterangan' => 'Pelembagaan Bina Ketahanan keluarga Lansia dan Rentan'],
            ['kode' => '400.13.31.1', 'keterangan' => 'Pengembangan Kelompok Bina Ketahanan Keluarga Lansia dan Rentan'],
            ['kode' => '400.13.31.2', 'keterangan' => 'Pengembangan Kemitraan Bina Ketahanan Keluarga Lansia dan Rentan'],
            ['kode' => '400.13.32', 'keterangan' => 'Monitoring dan evaluasi bina ketahanan keluarga Lansia dan Rentan'],
            ['kode' => '400.13.32.1', 'keterangan' => 'Monitoring Bina Ketahanan Keluarga Lansia dan Rentan'],
            ['kode' => '400.13.32.2', 'keterangan' => 'Evaluasi dan pelaporan bina ketahanan keluarga Lansia dan Rentan'],
            ['kode' => '400.13.33', 'keterangan' => 'Pengembangan program usaha ekonomi keluarga'],
            ['kode' => '400.13.34', 'keterangan' => 'Peningkatan teknologi dan permodalan usaha ekonomi keluarga'],
            ['kode' => '400.13.35', 'keterangan' => 'Peningkatan manajemen usaha ekonomi keluarga'],
            ['kode' => '400.13.35.1', 'keterangan' => 'Pengembangan administrasi dan keuangan kelompok usaha ekonomi keluarga'],
            ['kode' => '400.13.35.2', 'keterangan' => 'Pengemangan pemasaran kelompok usaha ekonomi keluarga'],
            ['kode' => '400.13.36', 'keterangan' => 'Monitoring dan evaluasi usaha ekonomi keluarga'],
            ['kode' => '400.13.37', 'keterangan' => 'Pengembangan Program Pusat pelayanan Keluarga Sejahtera'],
            ['kode' => '400.13.38', 'keterangan' => 'Pelembagaan Pusat Pelayanan Keluarga Sejahtera'],
            ['kode' => '400.13.38.1', 'keterangan' => 'Pengembangan Pusat Pelayanan Keluarga Sejahtera'],
            ['kode' => '400.13.38.2', 'keterangan' => 'Pengembangan Kemitraan Pusat Pelayanan Keluarga Sejahtera'],
            ['kode' => '400.13.39', 'keterangan' => 'Monitoring dan Evaluasi Pusat Pelayanan Keluarga Sejahtera'],
            ['kode' => '400.13.39.1', 'keterangan' => 'Monitoring Pusat Pelayanan Keluarga Sejahtera'],
            ['kode' => '400.13.39.2', 'keterangan' => 'Evaluasi dan pelaporan Pusat Pelayanan Keluarga Sejahtera'],
            ['kode' => '400.13.40', 'keterangan' => 'Pengembangan advokasi dan komunikasi, informasi, edukasi'],
            ['kode' => '400.13.40.1', 'keterangan' => 'Perencanaan advokasi dan komunikasi, informasi, edukasi'],
            ['kode' => '400.13.40.2', 'keterangan' => 'Evaluasi dan pelaporan advokasi dan komunikasi, informasi, edukasi'],
            ['kode' => '400.13.41', 'keterangan' => 'Advokasi dan pencitraan'],
            ['kode' => '400.13.42', 'keterangan' => 'Komunikasi, Informasi dan Edukasi'],
            ['kode' => '400.13.42.1', 'keterangan' => 'Promosi'],
            ['kode' => '400.13.42.2', 'keterangan' => 'Sarana produksi media komunikasi'],
            ['kode' => '400.13.42.3', 'keterangan' => 'Produk media komunikasi'],
            ['kode' => '400.13.43', 'keterangan' => 'Hubungan dengan lembaga pemerintah pusat dan provinsi'],
            ['kode' => '400.13.44', 'keterangan' => 'Hubungan dengan lembaga pemerintah kabupaten dan kota'],
            ['kode' => '400.13.44.1', 'keterangan' => 'Pengembangan hubungan dengan lembaga pemerintah kabupaten dan kota'],
            ['kode' => '400.13.44.2', 'keterangan' => 'Penguatan hubungan dengan lembaga pemerintah kabupaten dan kota'],
            ['kode' => '400.13.45', 'keterangan' => 'Hubungan dengan lembaga nonpemerintah'],
            ['kode' => '400.13.45.1', 'keterangan' => 'Pengembangan hubungan dengan lembaga nonpemerintah'],
            ['kode' => '400.13.45.2', 'keterangan' => 'Penguatan hubungan dengan lembaga nonpemerintah'],
            ['kode' => '400.13.46', 'keterangan' => 'Tenaga Lini Lapangan'],
            ['kode' => '400.13.47.1', 'keterangan' => 'Pengembangan institusi masyarakat pedesaan'],
            ['kode' => '400.13.47.2', 'keterangan' => 'Monitoring dan evaluasi institusi masyarakat pedesaan'],
            ['kode' => '400.13.48', 'keterangan' => 'Mekanisme Operasional lini lapangan'],
            ['kode' => '400.13.48.1', 'keterangan' => 'Pengembangan mekanisme operasional lini lapangan'],
            ['kode' => '400.13.48.2', 'keterangan' => 'Monitoring dan evaluasi mekanisme operasional lini lapangan'],
            ['kode' => '400.13.49', 'keterangan' => 'Pengembangan sistem pencatatan dan pelaporan'],
            ['kode' => '400.13.49.1', 'keterangan' => 'Perumusan pola sistem pencatatan dan pelaporan'],
            ['kode' => '400.13.49.2', 'keterangan' => 'Monitoring dan evaluasi sistem pencatatan dan pelaporan'],
            ['kode' => '400.13.50', 'keterangan' => 'Pengumpulan dan pengolahan data'],
            ['kode' => '400.13.51', 'keterangan' => 'Analisis dan evaluasi'],
            ['kode' => '400.13.51.1', 'keterangan' => 'Analisis dan evaluasi pengendalian penduduk'],
            ['kode' => '400.13.51.2', 'keterangan' => 'Analisis dan evaluasi keluarga berencana dan keluarga sejahtera'],
            ['kode' => '400.13.52', 'keterangan' => 'Sistem aplikasi dan bank data'],
            ['kode' => '400.13.52.1', 'keterangan' => 'Pengembangan sistem aplikasi'],
            ['kode' => '400.13.52.2', 'keterangan' => 'Pengelolaan bank data'],
            ['kode' => '400.13.53', 'keterangan' => 'Infrastruktur teknologi informasi'],
            ['kode' => '400.13.53.1', 'keterangan' => 'Pengembangan infrastruktur teknologi informasi'],
            ['kode' => '400.13.53.2', 'keterangan' => 'Pemeliharaan infrastruktur teknologi informasi'],
            ['kode' => '400.13.54', 'keterangan' => 'Dokumentasi dan penyebarluasan informasi'],
            ['kode' => '400.13.54.1', 'keterangan' => 'Dokumentasi dan perpustakaan'],
            ['kode' => '400.13.54.2', 'keterangan' => 'Pengelolaan situs BKKBN dan media konferensi'],
            ['kode' => '400.14', 'keterangan' => 'HUBUNGAN MASYARAKAT'],
            ['kode' => '400.14.1', 'keterangan' => 'Keprotokolan'],
            ['kode' => '400.14.1.1', 'keterangan' => 'Penyelenggaraan acara kedinasan (upacara, pelantikan, peresmian, dan jamuan termasuk acara peringatan hari-hari besar)'],
            ['kode' => '400.14.1.2', 'keterangan' => 'Buku tamu Keprotokolan'],
            ['kode' => '400.14.1.3', 'keterangan' => 'Agenda kegiatan pimpinan daerah'],
            ['kode' => '400.14.1.4', 'keterangan' => 'Kunjungan dinas dalam dan luar negeri'],
            ['kode' => '400.14.2', 'keterangan' => 'Daftar nama/alamat kantor /pejabat'],
            ['kode' => '400.14.3', 'keterangan' => 'Dokumentasi/ liputan kegiatan dinas pimpinan, acara kedinasan dan peristiwa-peristiwa bidang masing-masing, dalam berbagai media: kertas, foto/ video/ rekaman suara/ multi media'],
            ['kode' => '400.14.4', 'keterangan' => 'Pengumpulan, pengolahan dan penyajian informasi kelembagaan'],
            ['kode' => '400.14.4.1', 'keterangan' => 'Kliping koran'],
            ['kode' => '400.14.4.2', 'keterangan' => 'Brosur /Leaflet/poster /plakat'],
            ['kode' => '400.14.4.3', 'keterangan' => 'Pengumuman /pemberitaan'],
            ['kode' => '400.14.5', 'keterangan' => 'Hubungan antar lembaga dan Pemerintahan Daerah'],
            ['kode' => '400.14.5.1', 'keterangan' => 'Hubungan antar lembaga pemerintah'],
            ['kode' => '400.14.5.2', 'keterangan' => 'Hubungan dengan organisasi sosial / LSM'],
            ['kode' => '400.14.5.3', 'keterangan' => 'Hubungan dengan perusahaan'],
            ['kode' => '400.14.5.4', 'keterangan' => 'Hubungan dengan Perguruan Tinggi/ sekolah, termasuk magang, Pendidikan Sistem Ganda (PSG)/ Praktek Kerja Lapang (PKL)'],
            ['kode' => '400.14.5.5', 'keterangan' => 'Forum Kehumasan'],
            ['kode' => '400.14.5.6', 'keterangan' => 'Hubungan dengan Media Massa'],
            ['kode' => '400.14.6', 'keterangan' => 'Dengar pendapat/hearing DPRD'],
            ['kode' => '400.14.7', 'keterangan' => 'Bahan/materi pidato/sidang Muspida Provinsi/Kota/Kabupaten'],
            ['kode' => '400.14.8', 'keterangan' => 'Penerbitan Majalah, buletin, koran dan jurnal'],
            ['kode' => '400.14.9', 'keterangan' => 'Publikasi melalui media cetak maupun elektronik'],
            ['kode' => '400.14.10', 'keterangan' => 'Pameran /sayemara/lomba/festival, pembuatan spanduk dan iklan'],
            ['kode' => '400.14.11', 'keterangan' => 'Penghargaan/tanda kenang-kenangan'],
            ['kode' => '400.14.12', 'keterangan' => 'Ucapan Terimakasih, Ucapan Selamat, Bela Sungkawa, Permohonan Maaf'],
        ];
        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
