<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi600Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            ['kode' => '600', 'keterangan' => 'PEKERJAAN UMUM DAN KETENAGAAN'],
            ['kode' => '600.1', 'keterangan' => 'PEKERJAAN UMUM'],
            ['kode' => '600.1.1', 'keterangan' => 'Kebijakan di bidang Pekerjaan Umum yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '600.1.2', 'keterangan' => 'Penatagunaan Sumber Daya Air'],
            ['kode' => '600.1.2.1', 'keterangan' => 'Perencanaan Wilayah Sungai'],
            ['kode' => '600.1.2.2', 'keterangan' => 'Kelembagaan'],
            ['kode' => '600.1.2.3', 'keterangan' => 'Pemanfaatan Sumber Daya Air'],
            ['kode' => '600.1.2.4', 'keterangan' => 'Hidrologi dan Lingkungan Sumber Daya Air'],
            ['kode' => '600.1.2.5', 'keterangan' => 'Pengaturan dan Pemantauan'],
            ['kode' => '600.1.3', 'keterangan' => 'Pengembangan Jaringan Sumber Daya Air'],
            ['kode' => '600.1.3.1', 'keterangan' => 'Perencanaan Pengelolaan Sumber Daya Air'],
            ['kode' => '600.1.3.2', 'keterangan' => 'Manajemen Mutu'],
            ['kode' => '600.1.3.3', 'keterangan' => 'Informasi dan Data Sumber Daya Air'],
            ['kode' => '600.1.3.4', 'keterangan' => 'Keterpaduan Pemrograman'],
            ['kode' => '600.1.4', 'keterangan' => 'Pengelolaan Sumber Daya Air'],
            ['kode' => '600.1.4.1', 'keterangan' => 'Pengelolaan Sungai dan Pantai'],
            ['kode' => '600.1.4.2', 'keterangan' => 'Pengelolaan Irigasi dan Rawa'],
            ['kode' => '600.1.4.3', 'keterangan' => 'Pengelolaan Bendungan, Danau, Situ, dan Embung'],
            ['kode' => '600.1.4.4', 'keterangan' => 'Pengelolaan Air Tanah dan Air Baku'],
            ['kode' => '600.1.5', 'keterangan' => 'Operasi dan Pemeliharaan Sumber Daya Air'],
            ['kode' => '600.1.5.1', 'keterangan' => 'Operasi dan Pemeliharaan Sungai dan Pantai'],
            ['kode' => '600.1.5.2', 'keterangan' => 'Operasi dan Pemeliharaan Irigasi dan Rawa'],
            ['kode' => '600.1.5.3', 'keterangan' => 'Operasi dan Pemeliharaan Bendungan, Danau, Situ, dan Embung'],
            ['kode' => '600.1.5.4', 'keterangan' => 'Operasi dan Pemeliharaan Air Tanah dan Air Baku'],
            ['kode' => '600.1.5.5', 'keterangan' => 'Operasi dan Pemeliharaan Pengendalian Lumpur Sidoarjo'],
            ['kode' => '600.1.6', 'keterangan' => 'Pengendalian Lumpur Sidoarjo (Bencana Lokal Lingkup Nasional)'],
            ['kode' => '600.1.6.1', 'keterangan' => 'Perencanaan Pengendalian Lumpur Sidoarjo'],
            ['kode' => '600.1.6.2', 'keterangan' => 'Pemrograman Pengendalian Lumpur Sidoarjo'],
            ['kode' => '600.1.6.3', 'keterangan' => 'Pelaksanaan Pengendalian Lumpur Sidoarjo'],
            ['kode' => '600.1.6.4', 'keterangan' => 'Pengendalian Dampak Sosial, Ekonomi, dan Lingkungan akibat Lumpur Sidoarjo'],
            ['kode' => '600.1.6.5', 'keterangan' => 'Sistem Manajemen Keselamatan dan Kesehatan Kerja'],
            ['kode' => '600.1.7', 'keterangan' => 'Pengembangan Jaringan Jalan'],
            ['kode' => '600.1.7.1', 'keterangan' => 'Keterpaduan Perencanaan'],
            ['kode' => '600.1.7.2', 'keterangan' => 'Sistem Jaringan Jalan'],
            ['kode' => '600.1.7.3', 'keterangan' => 'Lingkungan dan Keselamatan Jalan'],
            ['kode' => '600.1.8', 'keterangan' => 'Pembangunan Jalan'],
            ['kode' => '600.1.8.1', 'keterangan' => 'Standar dan Pedoman'],
            ['kode' => '600.1.8.2', 'keterangan' => 'Manajemen Konstruksi'],
            ['kode' => '600.1.8.3', 'keterangan' => 'Pengelolaan Geometrik, Perkerasan, dan Drainage'],
            ['kode' => '600.1.8.4', 'keterangan' => 'Pengelolaan Geoteknik dan Manajemen Lereng'],
            ['kode' => '600.1.9', 'keterangan' => 'Preservasi Jalan'],
            ['kode' => '600.1.9.1', 'keterangan' => 'Standar dan Pedoman'],
            ['kode' => '600.1.9.2', 'keterangan' => 'Perencanaan Teknis'],
            ['kode' => '600.1.9.3', 'keterangan' => 'Teknik Rekonstruksi'],
            ['kode' => '600.1.9.4', 'keterangan' => 'Teknik Pemeliharaan Jalan'],
            ['kode' => '600.1.10', 'keterangan' => 'Pengelolaan Jembatan'],
            ['kode' => '600.1.10.1', 'keterangan' => 'Standar dan Pedoman'],
            ['kode' => '600.1.10.2', 'keterangan' => 'Perencanaan Teknis'],
            ['kode' => '600.1.10.3', 'keterangan' => 'Teknik Jembatan'],
            ['kode' => '600.1.10.4', 'keterangan' => 'Teknik Terowongan dan Jembatan Khusus'],
            ['kode' => '600.1.11', 'keterangan' => 'Pengelolaan Jalan Bebas Hambatan, Perkotaan, dan Fasilitas Jalan Daerah'],
            ['kode' => '600.1.11.1', 'keterangan' => 'Bimbingan Teknik Jalan Daerah'],
            ['kode' => '600.1.11.2', 'keterangan' => 'Pengembangan Jalan Metropolitan dan Kota Besar'],
            ['kode' => '600.1.11.3', 'keterangan' => 'Pembinaan Teknik Jalan Bebas Hambatan'],
            ['kode' => '600.1.12', 'keterangan' => 'Pengaturan Jalan Tol'],
            ['kode' => '600.1.12.1', 'keterangan' => 'Persiapan pengusahaan jalan tol'],
            ['kode' => '600.1.12.2', 'keterangan' => 'Pengadaan Investasi Jalan Tol'],
            ['kode' => '600.1.12.3', 'keterangan' => 'Teknik Pengaturan Jalan Tol'],
            ['kode' => '600.1.12.4', 'keterangan' => 'Pengambilalihan hak pengusahaan jalan tol'],
            ['kode' => '600.1.13', 'keterangan' => 'Keterpaduan Infrastruktur Permukiman'],
            ['kode' => '600.1.13.1', 'keterangan' => 'Keterpaduan Perencanaan dan Kemitraan'],
            ['kode' => '600.1.13.2', 'keterangan' => 'Keterpaduan Pembiayaan dan Pelaksanaan'],
            ['kode' => '600.1.14', 'keterangan' => 'Pengembangan Kawasan Permukiman'],
            ['kode' => '600.1.14.1', 'keterangan' => 'Perencanaan Teknis'],
            ['kode' => '600.1.14.2', 'keterangan' => 'Kawasan Permukiman Perkotaan'],
            ['kode' => '600.1.14.3', 'keterangan' => 'Kawasan Permukiman Pedesaan'],
            ['kode' => '600.1.14.4', 'keterangan' => 'Kawasan Permukiman Khusus'],
            ['kode' => '600.1.14.5', 'keterangan' => 'Kelembagaan'],
            ['kode' => '600.1.15', 'keterangan' => 'Pembinaan Penataan Bangunan'],
            ['kode' => '600.1.15.1', 'keterangan' => 'Perencanaan Teknis'],
            ['kode' => '600.1.15.2', 'keterangan' => 'Penataan Bangunan Gedung'],
            ['kode' => '600.1.15.3', 'keterangan' => 'Pengelolaan Rumah Negara'],
            ['kode' => '600.1.15.4', 'keterangan' => 'Penataan Bangunan dan Lingkungan Khusus'],
            ['kode' => '600.1.15.5', 'keterangan' => 'Kelembagaan'],
            ['kode' => '600.1.16', 'keterangan' => 'Pengembangan Sistem Penyediaan Air Minum'],
            ['kode' => '600.1.16.1', 'keterangan' => 'Perencanaan Teknis'],
            ['kode' => '600.1.16.2', 'keterangan' => 'Sistem Penyediaan Air Minum Perkotaan'],
            ['kode' => '600.1.16.3', 'keterangan' => 'Sistem Penyediaan Air Minum Pedesaan'],
            ['kode' => '600.1.16.4', 'keterangan' => 'Sistem Penyediaan Air Minum Khusus'],
            ['kode' => '600.1.16.5', 'keterangan' => 'Kelembagaan'],
            ['kode' => '600.1.16.6', 'keterangan' => 'Peningkatan Penyelenggaraan Sistem Penyediaan Air Minum'],
            ['kode' => '600.1.16.7', 'keterangan' => 'Pengelolaan Laboratorium dan Bengkel Kerja'],
            ['kode' => '600.1.17', 'keterangan' => 'Pengembangan Penyehatan Lingkungan Permukiman'],
            ['kode' => '600.1.17.1', 'keterangan' => 'Perencanaan Teknis'],
            ['kode' => '600.1.17.2', 'keterangan' => 'Pengelolaan Air Limbah'],
            ['kode' => '600.1.17.3', 'keterangan' => 'Pengelolaan Persampahan'],
            ['kode' => '600.1.17.4', 'keterangan' => 'Penyehatan Lingkungan Permukiman Khusus'],
            ['kode' => '600.1.17.5', 'keterangan' => 'Kelembagaan'],
            ['kode' => '600.1.17.6', 'keterangan' => 'Pengelolaan Laboratorium dan Bengkel Kerja'],
            ['kode' => '600.1.18', 'keterangan' => 'Pemantauan dan Evaluasi'],
            ['kode' => '600.2', 'keterangan' => 'PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN'],
            ['kode' => '600.2.1', 'keterangan' => 'Kebijakan di bidang Perumahan Rakyat dan Kawasan Pemukiman yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '600.2.2', 'keterangan' => 'Perencanaan Pembiayaan Peruman'],
            ['kode' => '600.2.2.1', 'keterangan' => 'Keterpaduan Perencanaan'],
            ['kode' => '600.2.2.2', 'keterangan' => 'Strategi Pembiayaan dan Analisa Pasar Perumahan'],
            ['kode' => '600.2.2.3', 'keterangan' => 'Kemitraan'],
            ['kode' => '600.2.3', 'keterangan' => 'Pola Pembiayaan Perumahan'],
            ['kode' => '600.2.3.1', 'keterangan' => 'Pola Pembiayaan Perumahan Rumah Umum'],
            ['kode' => '600.2.3.2', 'keterangan' => 'Pola Pembiayaan Perumahan Rumah Swadaya dan Mikro Perumahan'],
            ['kode' => '600.2.3.3', 'keterangan' => 'Pola Investasi Perumahan'],
            ['kode' => '600.2.4', 'keterangan' => 'Pendayagunaan Sumber Pembiayaan Perumahan'],
            ['kode' => '600.2.4.1', 'keterangan' => 'Sumber Pembiayaan Primer'],
            ['kode' => '600.2.4.2', 'keterangan' => 'Sumber Pembiayaan Sekunder'],
            ['kode' => '600.2.4.3', 'keterangan' => 'Sumber Tabungan Perumahan dan Pembiayaan Lainnya'],
            ['kode' => '600.2.4.4', 'keterangan' => 'Sistem Pembiayaan Perumahan'],
            ['kode' => '600.2.4.5', 'keterangan' => 'Pengelolaan Dana Pembiayaan Perumahan'],
            ['kode' => '600.2.5', 'keterangan' => 'Perencanaan Penyediaan Perumahan'],
            ['kode' => '600.2.5.1', 'keterangan' => 'Keterpaduan Perencanaan'],
            ['kode' => '600.2.5.2', 'keterangan' => 'Analisa Teknik'],
            ['kode' => '600.2.5.3', 'keterangan' => 'Rencana Pengembangan Lingkungan Hunian'],
            ['kode' => '600.2.5.4', 'keterangan' => 'Kemitraan dan Kelembagaan'],
            ['kode' => '600.2.6', 'keterangan' => 'Penyediaan Rumah Susun'],
            ['kode' => '600.2.6.1', 'keterangan' => 'Perencanaan Teknik'],
            ['kode' => '600.2.6.2', 'keterangan' => 'Penyediaan'],
            ['kode' => '600.2.6.3', 'keterangan' => 'Penghunian, Pengalihan, dan Pemanfaatan'],
            ['kode' => '600.2.6.4', 'keterangan' => 'Pengelolaan'],
            ['kode' => '600.2.7', 'keterangan' => 'Penyediaan Rumah Khusus'],
            ['kode' => '600.2.7.1', 'keterangan' => 'Perencanaan Teknik'],
            ['kode' => '600.2.7.2', 'keterangan' => 'Penyediaan dan Pengelolaan Rumah Tapak Khusus'],
            ['kode' => '600.2.7.3', 'keterangan' => 'Bimbingan teknis dan supervisi'],
            ['kode' => '600.2.7.4', 'keterangan' => 'Penyelenggaraan Bantuan Rumah Swadaya'],
            ['kode' => '600.2.7.5', 'keterangan' => 'Perencanaan Teknik'],
            ['kode' => '600.2.7.6', 'keterangan' => 'Fasilitas Backlog Rumah Swadaya dan Rumah Tidak Layak Huni'],
            ['kode' => '600.2.7.7', 'keterangan' => 'Pelaksanaan Bantuan Simultan'],
            ['kode' => '600.2.8', 'keterangan' => 'Penyediaan Rumah Umum dan Komersial'],
            ['kode' => '600.2.8.1', 'keterangan' => 'Perencanaan Teknik'],
            ['kode' => '600.2.8.2', 'keterangan' => 'Pemberian Bantuan Rumah Umum'],
            ['kode' => '600.2.8.3', 'keterangan' => 'Fasilitasi Hunian Berimbang'],
            ['kode' => '600.2.8.4', 'keterangan' => 'Fasilitasi Penyediaan Lahan Perumahan'],
            ['kode' => '600.2.9', 'keterangan' => 'Investasi Infrastruktur'],
            ['kode' => '600.2.9.1', 'keterangan' => 'Pelaksanaan Kebijakan Investasi Infrastruktur'],
            ['kode' => '600.2.9.2', 'keterangan' => 'Sinkronisasi Investasi Infrastruktur'],
            ['kode' => '600.2.9.3', 'keterangan' => 'Fasilitasi dan Mitigasi Risiko Investasi Infrastruktur'],
            ['kode' => '600.2.9.4', 'keterangan' => 'Pasar Infrastruktur'],
            ['kode' => '600.2.10', 'keterangan' => 'Penyelenggaraan Jasa Konstruksi'],
            ['kode' => '600.2.10.1', 'keterangan' => 'Sistem Penyelenggaraan'],
            ['kode' => '600.2.10.2', 'keterangan' => 'Kontrak Konstruksi'],
            ['kode' => '600.2.10.3', 'keterangan' => 'Konstruksi Berkelanjutan'],
            ['kode' => '600.2.10.4', 'keterangan' => 'Manajemen Mutu'],
            ['kode' => '600.2.11', 'keterangan' => 'Kelembagaan dan Sumber Daya Konstruksi'],
            ['kode' => '600.2.11.1', 'keterangan' => 'Kelembagaan'],
            ['kode' => '600.2.11.2', 'keterangan' => 'Material dan Peralatan Konstruksi'],
            ['kode' => '600.2.11.3', 'keterangan' => 'Teknologi Konstruksi dan Produksi Dalam Negeri'],
            ['kode' => '600.2.11.4', 'keterangan' => 'Usaha Jasa Konstruksi'],
            ['kode' => '600.2.12', 'keterangan' => 'Kompetensi dan Produktivitas Konstruksi'],
            ['kode' => '600.2.12.1', 'keterangan' => 'Standar dan Materi Kompetensi'],
            ['kode' => '600.2.12.2', 'keterangan' => 'Penerapan Kompetensi'],
            ['kode' => '600.2.12.3', 'keterangan' => 'Pengembangan Profesi Jasa Konstruksi'],
            ['kode' => '600.2.12.4', 'keterangan' => 'Pengembangan Produktivitas'],
            ['kode' => '600.2.13', 'keterangan' => 'Peningkatan Kerjasama dan Pemberdayaan Jasa Konstruksi'],
            ['kode' => '600.2.13.1', 'keterangan' => 'Peningkatan Kerjasama'],
            ['kode' => '600.2.13.2', 'keterangan' => 'Pemberdayaan Jasa Konstruksi'],
            ['kode' => '600.2.14', 'keterangan' => 'Peningkatan Jasa Konstruksi'],
            ['kode' => '600.2.14.1', 'keterangan' => 'Koordinasi dan Sinkronisasi Rencana Kerja'],
            ['kode' => '600.2.14.2', 'keterangan' => 'Pelaksanaan Pengendalian Mutu'],
            ['kode' => '600.2.15', 'keterangan' => 'Penerapan Teknologi Konstruksi'],
            ['kode' => '600.2.15.1', 'keterangan' => 'Koordinasi, Sinkronisasi, dan Kerjasama Penerapan Teknologi Konstruksi'],
            ['kode' => '600.2.15.2', 'keterangan' => 'Pengembangan Materi'],
            ['kode' => '600.2.15.3', 'keterangan' => 'Pendayagunaan Material dan Peralatan Konstruksi'],
            ['kode' => '600.2.16', 'keterangan' => 'Rencana Pengembangan Infrastruktur Pekerjaan Perumahan Rakyat (PUPR)'],
            ['kode' => '600.2.16.1', 'keterangan' => 'Antar Sektor'],
            ['kode' => '600.2.16.2', 'keterangan' => 'Antar Wilayah'],
            ['kode' => '600.2.17', 'keterangan' => 'Pengembangan Kawasan Strategis'],
            ['kode' => '600.2.17.1', 'keterangan' => 'Keterpaduan Infrastruktur Kawasan Strategis'],
            ['kode' => '600.2.17.2', 'keterangan' => 'Pengembangan Infrastruktur Antarkawasan Strategis'],
            ['kode' => '600.2.18', 'keterangan' => 'Pengembangan Kawasan Perkotaan'],
            ['kode' => '600.2.18.1', 'keterangan' => 'Pengembangan Infrastruktur Kawasan Metropolitan'],
            ['kode' => '600.2.18.2', 'keterangan' => 'Pengembangan Infrastruktur Kawasan Kota Besar dan Kota Baru'],
            ['kode' => '600.2.18.3', 'keterangan' => 'Pengembangan Infrastruktur Kawasan Kota Kecil dan Pedesaan'],
            ['kode' => '600.2.18.4', 'keterangan' => 'Analisa Manfaat dan Skema Pembiayaan'],
            ['kode' => '600.2.18.5', 'keterangan' => 'Sinkronisasi Program dan Pembiayaan Infrastruktur Perumahan Rakyat (PUPR)'],
            ['kode' => '600.2.19', 'keterangan' => 'Pemantauan dan Evaluasi'],
            ['kode' => '600.3', 'keterangan' => 'TATA RUANG (TATA KOTA)'],
            ['kode' => '600.3.1', 'keterangan' => 'Kebijakan di bidang Tata Ruang yang dilakukan Pemerintahan Daerah'],
            ['kode' => '600.3.2', 'keterangan' => 'Perencanaan'],
            ['kode' => '600.3.2.1', 'keterangan' => 'Tata Ruang Wilayah Kabupaten (RT/RW)'],
            ['kode' => '600.3.2.2', 'keterangan' => 'Rencana Detail Tata Ruang (RDTR)'],
            ['kode' => '600.3.2.3', 'keterangan' => 'Rencana Tata Ruang Strategis Kabupaten'],
            ['kode' => '600.3.2.4', 'keterangan' => 'Rencana Tata Bangun Lingkungan (RTBL)'],
            ['kode' => '600.3.2.5', 'keterangan' => 'Rencana Pengembangan Sistem Sarana dan Prasarana Kabupaten'],
            ['kode' => '600.3.2.6', 'keterangan' => 'Rencana Teknis Prasarana Kota'],
            ['kode' => '600.3.2.7', 'keterangan' => 'Rencana Teknis Rencana Peremajaan dan Pengembangan Kotas Prasarana Kota'],
            ['kode' => '600.3.3', 'keterangan' => 'Pemanfaatan dan Pengendalian'],
            ['kode' => '600.3.3.1', 'keterangan' => 'Evaluasi dan Pengawasan Penata Ruang'],
            ['kode' => '600.3.3.2', 'keterangan' => 'Ijin Pemanfaatan Ruang'],
            ['kode' => '600.3.3.3', 'keterangan' => 'Pembatalan Ijin Pemanfaatan Ruang'],
            ['kode' => '600.3.4', 'keterangan' => 'Pemetaan'],
            ['kode' => '600.3.4.1', 'keterangan' => 'Peta Dasar'],
            ['kode' => '600.3.4.2', 'keterangan' => 'Survey Pemetaan Ruang Darat'],
            ['kode' => '600.3.4.3', 'keterangan' => 'Survey Pemetaan Ruang Air'],
            ['kode' => '600.3.4.4', 'keterangan' => 'Survey Pemetaan Ruang Udara'],
            ['kode' => '600.4', 'keterangan' => 'LINGKUNGAN HIDUP'],
            ['kode' => '600.4.1', 'keterangan' => 'Kebijakan di bidang Lingkungan Hidup yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '600.4.2', 'keterangan' => 'Perencanaan Pemanfaatan Sumber Daya Alam dan Lingkungan Hidup'],
            ['kode' => '600.4.2.1', 'keterangan' => 'Inventarisasi, Penerapan ekoregion, dan rencana perlindungan dan pengelolaan Lingkungan'],
            ['kode' => '600.4.2.2', 'keterangan' => 'Evaluasi Pemanfaatan Sumber Daya Alam'],
            ['kode' => '600.4.3', 'keterangan' => 'Penerapan Kebijakan Wilayah dan Sektor'],
            ['kode' => '600.4.3.1', 'keterangan' => 'Evaluasi Penerapan'],
            ['kode' => '600.4.3.2', 'keterangan' => 'Perencanaan Lingkungan Hidup'],
            ['kode' => '600.4.4', 'keterangan' => 'Ekonomi Lingkungan'],
            ['kode' => '600.4.5', 'keterangan' => 'Dampak Lingkungan'],
            ['kode' => '600.4.5.1', 'keterangan' => 'Bimtek Dampak Lingkungan'],
            ['kode' => '600.4.5.2', 'keterangan' => 'Penerapan sistem kebijakan Dampak lingkungan'],
            ['kode' => '600.4.5.3', 'keterangan' => 'Evaluasi dan Tindak Lanjut'],
            ['kode' => '600.4.6', 'keterangan' => 'Pemantauan dan Pengawasan'],
            ['kode' => '600.4.6.1', 'keterangan' => 'Manufaktur Prasarana dan Jasa'],
            ['kode' => '600.4.6.2', 'keterangan' => 'Pertambangan Energi, Minyak dan Gas'],
            ['kode' => '600.4.6.3', 'keterangan' => 'Agro Industri dan Usaha Skala Kecil'],
            ['kode' => '600.4.6.4', 'keterangan' => 'Udara Sumber Bergerak'],
            ['kode' => '600.4.7', 'keterangan' => 'Evaluasi dan Pengembangan'],
            ['kode' => '600.4.7.1', 'keterangan' => 'Manufaktur, Prasarana, dan Jasa'],
            ['kode' => '600.4.7.2', 'keterangan' => 'Pertambangan Energi, Minyak dan Gas'],
            ['kode' => '600.4.7.3', 'keterangan' => 'Agro Industri dan Usaha Skala Kecil'],
            ['kode' => '600.4.7.4', 'keterangan' => 'Udara Sumber Bergerak'],
            ['kode' => '600.4.8', 'keterangan' => 'Keanekaragaman Hayati dan pengendalian Kerusakan Lahan'],
            ['kode' => '600.4.8.1', 'keterangan' => 'Pengembangan'],
            ['kode' => '600.4.8.2', 'keterangan' => 'Pemanfaatan'],
            ['kode' => '600.4.8.3', 'keterangan' => 'Pengelolaan Sumber Daya Genetik'],
            ['kode' => '600.4.8.4', 'keterangan' => 'Keamanan Hayati'],
            ['kode' => '600.4.8.5', 'keterangan' => 'Pengendalian kerusakan Lahan'],
            ['kode' => '600.4.9', 'keterangan' => 'Kerusakan Ekosistem Perairan Darat'],
            ['kode' => '600.4.9.1', 'keterangan' => 'Kerusakan Ekosistem'],
            ['kode' => '600.4.9.2', 'keterangan' => 'Rawa'],
            ['kode' => '600.4.10', 'keterangan' => 'Mitigasi dan pelestarian Fungsi Atmosfer'],
            ['kode' => '600.4.10.1', 'keterangan' => 'Perangkat mitigasi'],
            ['kode' => '600.4.10.2', 'keterangan' => 'Inventarisasi Emisi Gas Rumah Kaca'],
            ['kode' => '600.4.10.3', 'keterangan' => 'Pengendalian Bahan Perusak Ozon'],
            ['kode' => '600.4.10.4', 'keterangan' => 'Pengendalian Kerusakan Akibat Kebakaran Hutan dan Lahan'],
            ['kode' => '600.4.11', 'keterangan' => 'Adaptasi Perubahan Iklim'],
            ['kode' => '600.4.11.1', 'keterangan' => 'Perangkat Adaptasi Perubahan Iklim antara lain: Pengembangan perangkat Adaptasi Perubahan Iklim, Pemantauan dan Evaluasi Adaptasi Perusahaan Iklim'],
            ['kode' => '600.4.11.2', 'keterangan' => 'Kerentanan Perubahan Iklim'],
            ['kode' => '600.4.12', 'keterangan' => 'Pengelolaan Bahan Berbahaya dan Beracun'],
            ['kode' => '600.4.12.1', 'keterangan' => 'Registrasi dan Notifikasi'],
            ['kode' => '600.4.12.2', 'keterangan' => 'Pemantauan Bahan Berbahaya dan Beracun'],
            ['kode' => '600.4.12.3', 'keterangan' => 'Evaluasi dan Tindak Lanjut'],
            ['kode' => '600.4.13', 'keterangan' => 'Verifikasi Pengelolaan Limbah bahan Berbahaya dan beracun'],
            ['kode' => '600.4.13.1', 'keterangan' => 'Pengumpulan dan pemanfaatan'],
            ['kode' => '600.4.13.2', 'keterangan' => 'Pengangkutan dan Pengolahan'],
            ['kode' => '600.4.13.3', 'keterangan' => 'Penimbunan dan Dumping'],
            ['kode' => '600.4.13.4', 'keterangan' => 'Notifikasi dan Rekomendasi Limbah Lintas batas'],
            ['kode' => '600.4.14', 'keterangan' => 'Pengelolaan Limbah B3 dan Pemulihan Kontaminasi Limbah B3'],
            ['kode' => '600.4.14.1', 'keterangan' => 'Pemantauan'],
            ['kode' => '600.4.14.2', 'keterangan' => 'Tanggap darurat dan pemulihan Kontaminasi'],
            ['kode' => '600.4.15', 'keterangan' => 'Pengelolaan Sampah'],
            ['kode' => '600.4.15.1', 'keterangan' => 'Pembatasan sampah'],
            ['kode' => '600.4.15.2', 'keterangan' => 'Daur Ulang dan Pemanfaatan Sampah'],
            ['kode' => '600.4.15.3', 'keterangan' => 'Pembentukan Dewan Adipura'],
            ['kode' => '600.4.15.4', 'keterangan' => 'Penetapan pemenang adipura'],
            ['kode' => '600.4.16', 'keterangan' => 'Hukum Administrasi Lingkungan'],
            ['kode' => '600.4.16.1', 'keterangan' => 'Pengelolaan dan pengembangan pengaduan'],
            ['kode' => '600.4.16.2', 'keterangan' => 'Penataan hukum administrasi lingkungan'],
            ['kode' => '600.4.17', 'keterangan' => 'Penyelesaian Sengketa Lingkungan'],
            ['kode' => '600.4.17.1', 'keterangan' => 'Penyelesaian sengketa Melalui Pengadilan'],
            ['kode' => '600.4.17.2', 'keterangan' => 'Penyelesaian sengketa lingkungan di luar pengadilan'],
            ['kode' => '600.4.18', 'keterangan' => 'Penegakan hukum pidana lingkungan'],
            ['kode' => '600.4.18.1', 'keterangan' => 'Penyidikan'],
            ['kode' => '600.4.18.2', 'keterangan' => 'Koordinasi penuntutan, evaluasi, dan tindak lanjut'],
            ['kode' => '600.4.18.3', 'keterangan' => 'Koordinasi pembinaan penyidik PNS'],
            ['kode' => '600.4.19', 'keterangan' => 'Komunikasi Lingkungan'],
            ['kode' => '600.4.19.1', 'keterangan' => 'Pengembangan Komunikasi'],
            ['kode' => '600.4.19.2', 'keterangan' => 'Publikasi dan Kampanye'],
            ['kode' => '600.4.20', 'keterangan' => 'Penguatan Inisiatif Masyarakat'],
            ['kode' => '600.4.20.1', 'keterangan' => 'Komunitas Pendidikan Lingkungan'],
            ['kode' => '600.4.20.2', 'keterangan' => 'Kearifan Lingkungan'],
            ['kode' => '600.4.21', 'keterangan' => 'Peningkatan Peran Masyarakat'],
            ['kode' => '600.4.21.1', 'keterangan' => 'Masyarakat Perkotaan'],
            ['kode' => '600.4.21.2', 'keterangan' => 'Masyarakat Pedesaan'],
            ['kode' => '600.4.22', 'keterangan' => 'Peningkatan Peran Organisasi Kemasyarakatan'],
            ['kode' => '600.4.22.1', 'keterangan' => 'Organisasi Sosial Masyarakat'],
            ['kode' => '600.4.22.2', 'keterangan' => 'Organisasi Profesi Dunia Usaha'],
            ['kode' => '600.4.23', 'keterangan' => 'Data dan Informasi Lingkungan'],
            ['kode' => '600.4.23.1', 'keterangan' => 'Pengelolaan Data'],
            ['kode' => '600.4.23.2', 'keterangan' => 'Pengelolaan Informasi'],
            ['kode' => '600.4.23.3', 'keterangan' => 'Pengembangan Perangkat Lunak'],
            ['kode' => '600.4.23.4', 'keterangan' => 'Pengembangan Sistem dan Layanan Jaringan'],
            ['kode' => '600.4.24', 'keterangan' => 'Kelembagaan Lingkungan'],
            ['kode' => '600.4.24.1', 'keterangan' => 'Kelembagaan dan Tata Laksana'],
            ['kode' => '600.4.24.2', 'keterangan' => 'Fasilitasi Standar Pelayanan Minimal'],
            ['kode' => '600.4.25', 'keterangan' => 'Standarisasi dan teknologi'],
            ['kode' => '600.4.25.1', 'keterangan' => 'Standarisasi Manajemen dan Pengujian Lingkungan'],
            ['kode' => '600.4.25.2', 'keterangan' => 'Standarisasi Kompetensi Keahlian dan Lembaga Penyedia Jasa Lingkungan'],
            ['kode' => '600.4.25.3', 'keterangan' => 'Teknologi Ramah Lingkungan'],
            ['kode' => '600.4.26', 'keterangan' => 'Pusat Sarana Pengendalian Dampak Lingkungan'],
            ['kode' => '600.4.26.1', 'keterangan' => 'Pemantauan dan Kajian Kualitas Lingkungan'],
            ['kode' => '600.4.26.2', 'keterangan' => 'Laboratorium Rujukan dan Pengujian'],
        ];

        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
