<?php

namespace Database\Seeders;

use App\Models\KodeKlasifikasi;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KodeKlasifikasi400Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            ['kode' => '400', 'keterangan' => 'KESEJAHTERAAN RAKYAT'],
            ['kode' => '400.1', 'keterangan' => 'PEMBANGUNAN DAERAH TERTINGGAL'],
            ['kode' => '400.1.1', 'keterangan' => 'Kebijakan di bidang Pembangunan Daerah Tertinggal yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.1.2', 'keterangan' => 'Pembangunan Sumber Daya'],
            ['kode' => '400.1.2.1', 'keterangan' => 'Fasilitasi Pendidikan ketrampilan Pengembangan Sumber Daya'],
            ['kode' => '400.1.2.2', 'keterangan' => 'Fasilitasi Kesehatan Pengembangan Sumber Daya'],
            ['kode' => '400.1.2.3', 'keterangan' => 'Fasilitasi Sumber daya hayati dan Pengembangan Sumber Daya'],
            ['kode' => '400.1.2.4', 'keterangan' => 'Fasilitasi Mineral, energi dan lingkungan hidup'],
            ['kode' => '400.1.2.5', 'keterangan' => 'Fasilitasi Teknologi dan inovasi'],
            ['kode' => '400.1.2.6', 'keterangan' => 'Koordinasi pelaksanaan kebijakan pengembangan sumber daya'],
            ['kode' => '400.1.2.7', 'keterangan' => 'Pemantauan dan evaluasi'],
            ['kode' => '400.1.3', 'keterangan' => 'Peningkatan Infrastruktur'],
            ['kode' => '400.1.3.1', 'keterangan' => 'Fasilitasi Transportasi peningkatan infrastruktur'],
            ['kode' => '400.1.3.2', 'keterangan' => 'Fasilitasi Informasi dan Telekomunikasi dalam peningkatan infrastruktur'],
            ['kode' => '400.1.3.3', 'keterangan' => 'Fasilitasi Sosial dalam peningkatan infrastruktur'],
            ['kode' => '400.1.3.4', 'keterangan' => 'Fasilitasi Ekonomi dalam peningkatan infrastruktur'],
            ['kode' => '400.1.3.5', 'keterangan' => 'Fasilitasi energi dalam peningkatan infrastruktur'],
            ['kode' => '400.1.3.6', 'keterangan' => 'Koordinasi pelaksanaan kebijakan peningkatan infrastruktur'],
            ['kode' => '400.1.3.7', 'keterangan' => 'Pemantauan dan evaluasi'],
            ['kode' => '400.1.4', 'keterangan' => 'Pembinaan Ekonomi dan Dunia Usaha'],
            ['kode' => '400.1.4.1', 'keterangan' => 'Fasilitasi Invenstasi pembinaan ekonomi dan dunia usaha'],
            ['kode' => '400.1.4.2', 'keterangan' => 'Fasilitasi Kelembagaan ekonomi dan dunia usaha'],
            ['kode' => '400.1.4.3', 'keterangan' => 'Fasilitasi Usaha mikro, kecil dan menengah'],
            ['kode' => '400.1.4.4', 'keterangan' => 'Fasilitasi Kemitraan usaha'],
            ['kode' => '400.1.4.5', 'keterangan' => 'Fasilitasi Pengembangan komoditas unggulan'],
            ['kode' => '400.1.4.6', 'keterangan' => 'Koordinasi pelaksanaan kebijakan pembinaan ekonomi dan dunia usaha'],
            ['kode' => '400.1.4.7', 'keterangan' => 'Pemantauan dan evaluasi'],
            ['kode' => '400.1.4.8', 'keterangan' => 'Identifikasi dan inventarisasi pengembangan usaha ekonomi perdesaan tertinggal'],
            ['kode' => '400.1.4.9', 'keterangan' => 'Fasilitasi pengembangan usaha ekonomi perdesaan tertinggal'],
            ['kode' => '400.1.4.10', 'keterangan' => 'Monitoring dan evaluasi Ekonomi desa tertinggal'],
            ['kode' => '400.1.4.11', 'keterangan' => 'Identifikasi dan inventarisasi pengembangan masyarakat dan desa tertinggal'],
            ['kode' => '400.1.4.12', 'keterangan' => 'Fasilitasi pengembangan masyarakat dan desa tertinggal'],
            ['kode' => '400.1.4.13', 'keterangan' => 'Monitoring dan evaluasi Masyarakat tertinggal'],
            ['kode' => '400.1.4.14', 'keterangan' => 'Fasilitasi Kerja Sama antar Desa'],
            ['kode' => '400.1.5', 'keterangan' => 'Pembinaan Lembaga Sosial dan Budaya'],
            ['kode' => '400.1.5.1', 'keterangan' => 'Penguatan kapasitas lembaga lokal'],
            ['kode' => '400.1.5.2', 'keterangan' => 'Penguatan organisasi masyarakat'],
            ['kode' => '400.1.5.3', 'keterangan' => 'Pemberdayaan masyarakat'],
            ['kode' => '400.1.5.4', 'keterangan' => 'Kerjasama antar lembaga sosial dan budaya'],
            ['kode' => '400.1.5.5', 'keterangan' => 'Ketenagakerjaan'],
            ['kode' => '400.1.5.6', 'keterangan' => 'Koordinasi pelaksanaan kebijakan pembinaan lembaga sosial dan budaya'],
            ['kode' => '400.1.5.7', 'keterangan' => 'Pemantauan dan evaluasi'],
            ['kode' => '400.1.6', 'keterangan' => 'Pengembangan Daerah Khusus'],
            ['kode' => '400.1.6.1', 'keterangan' => 'Fasilitasi pengembangan Daerah perbatasan'],
            ['kode' => '400.1.6.2', 'keterangan' => 'Fasilitasi pengembangan Daerah rawan konflik dan bencana'],
            ['kode' => '400.1.6.3', 'keterangan' => 'Fasilitasi pengembangan Daerah Perdesaan'],
            ['kode' => '400.1.6.4', 'keterangan' => 'Fasilitasi pengembangan Daerah pulau terpencil dan terluar'],
            ['kode' => '400.1.6.5', 'keterangan' => 'Fasilitasi pengembangan Wilayah strategis'],
            ['kode' => '400.1.6.6', 'keterangan' => 'Koordinasi pelaksanaan kebijakan pengembangan daerah khusus'],
            ['kode' => '400.1.6.7', 'keterangan' => 'Pemantauan dan evaluasi'],
            ['kode' => '400.2', 'keterangan' => 'PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK'],
            ['kode' => '400.2.1', 'keterangan' => 'Kebijakan di bidang Pemberdayaan Perempuan dan Perlindungan Anak yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.2.2', 'keterangan' => 'Pengarusutamaan Gender Ekonomi, Politik Sosial dan Hukum'],
            ['kode' => '400.2.2.1', 'keterangan' => 'Data gender'],
            ['kode' => '400.2.2.2', 'keterangan' => 'Advokasi dan fasilitasi'],
            ['kode' => '400.2.3', 'keterangan' => 'Perlindungan Perempuan (Kekerasan, Masalah Sosial, Tenaga Kerja, Korban Perdagangan)'],
            ['kode' => '400.2.3.1', 'keterangan' => 'Pencegahan Kekerasan terhadap Perempuan'],
            ['kode' => '400.2.3.2', 'keterangan' => 'Data perlindungan perempuan'],
            ['kode' => '400.2.3.3', 'keterangan' => 'Advokasi dan fasilitasi'],
            ['kode' => '400.2.3.4', 'keterangan' => 'Monitoring, evaluasi dan analisa kebijakan perlindungan perempuan'],
            ['kode' => '400.2.3.5', 'keterangan' => 'Sistem aplikasi dan jaringan informasi gender'],
            ['kode' => '400.2.3.6', 'keterangan' => 'Analisis dan penyajian informasi gender'],
            ['kode' => '400.2.3.7', 'keterangan' => 'Partisipasi publik untuk kesejahteraan ibu'],
            ['kode' => '400.2.4', 'keterangan' => 'Perlindungan Anak (Hak Sipil, Masalah Sosial, Kekerasan Terhadap Anak, Anak Berkebutuhan Khusus, Anak Berhadapan Dengan Hukum)'],
            ['kode' => '400.2.4.1', 'keterangan' => 'Pencegahan Kekerasan terhadap Anak'],
            ['kode' => '400.2.4.2', 'keterangan' => 'Data perlindungan anak'],
            ['kode' => '400.2.4.3', 'keterangan' => 'Advokasi dan fasilitasi'],
            ['kode' => '400.2.4.4', 'keterangan' => 'Monitoring, evaluasi dan analisa kebijakan perlindungan anak'],
            ['kode' => '400.2.4.5', 'keterangan' => 'Partisipasi publik untuk kesejahteraan anak'],
            ['kode' => '400.2.5', 'keterangan' => 'Tumbuh Kembang Anak (Pendidikan, Kesehatan, Partisipasi, Lingkungan dan Penanaman Nilai-Nilai Luhur, Pengembangan Kota Layak Anak)'],
            ['kode' => '400.2.5.1', 'keterangan' => 'Pemenuhan Hak Anak'],
            ['kode' => '400.2.5.2', 'keterangan' => 'Data Klaster Hak Anak'],
            ['kode' => '400.2.5.3', 'keterangan' => 'Data tumbuh kembang anak'],
            ['kode' => '400.2.5.4', 'keterangan' => 'Advokasi dan fasilitasi'],
            ['kode' => '400.2.5.5', 'keterangan' => 'Monitoring, evaluasi dan analisa kebijakan tumbuh kembang anak'],
            ['kode' => '400.2.5.6', 'keterangan' => 'Penyelenggaraan parenting pola pengasuhan anak'],
            ['kode' => '400.2.6', 'keterangan' => 'Penghargaan terkait gender (Anugerah Parahita Ekapraya/APE)'],
            ['kode' => '400.2.7', 'keterangan' => 'Penghargaan Kabupaten Layak Anak'],
            ['kode' => '400.2.8', 'keterangan' => 'Penghargaan Desa Ramah Perempuan Peduli Anak'],
            ['kode' => '400.3', 'keterangan' => 'PENDIDIKAN'],
            ['kode' => '400.3.1', 'keterangan' => 'Kebijakan di bidang Pendidikan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.3.2', 'keterangan' => 'Pendidikan Anak Usia Dini (PAUD) Nonformal, Informal'],
            ['kode' => '400.3.2.1', 'keterangan' => 'Bahan Ajar (Alat Permainan Edukatif)'],
            ['kode' => '400.3.2.2', 'keterangan' => 'Pelatihan Sosial'],
            ['kode' => '400.3.2.3', 'keterangan' => 'Peringatan Hari anak'],
            ['kode' => '400.3.2.4', 'keterangan' => 'Block Grant'],
            ['kode' => '400.3.3', 'keterangan' => 'Pendidikan Masyarakat'],
            ['kode' => '400.3.3.1', 'keterangan' => 'Penyelenggaraan Program'],
            ['kode' => '400.3.3.2', 'keterangan' => 'Penilaian dan pemberian bantuan sosial'],
            ['kode' => '400.3.3.3', 'keterangan' => 'Pembinaan Program'],
            ['kode' => '400.3.3.4', 'keterangan' => 'Lomba/Pemberian Penghargaan'],
            ['kode' => '400.3.3.5', 'keterangan' => 'Pameran'],
            ['kode' => '400.3.3.6', 'keterangan' => 'Rakor'],
            ['kode' => '400.3.3.7', 'keterangan' => 'Sosialisasi'],
            ['kode' => '400.3.3.8', 'keterangan' => 'Sertifikasi dan Akreditasi'],
            ['kode' => '400.3.4', 'keterangan' => 'Kursus/Pelatihan Pendidik dan Tenaga Pendidik'],
            ['kode' => '400.3.5', 'keterangan' => 'Pendidikan Dasar dan Menengah Pertama'],
            ['kode' => '400.3.5.1', 'keterangan' => 'Kurikulum, bahan ajar'],
            ['kode' => '400.3.5.2', 'keterangan' => 'Block Grant'],
            ['kode' => '400.3.5.3', 'keterangan' => 'Pelatihan, Bimtek, sosialisasi,'],
            ['kode' => '400.3.5.4', 'keterangan' => 'Lomba, penghargaan, penganugerahan'],
            ['kode' => '400.3.5.5', 'keterangan' => 'Bantuan operasional sekolah (BOS)'],
            ['kode' => '400.3.5.6', 'keterangan' => 'Bantuan Siswa Miskin'],
            ['kode' => '400.3.6', 'keterangan' => 'Pendidikan khusus/Layanan Khusus'],
            ['kode' => '400.3.6.1', 'keterangan' => 'Kurikulum, Bahan ajar, alat bantu pembelajaran'],
            ['kode' => '400.3.6.2', 'keterangan' => 'Block Grant'],
            ['kode' => '400.3.6.3', 'keterangan' => 'Lomba, festival'],
            ['kode' => '400.3.6.4', 'keterangan' => 'Sosialisasi, bimtek'],
            ['kode' => '400.3.6.5', 'keterangan' => 'Pendataan'],
            ['kode' => '400.3.6.6', 'keterangan' => 'Kelembagaan'],
            ['kode' => '400.3.7', 'keterangan' => 'Pembinaan Pendidik dan Tenaga Pendidik'],
            ['kode' => '400.3.7.1', 'keterangan' => 'Pendataan dan Pemetaan'],
            ['kode' => '400.3.7.2', 'keterangan' => 'Uji Kompetensi Guru'],
            ['kode' => '400.3.7.3', 'keterangan' => 'Sertifikasi Guru'],
            ['kode' => '400.3.7.4', 'keterangan' => 'Penghargaan guru dan tenaga kependidikan'],
            ['kode' => '400.3.7.5', 'keterangan' => 'Peningkatan kesejahteraan guru'],
            ['kode' => '400.3.7.6', 'keterangan' => 'Sosialisasi, bimtek'],
            ['kode' => '400.3.7.7', 'keterangan' => 'Block Grant'],
            ['kode' => '400.3.8', 'keterangan' => 'Sekolah Menengah Atas'],
            ['kode' => '400.3.8.1', 'keterangan' => 'Kurikulum'],
            ['kode' => '400.3.8.2', 'keterangan' => 'Bahan Ajar'],
            ['kode' => '400.3.8.3', 'keterangan' => 'Pelatihan'],
            ['kode' => '400.3.8.4', 'keterangan' => 'Block grant'],
            ['kode' => '400.3.8.5', 'keterangan' => 'Bimbingan teknis/sosialisasi'],
            ['kode' => '400.3.8.6', 'keterangan' => 'Lomba, Sayembara, festival'],
            ['kode' => '400.3.8.7', 'keterangan' => 'Bantuan operasional Sekolah (BOS)'],
            ['kode' => '400.3.8.8', 'keterangan' => 'Bantuan siswa miskin'],
            ['kode' => '400.3.9', 'keterangan' => 'Pendidikan Khusus-Layanan Khusus'],
            ['kode' => '400.3.9.1', 'keterangan' => 'Bahan ajar'],
            ['kode' => '400.3.9.2', 'keterangan' => 'Petunjuk Teknis'],
            ['kode' => '400.3.9.3', 'keterangan' => 'Block grant'],
            ['kode' => '400.3.9.4', 'keterangan' => 'Sosialisasi, bimtek'],
            ['kode' => '400.3.9.5', 'keterangan' => 'Lomba, sayembara, jambore, festival'],
            ['kode' => '400.3.9.6', 'keterangan' => 'Kurikulum/bahan pembelajaran'],
            ['kode' => '400.3.9.7', 'keterangan' => 'Alat bantu pembelajaran'],
            ['kode' => '400.3.9.8', 'keterangan' => 'Pendataan'],
            ['kode' => '400.3.9.9', 'keterangan' => 'Kelembagaan (Unit kesehatan sekolah, Pendidikan jasmani adaptif, pendidikan inklusi'],
            ['kode' => '400.3.10', 'keterangan' => 'Pendidik dan Tenaga Pendidik'],
            ['kode' => '400.3.10.1', 'keterangan' => 'Pendataan dan Pemetaan'],
            ['kode' => '400.3.10.2', 'keterangan' => 'Uji Kompetensi Guru'],
            ['kode' => '400.3.10.3', 'keterangan' => 'Sertifikasi Guru'],
            ['kode' => '400.3.10.4', 'keterangan' => 'Penilaian prestasi kerja guru dan pengawas sekolah'],
            ['kode' => '400.3.10.5', 'keterangan' => 'Penghargaan guru dan tenaga kependidikan'],
            ['kode' => '400.3.10.6', 'keterangan' => 'Peningkatan kesejahteraan guru dan tenaga pendidik'],
            ['kode' => '400.3.10.7', 'keterangan' => 'Block grant'],
            ['kode' => '400.3.10.8', 'keterangan' => 'Bimbingan teknis/sosialisasi'],
            ['kode' => '400.3.11', 'keterangan' => 'Penilaian Pendidikan'],
            ['kode' => '400.3.11.1', 'keterangan' => 'Penilaian Akademik'],
            ['kode' => '400.3.11.2', 'keterangan' => 'Penilaian Non Akademik'],
            ['kode' => '400.3.11.3', 'keterangan' => 'Analisis dan Sistem Informasi Penilaian'],
            ['kode' => '400.3.12', 'keterangan' => 'Data dan Statistik Pendidikan'],
            ['kode' => '400.3.12.1', 'keterangan' => 'Data peserta didik, pendidik dan tenaga kependidikan'],
            ['kode' => '400.3.12.2', 'keterangan' => 'Data Satuan Pendidikan dan Proses Pembelajaran'],
            ['kode' => '400.3.13', 'keterangan' => 'Prasarana dan Sarana Pendidikan'],
            ['kode' => '400.3.13.1', 'keterangan' => 'Prasarana Pendidikan'],
            ['kode' => '400.3.13.2', 'keterangan' => 'Sarana Pendidikan'],
            ['kode' => '400.3.13.3', 'keterangan' => 'Monitoring dan Evaluasi'],
            ['kode' => '400.4', 'keterangan' => 'KEOLAHRAGAAN'],
            ['kode' => '400.4.1', 'keterangan' => 'Kebijakan di bidang Keolahragaan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.4.2', 'keterangan' => 'Pengelolaan Olahraga Pendidikan'],
            ['kode' => '400.4.2.1', 'keterangan' => 'Olahraga Pendidikan Dasar dan Menengah'],
            ['kode' => '400.4.2.2', 'keterangan' => 'Olahraga Pendidikan Tinggi'],
            ['kode' => '400.4.2.3', 'keterangan' => 'Olahraga Pendidikan Nonformal dan Informal'],
            ['kode' => '400.4.3', 'keterangan' => 'Pengelolaan Olahraga Rekreasi'],
            ['kode' => '400.4.3.1', 'keterangan' => 'Olahraga Massal'],
            ['kode' => '400.4.3.2', 'keterangan' => 'Olahraga Tradisional'],
            ['kode' => '400.4.3.3', 'keterangan' => 'Olahraga Petualangan, Tantangan dan wisata'],
            ['kode' => '400.4.4', 'keterangan' => 'Pengelolaan Pembinaan Sentra dan sekolah Khusus Olahraga'],
            ['kode' => '400.4.4.1', 'keterangan' => 'Olahraga Pendidikan'],
            ['kode' => '400.4.4.2', 'keterangan' => 'Olahraga Rekreasi'],
            ['kode' => '400.4.4.3', 'keterangan' => 'Olahraga Prestasi'],
            ['kode' => '400.4.4.4', 'keterangan' => 'Sekolah Khusus Olahraga'],
            ['kode' => '400.4.5', 'keterangan' => 'Pengembangan Olahraga Tradisional dan Layanan Khusus'],
            ['kode' => '400.4.5.1', 'keterangan' => 'Olahraga Tradisional'],
            ['kode' => '400.4.5.2', 'keterangan' => 'Layanan Khusus'],
            ['kode' => '400.4.6', 'keterangan' => 'Kemitraan dan Penghargaan Olahraga'],
            ['kode' => '400.4.6.1', 'keterangan' => 'Kemitraan Keolahragaan'],
            ['kode' => '400.4.6.2', 'keterangan' => 'Penghargaan Olahraga'],
            ['kode' => '400.4.7', 'keterangan' => 'Pembibitan dan IPTEK Olahraga'],
            ['kode' => '400.4.7.1', 'keterangan' => 'Pembibitan Olahraga'],
            ['kode' => '400.4.7.2', 'keterangan' => 'Kompetisi'],
            ['kode' => '400.4.7.3', 'keterangan' => 'IPTEK Olahraga'],
            ['kode' => '400.4.8', 'keterangan' => 'Peningkatan Tenaga dan Organisasi Keolahragaan'],
            ['kode' => '400.4.8.1', 'keterangan' => 'Tenaga Keolahragaan'],
            ['kode' => '400.4.8.2', 'keterangan' => 'Organisasi Keolahragaan'],
            ['kode' => '400.4.9', 'keterangan' => 'Industri dan Promosi Olahraga'],
            ['kode' => '400.4.9.1', 'keterangan' => 'Industri Olahraga'],
            ['kode' => '400.4.9.2', 'keterangan' => 'Promosi Olahraga'],
            ['kode' => '400.4.10', 'keterangan' => 'Olahraga Prestasi'],
            ['kode' => '400.4.10.1', 'keterangan' => 'Daerah'],
            ['kode' => '400.4.10.2', 'keterangan' => 'Nasional'],
            ['kode' => '400.4.10.3', 'keterangan' => 'Internasional'],
            ['kode' => '400.4.11', 'keterangan' => 'Standardisasi dan Infrastruktur Olahraga'],
            ['kode' => '400.4.11.1', 'keterangan' => 'Standardisasi Keolahragaan'],
            ['kode' => '400.4.11.2', 'keterangan' => 'Akreditasi dan Sertifikasi Keolahragaan'],
            ['kode' => '400.4.11.3', 'keterangan' => 'Infrastruktur Olahraga'],
            ['kode' => '400.5', 'keterangan' => 'KEPEMUDAAN'],
            ['kode' => '400.5.1', 'keterangan' => 'Kebijakan di bidang Kepemudaan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.5.2', 'keterangan' => 'Peningkatan Tenaga dan Sumber Daya Pemuda'],
            ['kode' => '400.5.2.1', 'keterangan' => 'Penelusuran (Duta Kepemudaan)'],
            ['kode' => '400.5.2.2', 'keterangan' => 'Pengkajian (Rekomendasi Kepemudaan melalui forum kepemudaan)'],
            ['kode' => '400.5.2.3', 'keterangan' => 'Pengembangan'],
            ['kode' => '400.5.3', 'keterangan' => 'Peningkatan Wawasan Pemuda'],
            ['kode' => '400.5.3.1', 'keterangan' => 'Wawasan Kebangsaan'],
            ['kode' => '400.5.3.2', 'keterangan' => 'Wawasan Lingkungan'],
            ['kode' => '400.5.3.3', 'keterangan' => 'Wawasan Sosial dan Hukum'],
            ['kode' => '400.5.4', 'keterangan' => 'Peningkatan Kapasitas Pemuda'],
            ['kode' => '400.5.4.1', 'keterangan' => 'Kapasitas Iman dan Taqwa'],
            ['kode' => '400.5.4.2', 'keterangan' => 'Kapasitas IPTEK'],
            ['kode' => '400.5.4.3', 'keterangan' => 'Pemanfaatan IPTEK'],
            ['kode' => '400.5.5', 'keterangan' => 'Peningkatan Kreativitas Pemuda (Pemetaan Kreativitas/seni kepemudaan)'],
            ['kode' => '400.5.5.1', 'keterangan' => 'Pengkajian'],
            ['kode' => '400.5.5.2', 'keterangan' => 'Pengembangan'],
            ['kode' => '400.5.5.3', 'keterangan' => 'Pendayagunaan (fasilitasi)'],
            ['kode' => '400.5.6', 'keterangan' => 'Kepemimpinan dan Kepeloporan Pemuda'],
            ['kode' => '400.5.6.1', 'keterangan' => 'Kepemimpinan: Penelusuran, Pengaderan, Pendayagunaan'],
            ['kode' => '400.5.6.2', 'keterangan' => 'Kepeloporan Pemuda: Kesukarelawanan, Pengembangan kepedulian, pendampingan'],
            ['kode' => '400.5.7', 'keterangan' => 'Kewirausahaan'],
            ['kode' => '400.5.7.1', 'keterangan' => 'Kelembagaan'],
            ['kode' => '400.5.7.2', 'keterangan' => 'Pengaderan'],
            ['kode' => '400.5.7.3', 'keterangan' => 'Perintisan'],
            ['kode' => '400.5.8', 'keterangan' => 'Organisasi Kepemudaan dan Pengawasan Kepramukaan'],
            ['kode' => '400.5.8.1', 'keterangan' => 'Pemberdayaan Organisasi Kepemudaan: Kelembagaan dan Sumberdaya'],
            ['kode' => '400.5.8.2', 'keterangan' => 'Pemberdayaan Organisasi Kemahasiswaan: Kelembagaan dan Sumberdaya'],
            ['kode' => '400.5.8.3', 'keterangan' => 'Pemberdayaan Organisasi Kepelajaran: Kelembagaan dan Sumberdaya'],
            ['kode' => '400.5.8.4', 'keterangan' => 'Pengawasan Kepramukaan: Kelembagaan, Program dan Sumberdaya'],
            ['kode' => '400.5.9', 'keterangan' => 'Standardisasi dan Infrastruktur Pemuda'],
            ['kode' => '400.5.9.1', 'keterangan' => 'Standardisasi'],
            ['kode' => '400.5.9.2', 'keterangan' => 'Infrastruktur Pemuda'],
            ['kode' => '400.5.10', 'keterangan' => 'Kemitraan dan Penghargaan Pemuda'],
            ['kode' => '400.5.10.1', 'keterangan' => 'Kemitraan'],
            ['kode' => '400.5.10.2', 'keterangan' => 'Penghargaan Pemuda'],
            ['kode' => '400.6', 'keterangan' => 'KEBUDAYAAN'],
            ['kode' => '400.6.1', 'keterangan' => 'Kebijakan di bidang Kebudayaan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.6.2', 'keterangan' => 'Pelestarian Cagar Budaya dan Permuseuman'],
            ['kode' => '400.6.2.1', 'keterangan' => 'Registrasi Nasional'],
            ['kode' => '400.6.2.2', 'keterangan' => 'Pelindungan'],
            ['kode' => '400.6.2.3', 'keterangan' => 'Pengembangan dan Pemanfaatan'],
            ['kode' => '400.6.2.4', 'keterangan' => 'Eksplorasi dan Dokumentasi'],
            ['kode' => '400.6.3', 'keterangan' => 'Pembinaan Kesenian dan Perfilman'],
            ['kode' => '400.6.3.1', 'keterangan' => 'Pembinaan Seni Pertunjukan'],
            ['kode' => '400.6.3.2', 'keterangan' => 'Pembinaan Seni Rupa'],
            ['kode' => '400.6.3.3', 'keterangan' => 'Pembinaan Seni Literasi dan apresiasi film'],
            ['kode' => '400.6.3.4', 'keterangan' => 'Dokumentasi dan Publikasi'],
            ['kode' => '400.6.4', 'keterangan' => 'Sejarah dan Nilai Budaya'],
            ['kode' => '400.6.4.1', 'keterangan' => 'Sejarah'],
            ['kode' => '400.6.4.2', 'keterangan' => 'Pemetaan nilai'],
            ['kode' => '400.6.4.3', 'keterangan' => 'Verifikasi dan Perumusan Nilai'],
            ['kode' => '400.6.4.4', 'keterangan' => 'Dokumentasi dan Publikasi'],
            ['kode' => '400.6.4.5', 'keterangan' => 'Dokumentasi sejarah dan nilai sejarah'],
            ['kode' => '400.6.4.6', 'keterangan' => 'Publikasi sejarah dan nilai sejarah'],
            ['kode' => '400.6.5', 'keterangan' => 'Internalisasi Nilai dan Diplomasi Budaya'],
            ['kode' => '400.6.5.1', 'keterangan' => 'Internalisasi nilai budaya'],
            ['kode' => '400.6.5.2', 'keterangan' => 'Kekayaan budaya'],
            ['kode' => '400.6.5.3', 'keterangan' => 'Warisan budaya nasional dan dunia'],
            ['kode' => '400.6.5.4', 'keterangan' => 'Diplomasi budaya'],
            ['kode' => '400.7', 'keterangan' => 'KESEHATAN'],
            ['kode' => '400.7.1', 'keterangan' => 'Kebijakan di bidang Kesehatan yang dilakukan oleh Pemerintah Daerah'],
            ['kode' => '400.7.2', 'keterangan' => 'Upaya Kesehatan Dasar'],
            ['kode' => '400.7.2.1', 'keterangan' => 'Pelayanan kedokteran keluarga'],
            ['kode' => '400.7.2.2', 'keterangan' => 'Praktek klinis dokter di pelayanan kesehatan primer'],
            ['kode' => '400.7.2.3', 'keterangan' => 'Pelaksanaan kesehatan primer'],
            ['kode' => '400.7.2.4', 'keterangan' => 'Kesehatan gigi dan mulut di puskesmas'],
            ['kode' => '400.7.2.5', 'keterangan' => 'Kesehatan gigi dan mulut di rumah sakit'],
            ['kode' => '400.7.2.6', 'keterangan' => 'ICD 10, Destistry & Stomatology'],
            ['kode' => '400.7.2.7', 'keterangan' => 'Infeksi menular lewat transfusi darah'],
            ['kode' => '400.7.2.8', 'keterangan' => 'Penyakit mulut di tingkat primer'],
            ['kode' => '400.7.2.9', 'keterangan' => 'Pembiayaan darah'],
            ['kode' => '400.7.2.10', 'keterangan' => 'Penggunaan darah rasional'],
            ['kode' => '400.7.2.11', 'keterangan' => 'Unit transfusi darah, bank darah rumah sakit dan jejaring pelayanan darah'],
            ['kode' => '400.7.2.12', 'keterangan' => 'Pelayanan kesehatan di daerah terpencil, sangat terpencil dan kepulauan'],
            ['kode' => '400.7.2.13', 'keterangan' => 'Akreditasi puskesmas'],
            ['kode' => '400.7.2.14', 'keterangan' => 'Puskesmas berprestasi'],
            ['kode' => '400.7.3', 'keterangan' => 'Upaya Kesehatan Rujukan'],
            ['kode' => '400.7.3.1', 'keterangan' => 'Pelayanan kesehatan rujukan'],
            ['kode' => '400.7.3.2', 'keterangan' => 'Pelayanan kedokteran, organisasi profesi dan konsorsium upaya kesehatan (KUK)'],
            ['kode' => '400.7.3.3', 'keterangan' => 'Pelayanan rumah sakit privat'],
            ['kode' => '400.7.3.4', 'keterangan' => 'Pelayanan kesehatan rumah sakit khusus dan fasilitas pelayanan kesehatan lainnya'],
            ['kode' => '400.7.3.5', 'keterangan' => 'Pelayanan kesehatan rumah sakit pendidikan'],
            ['kode' => '400.7.3.6', 'keterangan' => 'Pelayanan pasien jaminan kesehatan'],
            ['kode' => '400.7.3.7', 'keterangan' => 'Fasilitas pelayanan kesehatan asing dan perdagangan jasa'],
            ['kode' => '400.7.3.8', 'keterangan' => 'Badan pengawas rumah sakit'],
            ['kode' => '400.7.3.9', 'keterangan' => 'Perizinan dan penetapan kelas rumah sakit kelas A dan Penanam Modal Asing (PMA)'],
            ['kode' => '400.7.3.10', 'keterangan' => 'Akreditasi rumah sakit dan fasilitas kesehatan lainnya'],
            ['kode' => '400.7.4', 'keterangan' => 'Keperawatan dan keteknisian medik'],
            ['kode' => '400.7.4.1', 'keterangan' => 'Pelayanan Keperawatan Dasar'],
            ['kode' => '400.7.4.2', 'keterangan' => 'Pelayanan keperawatan profesional di rumah sakit'],
            ['kode' => '400.7.4.3', 'keterangan' => 'Pelayanan Keperawatan di Rumah Sakit Umum'],
            ['kode' => '400.7.4.4', 'keterangan' => 'Pelayanan Keperawatan di Rumah Sakit Khusus'],
            ['kode' => '400.7.4.5', 'keterangan' => 'Bina pelayanan kebidanan'],
            ['kode' => '400.7.5', 'keterangan' => 'Penunjang medik dan sarana kesehatan'],
            ['kode' => '400.7.5.1', 'keterangan' => 'Mikrobiologi dan imunologi'],
            ['kode' => '400.7.5.2', 'keterangan' => 'Patologi dan toksikologi'],
            ['kode' => '400.7.5.3', 'keterangan' => 'Radiologi'],
            ['kode' => '400.7.5.4', 'keterangan' => 'Perizinan dan sertifikasi'],
            ['kode' => '400.7.5.5', 'keterangan' => 'Sarana dan prasarana kesehatan'],
            ['kode' => '400.7.5.6', 'keterangan' => 'Peralatan medis di fasilitas pelayanan kesehatan'],
            ['kode' => '400.7.5.7', 'keterangan' => 'Aplikasi sarana dan prasarana alat kesehatan'],
            ['kode' => '400.7.6', 'keterangan' => 'Kesehatan Jiwa'],
            ['kode' => '400.7.6.1', 'keterangan' => 'Kesehatan jiwa di non fasilitas pelayanan kesehatan'],
            ['kode' => '400.7.6.2', 'keterangan' => 'Bina kesehatan jiwa di fasilitas pelayanan kesehatan'],
            ['kode' => '400.7.6.3', 'keterangan' => 'Etikolegal dan asesmen'],
            ['kode' => '400.7.6.4', 'keterangan' => 'Percegahan dan penanggulangan narkotika dan sejenisnya'],
            ['kode' => '400.7.6.5', 'keterangan' => 'Etikolegal dan asesmen'],
            ['kode' => '400.7.6.6', 'keterangan' => 'Kesehatan jiwa kelompok beresiko'],
            ['kode' => '400.7.7', 'keterangan' => 'Surveilans, Imunisasi, Karantina dan Kesehatan Matra'],
            ['kode' => '400.7.7.1', 'keterangan' => 'Surveilans dan respon kejadian luar biasa'],
            ['kode' => '400.7.7.2', 'keterangan' => 'Imunisasi'],
            ['kode' => '400.7.7.3', 'keterangan' => 'Karantina kesehatan dan kesehatan di pelabuhan'],
            ['kode' => '400.7.7.4', 'keterangan' => 'Kesehatan matra'],
            ['kode' => '400.7.8', 'keterangan' => 'Pengendalian penyakit menular langsung'],
            ['kode' => '400.7.8.1', 'keterangan' => 'Pengendalian tuberkolosis'],
            ['kode' => '400.7.8.2', 'keterangan' => 'Pengendalian AIDS dan penyakit menular seksual'],
            ['kode' => '400.7.8.3', 'keterangan' => 'Pengendalian infeksi saluran pernafasan akut'],
            ['kode' => '400.7.8.4', 'keterangan' => 'Pengendalian diare dan infeksi saluran pencernaan'],
            ['kode' => '400.7.8.5', 'keterangan' => 'Pengendalian kusta dan frambusia'],
            ['kode' => '400.7.9', 'keterangan' => 'Pengendalian penyakit bersumber binatang'],
            ['kode' => '400.7.9.1', 'keterangan' => 'Pengendalian malaria'],
            ['kode' => '400.7.9.2', 'keterangan' => 'Pengendalian arbovirosis'],
            ['kode' => '400.7.9.3', 'keterangan' => 'Pengendalian zoonosis'],
            ['kode' => '400.7.9.4', 'keterangan' => 'Pengendalian filariasis dan kecacingan'],
            ['kode' => '400.7.10', 'keterangan' => 'Pengendalian penyakit tidak menular'],
            ['kode' => '400.7.10.1', 'keterangan' => 'Pengendalian penyakit jantung dan pembuluh darah'],
            ['kode' => '400.7.10.2', 'keterangan' => 'Pengendalian penyakit diabetes melitus dan penyakit metabolik'],
            ['kode' => '400.7.10.3', 'keterangan' => 'Penyakit kanker'],
            ['kode' => '400.7.10.4', 'keterangan' => 'Penyakit kronis dan generatif'],
            ['kode' => '400.7.10.5', 'keterangan' => 'Gangguan akibat kecelakaan dan tindak kekerasan'],
            ['kode' => '400.7.11', 'keterangan' => 'Penyehatan lingkungan'],
            ['kode' => '400.7.11.1', 'keterangan' => 'Penyehatan air dan sanitasi dasar'],
            ['kode' => '400.7.11.2', 'keterangan' => 'Pemukiman dan tempat umum'],
            ['kode' => '400.7.11.3', 'keterangan' => 'Kawasan dan sanitasi darurat'],
            ['kode' => '400.7.11.4', 'keterangan' => 'Higien sanitasi pangan'],
            ['kode' => '400.7.11.5', 'keterangan' => 'Pengamanan limbah, udara, radiasi'],
            ['kode' => '400.7.12', 'keterangan' => 'Pengembangan dan penapisan teknologi pengendalian penyakit dan pengendalian lingkungan'],
            ['kode' => '400.7.13', 'keterangan' => 'Gizi'],
            ['kode' => '400.7.13.1', 'keterangan' => 'Gizi makro'],
            ['kode' => '400.7.13.2', 'keterangan' => 'Gizi mikro'],
            ['kode' => '400.7.13.3', 'keterangan' => 'Gizi klinik dan diatetik'],
            ['kode' => '400.7.13.4', 'keterangan' => 'Konsumsi makanan dan jasa makanan'],
            ['kode' => '400.7.13.5', 'keterangan' => 'Kewaspadaan gizi'],
            ['kode' => '400.7.14', 'keterangan' => 'Kesehatan ibu'],
            ['kode' => '400.7.14.1', 'keterangan' => 'Kesehatan ibu hamil'],
            ['kode' => '400.7.14.2', 'keterangan' => 'Kesehatan ibu bersalin dan nifas'],
            ['kode' => '400.7.14.3', 'keterangan' => 'Kesehatan maternal dengan pencegahan komplikasi'],
            ['kode' => '400.7.14.4', 'keterangan' => 'Keluarga berencana'],
            ['kode' => '400.7.14.5', 'keterangan' => 'Perlindungan kesehatan reproduksi'],
            ['kode' => '400.7.15', 'keterangan' => 'Kesehatan anak'],
            ['kode' => '400.7.15.1', 'keterangan' => 'Kelangsungan hidup bayi'],
            ['kode' => '400.7.15.2', 'keterangan' => 'Kelangsungan anak balita dan pra sekolah'],
            ['kode' => '400.7.15.3', 'keterangan' => 'Kewaspadaan penanganan balita beresiko'],
            ['kode' => '400.7.15.4', 'keterangan' => 'Kualitas hidup anak usia sekolah dan remaja'],
            ['kode' => '400.7.15.5', 'keterangan' => 'Perlindungan kesehatan anak'],
            ['kode' => '400.7.16', 'keterangan' => 'Kesehatan Tradisional alternatif dan komplementer'],
            ['kode' => '400.7.16.1', 'keterangan' => 'Kesehatan tradisional keterampilan'],
            ['kode' => '400.7.16.2', 'keterangan' => 'Kesehatan tradisional ramuan'],
            ['kode' => '400.7.16.3', 'keterangan' => 'Kesehatan alternatif dan komplementer'],
            ['kode' => '400.7.16.4', 'keterangan' => 'Penapisan dan kemitraan'],
            ['kode' => '400.7.17', 'keterangan' => 'Kesehatan kerja dan Olah raga'],
            ['kode' => '400.7.17.1', 'keterangan' => 'Pelayanan kesehatan kerja'],
            ['kode' => '400.7.17.2', 'keterangan' => 'Kapasitas kerja'],
            ['kode' => '400.7.17.3', 'keterangan' => 'Lingkungan kerja'],
            ['kode' => '400.7.17.4', 'keterangan' => 'Kemitraan kesehatan kerja'],
            ['kode' => '400.7.17.5', 'keterangan' => 'Kesehatan perkotaan'],
            ['kode' => '400.7.17.6', 'keterangan' => 'Kesehatan olahraga'],
            ['kode' => '400.7.18', 'keterangan' => 'Obat Publik dan perbekalan kesehatan'],
            ['kode' => '400.7.18.1', 'keterangan' => 'Harga obat publik'],
            ['kode' => '400.7.18.2', 'keterangan' => 'Pengadaan obat'],
            ['kode' => '400.7.18.3', 'keterangan' => 'Perbekalan kesehatan'],
            ['kode' => '400.7.19', 'keterangan' => 'Produksi dan distribusi alat kesehatan'],
            ['kode' => '400.7.19.1', 'keterangan' => 'Alat kesehatan'],
            ['kode' => '400.7.19.2', 'keterangan' => 'Produsen dan distributor alat kesehatan dan obat'],
            ['kode' => '400.7.19.3', 'keterangan' => 'Produk diagnostik in vitro dan perbekalan kesehatan rumah tangga'],
            ['kode' => '400.7.20', 'keterangan' => 'Kefarmasian'],
            ['kode' => '400.7.20.1', 'keterangan' => 'Pelayanan kefarmasian'],
            ['kode' => '400.7.20.2', 'keterangan' => 'Farmasi klinis'],
            ['kode' => '400.7.20.3', 'keterangan' => 'Farmasi Komunitas'],
            ['kode' => '400.7.20.4', 'keterangan' => 'Penggunaan obat rasional'],
            ['kode' => '400.7.21', 'keterangan' => 'Produksi dan distribusi kefarmasian'],
            ['kode' => '400.7.21.1', 'keterangan' => 'Obat tradisional'],
            ['kode' => '400.7.21.2', 'keterangan' => 'Kosmetik dan makanan'],
            ['kode' => '400.7.21.3', 'keterangan' => 'Narkotika, psikotropika, prekursor farmasi dan sediaan farmasi khusus'],
            ['kode' => '400.7.21.4', 'keterangan' => 'Kemandirian obat dan bahan baku obat'],
            ['kode' => '400.7.22', 'keterangan' => 'Surat Keterangan, Sertifikasi dan Perijinan'],
        ];
        foreach ($data as $item) {
            KodeKlasifikasi::create($item);
        }
    }
}
